apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-processor

resources:
  - configmap-lite.yaml
  - configmap-heavy.yaml
  - daemonset-lite.yaml
  - daemonset-heavy.yaml
