"use client";
import { useEffect,useMemo,useState,useRef } from "react";
import Link from "next/link";
import Image from "next/image";
import {useRouter} from "next/navigation";
import {BulkSupplyReviewPanel} from "./bulk-review-panel";
import { useWorkbenchContext } from "@/components/providers/workbench-context-provider";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell } from "@/components/ui/table";
import { ConsolePage,ConsoleState } from "../console/console-page";
import { CollectionDialog } from "../collections/collection-page";
import { useSupplyCommand } from "./use-supply-command";
import { SupplyCommandFeedback } from "./command-feedback";
import { SupplyTargetEditor } from "./target-editor";
import {UploadResolutionPanel} from "./upload-resolution-panel";
import {SupplyReviewPanel} from "./review-panel";
import type {ProductTitleProposal} from "@/lib/api/product-title-review";
import { SupplyAPIError,listSupplyPreparations,readSupplyPreparation,listSupplySources,listSupplyStages,readSupplySource,readSupplyTarget,readSupplyPublication,listSupplyOperations,readSupplyOperation,listSupplyOperationItems,controlSupplyOperation,readSupplyOptimizationOptions,type SupplyScope } from "@/lib/api/supply-chain";
import { uploadResolutionSchema,operationReceiptSchema,operationSchema,type SupplyPreparation,type SupplySourceDetail,type SupplyTarget,type SupplyOperation,type SupplyOperationItem,type SupplyPublication,type SupplyOptimizationOptions,type SupplyOptimizationChoice,type SupplyStagePage,type Stage } from "@/lib/contracts/supply-chain";
import { listWorkbenchStores,type WorkbenchStore } from "@/lib/api/workbench-stores";
const stages=["全部","待适配","待补全","已适配","待审核","已上传"] as const;
const itemLabels:Record<string,string>={pending:"等待处理",running:"处理中",succeeded:"已完成",missing:"待补全",review:"待审核",unknown:"结果待核实",denied:"权限不足",failed:"处理失败",cancelled:"已取消"};
const operationLabels:Record<string,string>={adapt:"适配",upload:"上传",optimize:"智能体优化",pending:"等待执行",running:"处理中",completed:"处理完成",cancelled:"已取消"};
export function SupplyPage({initialPreparation,initialStore,initialOperation,initialStage}:{initialPreparation?:string;initialStore?:string;initialOperation?:string;initialStage?:Stage}){
 const context=useWorkbenchContext();const userId=context.user?.id,organizationId=context.effectiveOrganization?.id;
 const scope=useMemo(()=>userId&&organizationId?{userId,organizationId}:null,[userId,organizationId]);
 if(context.isLoading||context.isSwitching)return <ConsoleState kind="loading" title="正在确认当前企业"/>;
 if(!scope||context.selectionRequired||context.error||context.blockingError)return <ConsoleState kind="error" title="请先确认登录身份与当前企业"/>;
 if(!context.permissions.includes("workbench.supply.read"))return <ConsoleState kind="unavailable" title="当前身份没有供应链查看权限"/>;
 return <ScopedSupplyPage key={`${userId}:${organizationId}:${initialStage??"all"}`} scope={scope} initialPreparation={initialPreparation} initialStore={initialStore} initialOperation={initialOperation} initialStage={initialStage}/>;
}
const stageKeys:Record<(typeof stages)[number],Stage>={全部:"all",待适配:"waiting",待补全:"missing",已适配:"ready",待审核:"review",已上传:"uploaded"};
type Row={fact?:SupplyStagePage["items"][number];detail:SupplySourceDetail;target?:SupplyTarget;publication?:SupplyPublication;appliedProposal?:ProductTitleProposal};
function ScopedSupplyPage({scope,initialPreparation,initialStore,initialOperation,initialStage}:{scope:SupplyScope;initialPreparation?:string;initialStore?:string;initialOperation?:string;initialStage?:Stage}){
 const router=useRouter();const context=useWorkbenchContext();const [preparationId,setPreparationId]=useState(initialPreparation??"");const [preparation,setPreparation]=useState<SupplyPreparation>();
 const [preparations,setPreparations]=useState<SupplyPreparation[]>([]),[prepNext,setPrepNext]=useState<string>(),[prepAfter,setPrepAfter]=useState<string>(),[prepLoadedKey,setPrepLoadedKey]=useState("");
 const [storeId,setStoreId]=useState(initialStore??""),[stores,setStores]=useState<WorkbenchStore[]>([]),[storePage,setStorePage]=useState(1),[storeTotal,setStoreTotal]=useState(0);
 const [rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[after,setAfter]=useState<string>(),[next,setNext]=useState<string>();
 const [tab,setTab]=useState<(typeof stages)[number]>(stages.find(s=>stageKeys[s]===initialStage)??"全部"),[reload,setReload]=useState(0),[loadedKey,setLoadedKey]=useState(""),[error,setError]=useState<string>(),[notice,setNotice]=useState("");
 const [resolveItem,setResolveItem]=useState<SupplyOperationItem>();
 const [operations,setOperations]=useState<SupplyOperation[]>([]),[historyNext,setHistoryNext]=useState<string>(),[historyAfter,setHistoryAfter]=useState<string>();
 const [operation,setOperation]=useState<SupplyOperation>(),[operationId,setOperationId]=useState(initialOperation??""),[operationItems,setOperationItems]=useState<SupplyOperationItem[]>([]),[itemAfter,setItemAfter]=useState<string>(),[itemNext,setItemNext]=useState<string>();
 const [stagePage,setStagePage]=useState<SupplyStagePage>(),[keyword,setKeyword]=useState(""),[search,setSearch]=useState(""),[sourceKind,setSourceKind]=useState<"own"|"acquisition"|"">("");
 const [selected,setSelected]=useState<Set<string>>(new Set()),[editor,setEditor]=useState<Row>(),[saved,setSaved]=useState(0),[confirm,setConfirm]=useState<{action:"adapt"|"upload"|"optimize";whole:boolean}>();
 const [configuration,setConfiguration]=useState(initialStage!=="missing"&&initialStage!=="review"&&initialStage!=="uploaded"),[rulesEnabled,setRulesEnabled]=useState(true),[ruleDetails,setRuleDetails]=useState(false);
 const [agentEnabled,setAgentEnabled]=useState(false),[agentOptions,setAgentOptions]=useState<SupplyOptimizationOptions>(),[titleChoice,setTitleChoice]=useState<SupplyOptimizationChoice>(),[agentAfter,setAgentAfter]=useState<string>();
 const validTitle=titleChoice&&agentOptions?.titles.some(t=>t.templateId===titleChoice.templateId&&t.revision===titleChoice.revision&&t.quoteHash===titleChoice.quoteHash)?titleChoice:undefined;
 useEffect(()=>{if(!agentEnabled)return;const c=new AbortController();let live=true;void readSupplyOptimizationOptions(scope,{after:agentAfter,limit:100},c.signal).then(value=>{if(live)setAgentOptions(value)}).catch(e=>{if(live)setError(codeOf(e))});return()=>{live=false;c.abort()};},[scope,agentEnabled,agentAfter,reload]);
 const rowsKey=JSON.stringify([preparationId,storeId,after,reload,tab,keyword,sourceKind]);
 const loading=!!preparationId&&loadedKey!==rowsKey;
 const [controlBusy,setControlBusy]=useState(false);
 const [review,setReview]=useState<SupplyOperationItem>();const [bulkReview,setBulkReview]=useState<SupplyOperationItem[]>();
 const controlRequest=useRef<AbortController|null>(null);
 useEffect(()=>()=>{controlRequest.current?.abort()},[]);
 const supply=useSupplyCommand(scope,(result,intent)=>{
  if(intent.route==="resolve-upload"){const v=uploadResolutionSchema.parse(result);setNotice(v.message??"已核实原上传");setResolveItem(undefined);setSaved(n=>n+1);setReload(n=>n+1);return;}
  setNotice("原操作结果已保存");setSaved(n=>n+1);
  if(intent.route==="create-operation"){const receipt=operationReceiptSchema.safeParse(result);const op=receipt.success?receipt.data.operation:operationSchema.parse(result);setOperationId(op.id);setOperation(op);setItemAfter(undefined)}
  if(intent.route==="save-target"){setEditor(undefined);setReload(n=>n+1)}
  setConfirm(undefined);
 });
 const canManage=context.permissions.includes("workbench.supply.manage"),canSubmit=context.permissions.includes("workbench.listing.submit"),canReadStores=context.permissions.includes("workbench.store.read");
 const blocked=!canManage||supply.busy||!!supply.pending||!supply.ready||!!context.pendingCollectionIntent||controlBusy;
 useEffect(()=>context.registerOrganizationSwitchGuard(()=>!controlBusy),[context,controlBusy]);
 useEffect(()=>{const c=new AbortController();let live=true;
  const request=preparationId?readSupplyPreparation(scope,preparationId,c.signal):listSupplyPreparations(scope,{after:prepAfter,limit:50},c.signal);
  void request.then(value=>{if(!live)return;if("items" in value){setPreparations(value.items);setPrepNext(value.nextCursor)}else setPreparation(value);setError(undefined)}).catch(e=>{if(live)setError(codeOf(e))}).finally(()=>{if(live)setPrepLoadedKey(JSON.stringify([preparationId,prepAfter,reload]))});
  return()=>{live=false;c.abort()};
 },[scope,preparationId,prepAfter,reload]);
 useEffect(()=>{if(!canReadStores)return;const c=new AbortController();let live=true;
  void listWorkbenchStores({page:storePage,pageSize:100,platform:"shein",status:"active"},scope.organizationId,c.signal).then(value=>{if(live){setStores(value.items);setStoreTotal(value.pagination.total)}}).catch(e=>{if(live)setError(codeOf(e))});
  return()=>{live=false;c.abort()};
 },[scope,canReadStores,storePage]);
 useEffect(()=>{if(!preparationId)return;const c=new AbortController();let live=true;
  void (storeId?listSupplyStages(scope,preparationId,storeId,stageKeys[tab],{after,keyword:keyword||undefined,sourceKind:sourceKind||undefined,limit:20},c.signal):listSupplySources(scope,preparationId,{after,keyword:keyword||undefined,limit:20},c.signal)).then(async page=>{
   const facts="batchTotal" in page?page:undefined;
   const values=await Promise.all(page.items.map(async source=>{
    const id="sourceId" in source?source.sourceId:source.id;
    const detail=await readSupplySource(scope,id,c.signal);let target:SupplyTarget|undefined;
    if(storeId)try{target=await readSupplyTarget(scope,id,storeId,c.signal)}catch(e){if(!(e instanceof SupplyAPIError&&e.code==="NOT_FOUND"))throw e}
    const publication=storeId?await readSupplyPublication(scope,id,storeId,c.signal):undefined;
    return {detail,target,publication,fact:facts?.items.find(f=>f.sourceId===id)};
   }));if(live){setRows(values);setStagePage(facts);setTotal(page.total);setNext(page.nextCursor);setError(undefined)}
  }).catch(e=>{if(live){setError(codeOf(e));setRows([])}}).finally(()=>{if(live)setLoadedKey(JSON.stringify([preparationId,storeId,after,reload,tab,keyword,sourceKind]))});return()=>{live=false;c.abort()};
 },[scope,preparationId,storeId,after,reload,tab,keyword,sourceKind]);
 useEffect(()=>{if(!preparationId||!storeId)return;const c=new AbortController();let live=true;
  void listSupplyOperations(scope,preparationId,storeId,{after:historyAfter,limit:20},c.signal).then(page=>{if(live){setOperations(page.items);setHistoryNext(page.nextCursor)}}).catch(e=>{if(live)setError(codeOf(e))});return()=>{live=false;c.abort()};
 },[scope,preparationId,storeId,historyAfter,reload,saved]);
 useEffect(()=>{if(!operationId)return;const c=new AbortController();let live=true;
  void Promise.all([readSupplyOperation(scope,operationId,c.signal),listSupplyOperationItems(scope,operationId,{after:itemAfter,limit:100},c.signal)]).then(([op,page])=>{if(live){if(op.input.preparationId!==preparationId||op.input.storeId!==storeId){setError("REVISION_CONFLICT");return}setOperation(op);setOperationItems(page.items);setItemNext(page.nextCursor)}}).catch(e=>{if(live)setError(codeOf(e))});return()=>{live=false;c.abort()};
 },[scope,operationId,preparationId,storeId,itemAfter,reload,saved]);
 function saveSelection(batch:string,store:string){const url=new URL(window.location.href);for(const [key,value] of [["preparation",batch],["store",store]]){if(value)url.searchParams.set(key,value);else url.searchParams.delete(key)}url.searchParams.delete("operation");window.history.replaceState(null,"",url);}
 function choosePreparation(id:string){saveSelection(id,storeId);setPreparationId(id);setPreparation(undefined);setAfter(undefined);setSelected(new Set());setOperations([]);setOperationId("");setOperation(undefined);setHistoryAfter(undefined);setKeyword("");setSearch("");setSourceKind("");setStagePage(undefined);setEditor(undefined);setReview(undefined);setResolveItem(undefined)}
 function chooseStore(id:string){saveSelection(preparationId,id);setStoreId(id);setSelected(new Set());setOperations([]);setAfter(undefined);setOperationId("");setOperation(undefined);setHistoryAfter(undefined);setKeyword("");setSearch("");setSourceKind("");setStagePage(undefined);setEditor(undefined);setReview(undefined);setResolveItem(undefined)}
 function execute(){if(!confirm||!preparation||!storeId||blocked||confirm.action==="upload"&&!canSubmit)return;
  if(confirm.action==="optimize"&&!validTitle)return;
  supply.execute("create-operation",{preparationId:preparation.id,expectedRevision:preparation.revision,storeId,action:confirm.action,...confirm.action==="optimize"&&validTitle?{titleTemplateId:validTitle.templateId,titleTemplateRevision:validTitle.revision,titleQuoteHash:validTitle.quoteHash}:{},...confirm.whole?{}:{sourceIds:Array.from(selected)}});
 }
 async function control(action:"ensure"|"cancel"){if(!operation||blocked)return;setControlBusy(true);const c=new AbortController();controlRequest.current=c;try{const value=await controlSupplyOperation(scope,operation.id,action,c.signal);if(!c.signal.aborted){setOperation(value);setReload(n=>n+1)}}catch(e){if(!c.signal.aborted)setError(codeOf(e))}finally{if(!c.signal.aborted)setControlBusy(false)}}
 const visible=storeId?rows:rows.filter(r=>tab==="全部"||stage(r)===tab);
 return <ConsolePage className="space-y-5" title={tab==="全部"?"我的供应链":tab} description={tab==="待适配"?"把我的数据里的商品资料，按目标平台的上架要求整理。选好批次、规则和平台后即可开始。":tab==="已适配"?"选择批次，可选启用智能体优化，再确认目标店铺上传。":tab==="待补全"?"按当前店铺的官方要求补齐商品资料，保存后再次校验。":tab==="待审核"?"查看智能体建议，接受、编辑或拒绝后，单独确认应用。":tab==="已上传"?"查看原上传结果和平台商品编号。":"选择商品批次，生成平台资料，补全后上传。"} breadcrumbs={[{label:"供应市场"},{label:"我的供应链"}]} actions={<><Link href="/workbench/data/mine" prefetch={false} className="text-sm text-emerald-700">从我的数据添加商品</Link><Button variant="outline" disabled={supply.busy||controlBusy} onClick={()=>setReload(n=>n+1)}>刷新</Button></>}>
  <SupplyCommandFeedback state={supply}/>{error?<Card role="alert" className="p-4 text-sm text-red-700">{errorMessage(error)}</Card>:null}{notice?<p role="status" className="text-sm text-emerald-700">{notice}</p>:null}
  {!preparationId?<><Card className="space-y-4 p-5"><h2 className="font-semibold">选择商品批次</h2>{prepLoadedKey!==JSON.stringify([preparationId,prepAfter,reload])?<p>正在读取批次</p>:preparations.length?preparations.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><div><h3 className="font-medium">{p.name}</h3><p className="text-xs text-slate-500">{p.count} 件 · {new Date(p.createdAt).toLocaleString("zh-CN")}</p></div><Button onClick={()=>choosePreparation(p.id)}>选择批次</Button></div>):<p className="text-sm text-slate-500">还没有商品批次，请先从“我的数据”加入。</p>}<Pager next={prepNext} after={prepAfter} onNext={()=>{setPrepAfter(prepNext)}} onFirst={()=>{setPrepAfter(undefined)}}/></Card></>:<>
   <div className="flex flex-wrap justify-between gap-3"><div className="flex gap-2"><Button size="sm" variant={configuration?"default":"outline"} onClick={()=>setConfiguration(true)}>{tab==="待适配"?"适配配置":"发布配置"}</Button><Button size="sm" variant={!configuration?"default":"outline"} onClick={()=>setConfiguration(false)}>商品列表</Button></div></div>
   {!configuration?<Card className="flex flex-wrap items-end gap-4 p-4"><div className="mr-auto"><p className="text-sm font-medium">{preparation?.name??"正在读取批次"}</p><p className="mt-1 text-xs text-slate-500">完整批次 {preparation?.count??0} 件</p><Button variant="ghost" size="sm" onClick={()=>choosePreparation("")}>更换批次</Button></div><label className="grid min-w-48 gap-2 text-sm">目标店铺<Select value={storeId} disabled={!canReadStores||supply.busy||controlBusy} onChange={e=>chooseStore(e.target.value)}><option value="">选择店铺</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></label></Card>:null}
   {configuration?<>
   <Card className="space-y-4 border-border bg-muted/50 p-5"><h2 className="text-sm font-semibold">{tab==="待适配"?"商品上架整理流程":"发布配置流程"}</h2><ol className="grid gap-3 sm:grid-cols-3">{["选择批次",tab==="待适配"?"选择适配规则":"智能体设置","选择目标平台"].map((label,i)=><li key={label} className="flex items-center gap-3 rounded-lg border border-border bg-card p-3"><span className="flex size-7 items-center justify-center rounded-full bg-emerald-100 text-sm font-semibold text-emerald-700">{i+1}</span><span className="text-sm">{label}</span><span className="ml-auto text-xs text-slate-500">{i===0&&preparation?"已完成":i===2&&!storeId?"待进行":i===2&&storeId?"已选择":"当前步骤"}</span></li>)}</ol></Card>
   <div className="grid gap-4 lg:grid-cols-3"><Card className="space-y-3 p-5"><h2 className="font-semibold">1. 选择商品批次</h2><p className="text-sm">{preparation?.name??"正在读取批次"}</p><p className="text-xs text-slate-500">{preparation?`${preparation.count} 件商品 · 原始资料保留`:""}</p><Button variant="outline" onClick={()=>choosePreparation("")}>更换批次</Button></Card>
    <Card className="space-y-3 p-5"><h2 className="font-semibold">2. {tab==="待适配"?"选择并启用适配规则":"启用智能体（可选）"}</h2><p className="text-sm">标准适配规则 · 当前店铺官方要求</p><p className="text-xs text-slate-500">保存资料时校验类目、属性、价格、库存和图片。</p>{tab==="待适配"?<label className="flex items-center justify-between gap-2 rounded-lg bg-muted px-3 py-2 text-sm">启用本次规则<input type="checkbox" role="switch" aria-label="启用本次规则" checked={rulesEnabled} disabled={blocked} onChange={e=>setRulesEnabled(e.target.checked)}/></label>:null}<Button variant="outline" size="sm" onClick={()=>setRuleDetails(true)}>适配规则设置</Button><label className="flex items-center gap-2 text-sm"><input type="checkbox" aria-label="开启智能体优化" checked={agentEnabled} disabled={blocked} onChange={e=>{setAgentEnabled(e.target.checked);setTitleChoice(undefined)}}/>可选智能体优化</label>{agentEnabled?<div className="space-y-3"><label className="grid gap-2 text-sm">标题优化模板<Select value={validTitle?`${validTitle.templateId}:${validTitle.revision}`:""} onChange={e=>setTitleChoice(agentOptions?.titles.find(t=>`${t.templateId}:${t.revision}`===e.target.value))}><option value="">选择已启用模板</option>{agentOptions?.titles.map(t=><option key={`${t.templateId}:${t.revision}`} value={`${t.templateId}:${t.revision}`}>{t.name} · v{t.revision}</option>)}</Select></label>{!agentOptions?<p className="text-xs text-slate-500">正在读取可用智能体与预算</p>:null}{agentOptions?.reason?<p className="text-xs text-amber-700">{agentOptions.reason}</p>:null}{validTitle?<p className="text-xs text-slate-500">每件预算上限 {validTitle.maximumPoints} 积分 · 价格版本 {validTitle.priceVersion}</p>:null}{agentOptions?.imageReason?<p className="text-xs text-slate-500">图片优化：{agentOptions.imageReason}</p>:null}<Pager next={agentOptions?.nextCursor} after={agentAfter} onNext={()=>{setAgentAfter(agentOptions?.nextCursor);setTitleChoice(undefined)}} onFirst={()=>{setAgentAfter(undefined);setTitleChoice(undefined)}}/></div>:null}</Card>
    <Card className="space-y-3 p-5"><h2 className="font-semibold">3. 选择目标平台</h2><div className="flex gap-2 text-sm"><span className="rounded-lg bg-muted px-3 py-2">SHEIN</span><span className="rounded-lg bg-muted px-3 py-2">美国站</span></div><label className="grid gap-2 text-sm">目标店铺<Select value={storeId} disabled={!canReadStores||supply.busy||controlBusy} onChange={e=>chooseStore(e.target.value)}><option value="">选择店铺</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name} · {s.connectionStatus==="connected"&&s.serviceStatus==="active"?"已连接":"需完善连接或服务"}</option>)}</Select></label>{!canReadStores?<p className="text-xs text-amber-700">需要店铺查看权限。</p>:null}{storeTotal>100?<Pager next={storePage*100<storeTotal?"next":undefined} after={storePage>1?"previous":undefined} onNext={()=>setStorePage(p=>p+1)} onFirst={()=>setStorePage(1)}/>:null}<p className="text-xs text-slate-500">全托管市场由 SHEIN 分配；编辑时显示实际应用类型。</p></Card></div>
   <Card className="flex flex-wrap items-center justify-between gap-4 p-5"><div><h2 className="font-semibold">{tab==="待适配"?"本次适配":"本次发布"}</h2><p className="mt-2 text-sm text-slate-500">{preparation?.name} · {preparation?.count??0} 件 · {stores.find(s=>s.id===storeId)?.name??"请选择目标店铺"}</p></div><div className="flex flex-wrap gap-2">{tab==="待适配"?<Button disabled={blocked||!rulesEnabled||!storeId||!preparation||loading} onClick={()=>setConfirm({action:"adapt",whole:true})}>开始适配</Button>:tab==="已适配"?<Button disabled={blocked||!canSubmit&&!agentEnabled||!storeId||!preparation||loading||agentEnabled&&!validTitle} onClick={()=>setConfirm({action:agentEnabled?"optimize":"upload",whole:true})}>{agentEnabled?"开始优化并审核":"开始上传"}</Button>:<Button disabled={blocked||!storeId||!preparation||loading} onClick={()=>setConfirm({action:"adapt",whole:true})}>适配整批</Button>}{agentEnabled&&tab!=="已适配"?<Button disabled={blocked||!storeId||!preparation||loading||!validTitle} onClick={()=>setConfirm({action:"optimize",whole:true})}>重构整批</Button>:null}{tab!=="待适配"&&tab!=="已适配"?<Button variant="outline" disabled={blocked||!canSubmit||!storeId||!preparation||loading} onClick={()=>setConfirm({action:"upload",whole:true})}>上传整批</Button>:null}</div></Card>
   </>:null}
   <Card className="overflow-hidden"><div role="tablist" aria-label="商品阶段" className="flex flex-wrap gap-2 border-b border-slate-100 p-4">{stages.map(s=><Button key={s} role="tab" aria-selected={tab===s} variant={tab===s?"default":"ghost"} disabled={!storeId&&s!=="全部"&&s!=="待适配"} onClick={()=>{if(initialStage){router.push(`/workbench/supply/mine${s==="全部"?"":`/${stageKeys[s]}`}?${new URLSearchParams({preparation:preparationId,...storeId?{store:storeId}:{}})}`);return;}setTab(s);setAfter(undefined);setSelected(new Set())}}>{s}{stagePage&&!loading?` (${stagePage.counts[stageKeys[s]]})`:""}</Button>)}</div><div className="flex flex-wrap items-center justify-between gap-3 p-4"><p className="text-xs text-slate-500">完整批次 {stagePage?.batchTotal??preparation?.count??total} 件，筛选结果 {total} 件。</p><form className="flex gap-2" onSubmit={e=>{e.preventDefault();setKeyword(search.trim());setAfter(undefined);setSelected(new Set())}}><Input aria-label="搜索供应链商品" disabled={!storeId} placeholder={storeId?"商品名称 / SKU / 批次":"请先选择目标店铺"} value={search} onChange={e=>setSearch(e.target.value)}/><label className="sr-only" htmlFor="supply-source-kind">商品来源</label><Select id="supply-source-kind" value={sourceKind} disabled={!storeId||loading} onChange={e=>{setSourceKind(e.target.value as "own"|"acquisition"|"");setAfter(undefined);setSelected(new Set())}}><option value="">来源：全部</option><option value="own">自有商品</option><option value="acquisition">采集商品</option></Select><Button type="button" variant="ghost" onClick={()=>{setKeyword("");setSearch("");setSourceKind("");setAfter(undefined);setSelected(new Set())}}>重置</Button><Button type="submit" variant="outline">搜索</Button></form><div className="flex flex-wrap gap-2">{tab==="待审核"?<Button disabled={blocked||!context.permissions.includes("listingkit.admin.write")||!selected.size||visible.filter(r=>selected.has(r.detail.source.id)).some(r=>!r.fact?.review)} onClick={()=>setBulkReview(visible.filter(r=>selected.has(r.detail.source.id)).map(r=>r.fact!.review!))}>批量审核通过</Button>:null}<Button variant="outline" disabled={blocked||tab==="待适配"&&!rulesEnabled||!storeId||!selected.size} onClick={()=>setConfirm({action:"adapt",whole:false})}>适配所选 {selected.size||""}</Button><Button variant="outline" title={!validTitle?"请先在发布配置选择标题优化模板":undefined} disabled={blocked||!validTitle||!storeId||!selected.size} onClick={()=>setConfirm({action:"optimize",whole:false})}>{tab==="待审核"?"批量重新重构":"重构所选"}</Button><Button variant="outline" disabled={blocked||!canSubmit||!storeId||!selected.size} onClick={()=>setConfirm({action:"upload",whole:false})}>上传所选</Button></div></div>
    {loading?<p className="p-6 text-sm">正在读取商品资料</p>:<Table><TableHeader><TableRow><TableHead>选择</TableHead><TableHead>商品</TableHead><TableHead>来源 / 批次</TableHead><TableHead>目标</TableHead><TableHead>智能体</TableHead><TableHead>资料状态</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{visible.map(r=><TableRow key={r.detail.source.id}><TableCell><input type="checkbox" aria-label={`选择 ${r.detail.product.title??r.detail.source.id}`} checked={selected.has(r.detail.source.id)} onChange={e=>setSelected(prior=>{const copy=new Set(prior);if(e.target.checked)copy.add(r.detail.source.id);else copy.delete(r.detail.source.id);return copy})}/></TableCell><TableCell><div className="flex items-center gap-3">{r.detail.images[0]?.url?<Image src={r.detail.images[0].url} alt="" width={48} height={48} unoptimized className="size-12 rounded-md object-cover"/>:<span aria-hidden="true" className="flex size-12 shrink-0 items-center justify-center rounded-md bg-muted text-xs text-muted-foreground">商品</span>}<div><p className="font-medium">{r.detail.product.title||"未命名商品"}</p><p className="mt-1 text-xs text-muted-foreground">{r.detail.product.variants?.[0]?.sku??r.detail.source.source.productKey}</p></div></div></TableCell><TableCell><p>{r.detail.source.source.kind==="own"?"自有商品":"采集商品"}</p><p className="mt-1 text-xs text-muted-foreground">{preparation?.name} · 来源版本 {r.detail.source.source.version}</p></TableCell><TableCell><p>SHEIN / 美国站</p><p className="mt-1 text-xs text-muted-foreground">{stores.find(s=>s.id===storeId)?.name??"未选择店铺"}</p></TableCell><TableCell>{r.fact?.review?"标题优化 · 人工审核":r.target?.applyReceiptId?"标题优化 · 已应用":"未启用"}</TableCell><TableCell>{r.fact?stages.find(s=>stageKeys[s]===r.fact!.stage):stage(r)}{r.publication?.product?<p className="mt-1 break-all text-xs text-emerald-700">SPU：{r.publication.product.spu_name}{r.target&&r.publication.recordId!==r.target.id?" · 原资料版本已上传":""}</p>:null}{r.publication?.product?<details className="mt-1 text-xs"><summary className="cursor-pointer">平台 SKC / SKU 编号</summary>{r.publication.product.skc_list.map(skc=><div className="my-2" key={skc.skc_name}><p>SKC：{skc.skc_name}</p>{skc.sku_list.map(sku=><p key={sku.sku_code}>{sku.supplier_sku} → {sku.sku_code}</p>)}</div>)}</details>:null}{r.target?<p className="text-xs text-slate-500">目标版本 {r.target.revision} · {r.target.result.issues.length} 项待处理</p>:null}</TableCell><TableCell><Button variant="outline" disabled={!storeId||supply.busy} onClick={()=>setEditor(r)}>查看 / 补全</Button>{r.fact?.review?<Button size="sm" variant="outline" disabled={blocked} onClick={()=>setReview(r.fact!.review)}>查看重构结果</Button>:null}</TableCell></TableRow>)}</TableBody></Table>}
    {!loading&&!visible.length?<p className="p-6 text-sm text-slate-500">完整批次中没有符合此阶段及搜索条件的商品。</p>:null}<div className="p-4"><Pager next={next} after={after} onNext={()=>{setAfter(next);setSelected(new Set())}} onFirst={()=>{setAfter(undefined);setSelected(new Set())}}/></div></Card>
   <Card className="space-y-3 p-5"><h2 className="font-semibold">操作进度</h2>{operations.length?<label className="grid gap-2 text-sm">历史操作<Select value={operationId} onChange={e=>{setOperationId(e.target.value);setItemAfter(undefined)}}><option value="">选择操作</option>{operations.map(o=><option key={o.id} value={o.id}>{operationLabels[o.input.action]} · {new Date(o.createdAt).toLocaleString("zh-CN")} · {operationLabels[o.status]} {o.completed}/{o.count}</option>)}</Select></label>:<p className="text-sm text-slate-500">选择目标店铺后，可查看保存的操作历史。</p>}<Pager next={historyNext} after={historyAfter} onNext={()=>setHistoryAfter(historyNext)} onFirst={()=>setHistoryAfter(undefined)}/>
    {operation?<><p className="text-sm">{operationLabels[operation.input.action]} · {operationLabels[operation.status]} · {operation.completed}/{operation.count}</p><p className="break-all text-xs text-slate-500">操作编号：{operation.id}</p>{operation.status!=="completed"&&operation.status!=="cancelled"?<div className="flex gap-2"><Button variant="outline" disabled={blocked} onClick={()=>void control("ensure")}>确认原执行已启动</Button><Button variant="outline" disabled={blocked} onClick={()=>void control("cancel")}>取消未开始商品</Button></div>:null}<Table><TableHeader><TableRow><TableHead>商品编号</TableHead><TableHead>结果</TableHead><TableHead>说明</TableHead></TableRow></TableHeader><TableBody>{operationItems.map(i=><TableRow key={i.sourceId}><TableCell className="max-w-48 break-all text-xs">{i.sourceId}</TableCell><TableCell>{i.confirmedProduct?"原执行 UNKNOWN，已核实成功":itemLabels[i.status]}</TableCell><TableCell>{i.note}{i.confirmedProduct?<p className="mt-1 break-all text-xs text-emerald-700">SPU：{i.confirmedProduct.spu_name}</p>:null}{operation?.input.action==="upload"&&i.status==="unknown"&&!i.confirmedProduct&&i.recordId&&i.resultReference?<Button variant="outline" size="sm" disabled={blocked||!canSubmit} onClick={()=>setResolveItem(i)}>查看待核实结果</Button>:null}{i.status==="review"&&i.recordId&&i.resultReference?<Button variant="outline" size="sm" disabled={blocked} onClick={()=>setReview(i)}>查看 / 审核</Button>:null}</TableCell></TableRow>)}</TableBody></Table><Pager next={itemNext} after={itemAfter} onNext={()=>setItemAfter(itemNext)} onFirst={()=>setItemAfter(undefined)}/></>:null}
   </Card>
  </>}
  {ruleDetails?<CollectionDialog title="适配规则设置" onClose={()=>setRuleDetails(false)}><p className="text-sm">标准规则读取当前店铺对应应用的官方要求，包括类目、属性、品牌、售价或供货价、库存及图片。选择具体商品后，可在“查看 / 补全”中读取该类目的详细字段。</p><p className="text-sm text-slate-500">规则只生成目标平台资料，保留原始商品信息。SHEIN 全托管、半托管、自运营的字段分别按实际应用类型校验。</p><Button variant="outline" onClick={()=>{setRuleDetails(false);setConfiguration(false)}}>查看商品资料</Button></CollectionDialog>:null}
  {confirm&&preparation?<CollectionDialog title={confirm.action==="adapt"?"确认适配":confirm.action==="optimize"?"确认智能体优化":"确认上传"} onClose={()=>{if(!supply.busy)setConfirm(undefined)}}><p className="text-sm">{confirm.whole?`完整批次 ${preparation.count} 件商品`:`所选 ${selected.size} 件商品`} → {stores.find(s=>s.id===storeId)?.name}</p><p className="text-sm text-slate-500">{confirm.action==="adapt"?"逐件生成平台资料，缺失信息进入待补全。":confirm.action==="optimize"?"按所选模板生成标题建议，进入人工审核并显式应用。":"向平台实际提交已满足条件的商品；不确定结果会保留供核实。"}</p>{confirm.action==="optimize"&&validTitle?<p className="rounded-lg bg-blue-50 p-3 text-sm">本次预算上限 {String(BigInt(validTitle.maximumPoints)*BigInt(confirm.whole?preparation.count:selected.size))} 积分 · {validTitle.name} v{validTitle.revision} · 价格版本 {validTitle.priceVersion}。实际用量沿现有账户计量。</p>:null}<Button disabled={blocked||confirm.action==="optimize"&&!validTitle} onClick={execute}>{confirm.action==="adapt"?"确认适配":confirm.action==="optimize"?"确认智能体优化":"确认上传"}</Button></CollectionDialog>:null}
  {bulkReview?<CollectionDialog title="批量审核通过" onClose={()=>{if(!supply.busy&&!supply.pending){setBulkReview(undefined);setReload(n=>n+1)}}}><BulkSupplyReviewPanel scope={scope} storeId={storeId} items={bulkReview} command={supply} permissions={context.permissions}/></CollectionDialog>:null}
  {review?<CollectionDialog title="审核智能体建议" onClose={()=>{if(!supply.busy)setReview(undefined)}}><SupplyReviewPanel scope={scope} storeId={storeId} item={review} command={supply} saved={saved} permissions={context.permissions} roles={context.roles} onApplied={(p,r)=>{void Promise.all([readSupplySource(scope,r.source.id),readSupplyTarget(scope,r.source.id,storeId)]).then(([detail,target])=>{if(target.id!==r.id){setError("REVISION_CONFLICT");return}setReview(undefined);setEditor({detail,target,appliedProposal:p})}).catch(e=>setError(codeOf(e)))}}/></CollectionDialog>:null}
  {resolveItem?<CollectionDialog title="核实原上传结果" onClose={()=>{if(!supply.busy)setResolveItem(undefined)}}><UploadResolutionPanel scope={scope} item={resolveItem} command={supply} disabled={blocked||!canSubmit}/></CollectionDialog>:null}
  {editor?<CollectionDialog title="商品资料与平台适配" onClose={()=>{if(!supply.busy)setEditor(undefined)}}><SupplyTargetEditor key={`${editor.detail.source.id}:${storeId}`} scope={scope} source={editor.detail} storeId={storeId} existing={editor.target} appliedProposal={editor.appliedProposal} command={supply} disabled={blocked} saved={saved}/></CollectionDialog>:null}
 </ConsolePage>;
}
function stage(row:Row){return row.publication?.product&&row.publication.recordId===row.target?.id?"已上传":!row.target?"待适配":row.target.result.ready_for_upload?"已适配":"待补全"}
function Pager({next,after,onNext,onFirst}:{next?:string;after?:string;onNext:()=>void;onFirst:()=>void}){return <div className="flex gap-2">{after?<Button size="sm" variant="ghost" onClick={onFirst}>回到首页</Button>:null}{next?<Button size="sm" variant="outline" onClick={onNext}>下一页</Button>:null}</div>}
function codeOf(e:unknown){return e instanceof SupplyAPIError?e.code:"DEPENDENCY_UNAVAILABLE"}
function errorMessage(code:string){return ({NOT_FOUND:"未找到当前身份下的记录。",PERMISSION_DENIED:"当前权限不足。",REVISION_CONFLICT:"资料或店铺上下文已变化，请刷新核对。",NOT_READY:"当前资料尚未满足条件。",OUTCOME_UNKNOWN:"原操作结果待核实，请保留原操作编号。",DEPENDENCY_UNAVAILABLE:"暂时无法读取资料，请刷新重试。"} as Record<string,string>)[code]??code}
