"use client";
import { useEffect,useRef,useState,type ReactNode } from "react";
import Image from "next/image";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { supplyRules,supplyInventory,SupplyAPIError,type SupplyScope } from "@/lib/api/supply-chain";
import { sourceSelectionSchema,targetInputSchema,inventorySchema,type SupplySourceDetail,type SupplyTarget,type SupplyRules,type OfficialProduct } from "@/lib/contracts/supply-chain";
import { initialSupplyDraft,applyApplicationMode,categoryLeaves,emptySKC,emptySKU,sampleForSKU,type SupplyDraft,type AttributeValue,type SKU } from "./draft-fields";
import type { SupplyCommandState } from "./use-supply-command";
import type {ProductTitleProposal} from "@/lib/api/product-title-review";
import {reviewedSupplyDraft} from "./title-review-binding";
import {ProductImageSetPanel} from "../acquisition/product-image-set-panel";
type Inventory=z.infer<typeof inventorySchema>;
type RuleAttribute=SupplyRules["rules"]["attributes"]["attribute_infos"][number];
const modeLabel={self_operated:"自营",semi_managed:"半托管",fully_managed:"全托管"};
const roleLabel={main:"主图",white_background:"白底图",gallery:"展示图",design:"设计图"};
type Role=keyof typeof roleLabel;
export function SupplyTargetEditor({scope,source,storeId,existing,appliedProposal,command,disabled,saved}:{scope:SupplyScope;source:SupplySourceDetail;storeId:string;existing?:SupplyTarget;appliedProposal?:ProductTitleProposal;command:SupplyCommandState;disabled:boolean;saved:number}){
 const [draft,setDraft]=useState<SupplyDraft>(()=>existing&&appliedProposal?reviewedSupplyDraft(existing,appliedProposal):structuredClone(existing?.input.draft??initialSupplyDraft(source)));
 const [rules,setRules]=useState<SupplyRules>();const [inventory,setInventory]=useState<Inventory>();
 const [selectedImages,setSelectedImages]=useState<Record<string,Role>>({});const [error,setError]=useState<string>();const [resolvedRuleEpoch,setResolvedRuleEpoch]=useState(-1),[ruleEpoch,setRuleEpoch]=useState(0),[inventoryEpoch,setInventoryEpoch]=useState(0);
 const applied=appliedProposal?.proposal_id??existing?.applyReceiptId;const version=appliedProposal?.apply_receipt?.product_version??existing?.effectiveVersion??source.source.source.version;
 const mode=useRef(existing?.merchant.application_type);
 const currentInput=useRef(draft);
 useEffect(()=>{currentInput.current=draft},[draft]);
 const loading=resolvedRuleEpoch!==ruleEpoch;
 const selection={itemId:source.source.id,originalPublicationId:source.source.source.publicationId,originalSnapshotVersion:source.source.source.version,effectiveCatalogVersion:version,...(applied?{applyReceiptId:applied}:{}),targetPlatform:"shein" as const};
 function change(edit:(next:SupplyDraft)=>void){setDraft(value=>{const copy=structuredClone(value);edit(copy);return copy})}
 useEffect(()=>{let live=true;const c=new AbortController();
  const input={sourceId:source.source.id,storeId,expectedRevision:existing?.revision??0,effectiveVersion:version,...applied?{applyReceiptId:applied}:{},draft:currentInput.current};
  void supplyRules(scope,input,c.signal).then(value=>{if(live){setRules(value);if(mode.current!==value.merchant.application_type){setDraft(d=>applyApplicationMode(d,value.merchant.application_type));mode.current=value.merchant.application_type}setError(undefined)}}).catch(e=>{if(live)setError(e instanceof SupplyAPIError?e.code:"DEPENDENCY_UNAVAILABLE")}).finally(()=>{if(live)setResolvedRuleEpoch(ruleEpoch)});
  return()=>{live=false;c.abort()};
 },[scope,source,storeId,existing,version,applied,ruleEpoch]);
 useEffect(()=>{let live=true;const c=new AbortController();
  void supplyInventory(scope,selection,c.signal).then(value=>{if(live)setInventory(value)}).catch(e=>{if(live)setError(e instanceof SupplyAPIError?e.code:"DEPENDENCY_UNAVAILABLE")});return()=>{live=false;c.abort()};
 // Selection facts are immutable during this editor session; saved refreshes the exact inventory.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[scope,source,version,applied,saved,inventoryEpoch]);
 const product=draft.product;const attributes=rules?.rules.attributes.attribute_infos??[];
 const visibleAttributes=(dimension:number)=>attributes.filter(a=>(a.attribute_type===3||a.attribute_type===4)&&a.data_dimension===dimension);
 const sale=attributes.filter(a=>a.attribute_type===1),main=sale.filter(a=>a.attribute_label===1);
 const priceMode=rules?.merchant.application_type;const warehouses=rules?.rules.warehouses.filter(w=>w.warehouseType===1&&w.saleCountryList.includes("US"))??[];
 const fieldShown=(name:string)=>rules?.rules.fill.fill_in_standard_list.some(f=>f.field_key===name&&f.show);
 function save(){const parsed=targetInputSchema.safeParse({sourceId:source.source.id,storeId,expectedRevision:existing?.revision??0,effectiveVersion:version,...applied?{applyReceiptId:applied}:{},draft});if(!parsed.success){setError("请检查资料格式与数量");return}command.execute("save-target",parsed.data)}
 const selectionSafe=sourceSelectionSchema.safeParse(selection).success;
 return <div className="space-y-6">
  <ProductImageSetPanel kind="supply" contextId={source.source.id} effectiveVersion={version} applyReceiptId={applied} target={existing?{Platform:"shein",RecordID:existing.id,StoreID:storeId,Site:existing.merchant.site,CategoryID:existing.input.draft.product.category_id}:undefined} onSaved={()=>{setRuleEpoch(old=>old+1);setInventoryEpoch(old=>old+1)}}/>
  <details className="rounded-xl bg-slate-50 p-4"><summary className="cursor-pointer text-sm font-medium">查看原始资料 · 版本 {source.source.source.version}</summary><p className="mt-3 font-medium">{source.product.title}</p><p className="mt-2 whitespace-pre-wrap text-sm">{source.product.description}</p><dl className="mt-3 grid gap-2 sm:grid-cols-2">{source.product.attributes?.map((a,i)=><div key={i} className="text-sm"><dt className="text-slate-500">{a.name}</dt><dd>{a.value}</dd></div>)}</dl></details>
  <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-semibold">SHEIN · {priceMode?modeLabel[priceMode]:"正在读取应用类型"} · {priceMode==="fully_managed"?"平台分配市场":"美国站"}</p><Button variant="outline" size="sm" disabled={loading} onClick={()=>setRuleEpoch(n=>n+1)}>刷新店铺规则</Button></div>
  {error?<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}{loading?<p role="status" className="text-sm text-slate-500">正在读取店铺类目与规则</p>:null}
  <fieldset disabled={disabled} className="space-y-5 disabled:opacity-70">
   <div className="grid gap-4 sm:grid-cols-2"><Field label="平台类目"><Select value={product.category_id||""} onChange={e=>{const leaf=categoryLeaves(rules?.rules.categories??[]).find(c=>c.id===Number(e.target.value));if(!leaf)return;change(d=>{d.product.category_id=leaf.id;d.product.product_type_id=leaf.type;d.product.product_attribute_list=[];d.product.size_attribute_list=[];for(const skc of d.product.skc_list){skc.sale_attribute={attribute_id:0};for(const sku of skc.sku_list){sku.sale_attribute_list=[];sku.sku_scope_attribute_list=[]}}});setRuleEpoch(n=>n+1)}}><option value="">选择可发布的末级类目</option>{categoryLeaves(rules?.rules.categories??[]).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</Select></Field><Field label="品牌"><Select value={product.brand_code??""} onChange={e=>change(d=>{d.product.brand_code=e.target.value})}><option value="">选择当前店铺品牌</option>{rules?.rules.brands.map(b=><option key={b.brand_code} value={b.brand_code}>{b.brand_name}</option>)}</Select></Field></div>
   <LanguageFields label="商品标题" values={product.multi_language_name_list} onChange={v=>change(d=>{d.product.multi_language_name_list=v})}/>
   <LanguageFields label="商品描述" multiline values={product.multi_language_desc_list??[]} onChange={v=>change(d=>{d.product.multi_language_desc_list=v})}/>
   {rules?.rules.fill.supplier_code_in_spu_dimension?<Field label="SPU 货号"><Input value={product.supplier_code??""} onChange={e=>change(d=>{d.product.supplier_code=e.target.value})}/></Field>:null}
   {fieldShown("sample_spec")?<section className="space-y-3 rounded-xl bg-slate-50 p-4"><h3 className="text-sm font-semibold">样品资料</h3><p className="text-xs text-slate-500">选择真实 SKU 规格；样品类型为大货样衣，不留样。需要填写尺码表。</p><Field label="样品 SKU 规格"><Select value={product.sample_info?product.skc_list.flatMap((skc,i)=>skc.sku_list.map((_,j)=>({key:`${i}:${j}`,sample:sampleForSKU(draft,i,j)}))).find(v=>v.sample&&JSON.stringify(v.sample.sample_spec)===JSON.stringify(product.sample_info!.sample_spec))?.key??"":""} onChange={e=>change(d=>{if(!e.target.value){delete d.product.sample_info;return}const [i,j]=e.target.value.split(":").map(Number);const sample=sampleForSKU(d,i!,j!);if(sample)d.product.sample_info=sample})}><option value="">选择已填写销售属性的 SKU</option>{product.skc_list.flatMap((skc,i)=>skc.sku_list.map((sku,j)=>sampleForSKU(draft,i,j)?<option key={`${i}:${j}`} value={`${i}:${j}`}>SKC {i+1} / SKU {j+1} · {sku.supplier_sku||"未填写商家 SKU"}</option>:null))}</Select></Field>{product.sample_info?<Field label="样品是否现货"><Select value={product.sample_info.spot_flag||""} onChange={e=>change(d=>{d.product.sample_info!.spot_flag=Number(e.target.value)})}><option value="">选择</option><option value="1">现货</option><option value="2">非现货</option></Select></Field>:null}</section>:null}
   <AttributeFields title="商品属性" attributes={visibleAttributes(1)} values={product.product_attribute_list} onChange={v=>change(d=>{d.product.product_attribute_list=v})}/>
   {product.skc_list.map((skc,i)=><section key={i} className="space-y-4 rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">SKC {i+1}</h3>{product.skc_list.length>1?<Button size="sm" variant="ghost" onClick={()=>change(d=>{d.product.skc_list.splice(i,1);d.images=d.images.filter(s=>s.group==="spu"||s.skc!==i).map(s=>s.group!=="spu"&&s.skc>i?{...s,skc:s.skc-1}:s)})}>移除此 SKC</Button>:null}</div>
    {!rules?.rules.fill.supplier_code_in_spu_dimension?<Field label={`SKC ${i+1} 货号`}><Input value={skc.supplier_code??""} onChange={e=>change(d=>{d.product.skc_list[i]!.supplier_code=e.target.value})}/></Field>:null}
    <AttributeFields title="主销售属性" attributes={main} values={skc.sale_attribute.attribute_id?[skc.sale_attribute]:[]} single onChange={v=>change(d=>{d.product.skc_list[i]!.sale_attribute=v[0]??{attribute_id:0}})}/>
    {fieldShown("skc_title")?<LanguageFields label={`SKC ${i+1} 标题`} values={skc.skc_multi_language_name_list??[]} onChange={v=>change(d=>{d.product.skc_list[i]!.skc_multi_language_name_list=v})}/>:null}
    {(priceMode==="fully_managed"||fieldShown("shelf_require"))?<Field label="上架要求"><Select value={skc.shelf_require??""} onChange={e=>change(d=>{d.product.skc_list[i]!.shelf_require=e.target.value})}><option value="">选择</option><option value="0">无需到仓后上架</option><option value="1">到货 SHEIN 仓后上架</option></Select></Field>:null}
    {fieldShown("suggest_price")?<div className="grid gap-3 sm:grid-cols-2"><Field label="建议零售价"><Input type="number" min="0" step="0.01" value={skc.suggested_retail_price?.price??""} onChange={e=>change(d=>{const s=d.product.skc_list[i]!;if(e.target.value==="")delete s.suggested_retail_price;else s.suggested_retail_price={price:Number(e.target.value),currency:s.suggested_retail_price?.currency??""}})}/></Field><Field label="建议价币种"><Input value={skc.suggested_retail_price?.currency??""} onChange={e=>change(d=>{const s=d.product.skc_list[i]!;s.suggested_retail_price={price:s.suggested_retail_price?.price??0,currency:e.target.value}})}/></Field></div>:null}
    {priceMode==="semi_managed"||priceMode==="fully_managed"?<div className="grid gap-3 sm:grid-cols-2"><Field label="上架方式"><Select value={skc.shelf_way??""} onChange={e=>change(d=>{const s=d.product.skc_list[i]!;s.shelf_way=e.target.value;if(s.shelf_way!=="2")delete s.hope_on_sale_date})}><option value="">选择上架方式</option><option value="1">自动上架</option><option value="2">定时上架</option></Select></Field>{skc.shelf_way==="2"?<Field label="期望上架时间（北京时间）"><Input type="datetime-local" step="1" value={(skc.hope_on_sale_date??"").replace(" ","T")} onChange={e=>change(d=>{d.product.skc_list[i]!.hope_on_sale_date=e.target.value.replace("T"," ")+(e.target.value.length===16?":00":"")})}/></Field>:null}</div>:null}
    {fieldShown("proof_of_stock")?<section className="space-y-3 rounded-lg border border-slate-200 p-4"><h4 className="text-sm font-semibold">库存证明</h4><p className="text-xs text-slate-500">每个 SKC 最多一个 JPEG/PNG 或 PDF 文件，最大 3MiB。填写可公开读取的 HTTPS 链接，保存时验证实际文件。</p>{skc.proof_of_stock_list?.[0]?<div className="grid gap-3 sm:grid-cols-3"><Field label={`库存证明文件名 ${i+1}`}><Input value={skc.proof_of_stock_list[0].file_name} onChange={e=>change(d=>{d.product.skc_list[i]!.proof_of_stock_list![0]!.file_name=e.target.value})}/></Field><Field label={`库存证明类型 ${i+1}`}><Select value={skc.proof_of_stock_list[0].type} onChange={e=>change(d=>{d.product.skc_list[i]!.proof_of_stock_list![0]!.type=e.target.value as "1"|"2"})}><option value="1">JPEG / PNG 图片</option><option value="2">PDF 文件</option></Select></Field><Field label={`库存证明链接 ${i+1}`}><Input type="url" placeholder="https://" value={skc.proof_of_stock_list[0].url} onChange={e=>change(d=>{d.product.skc_list[i]!.proof_of_stock_list![0]!.url=e.target.value})}/></Field><Button variant="ghost" size="sm" onClick={()=>change(d=>{delete d.product.skc_list[i]!.proof_of_stock_list})}>移除库存证明</Button></div>:<Button variant="outline" size="sm" onClick={()=>change(d=>{d.product.skc_list[i]!.proof_of_stock_list=[{file_name:"",type:"1",url:""}]})}>添加库存证明</Button>}</section>:null}
    {skc.sku_list.map((sku,j)=><section key={j} className="space-y-3 rounded-lg bg-slate-50 p-4"><div className="flex items-center justify-between"><h4 className="text-sm font-semibold">SKU {j+1}</h4>{skc.sku_list.length>1?<Button size="sm" variant="ghost" onClick={()=>change(d=>{d.product.skc_list[i]!.sku_list.splice(j,1);d.images=d.images.filter(s=>!(s.group==="sku"&&s.skc===i&&s.sku===j)).map(s=>s.group==="sku"&&s.skc===i&&s.sku>j?{...s,sku:s.sku-1}:s)})}>移除此 SKU</Button>:null}</div>
     <SKUFields sku={sku} index={`${i+1}-${j+1}`} mode={priceMode} currency={rules?.rules.fill.currency??undefined} warehouses={warehouses} fullWarehouseCount={rules?.rules.warehouses.length??0} fieldShown={fieldShown} onChange={v=>change(d=>{d.product.skc_list[i]!.sku_list[j]=v})}/>
     <AttributeFields title="销售规格" attributes={sale.filter(a=>a.attribute_id!==skc.sale_attribute.attribute_id)} values={sku.sale_attribute_list} onChange={v=>change(d=>{d.product.skc_list[i]!.sku_list[j]!.sale_attribute_list=v})}/>
     <AttributeFields title="SKU 属性" attributes={visibleAttributes(3)} values={sku.sku_scope_attribute_list??[]} onChange={v=>change(d=>{d.product.skc_list[i]!.sku_list[j]!.sku_scope_attribute_list=v})}/>
    </section>)}<Button variant="outline" size="sm" disabled={skc.sku_list.length>=400} onClick={()=>change(d=>{d.product.skc_list[i]!.sku_list.push(emptySKU())})}>添加 SKU</Button>
   </section>)}<Button variant="outline" disabled={product.skc_list.length>=40} onClick={()=>change(d=>{d.product.skc_list.push(emptySKC())})}>添加 SKC</Button>
   <SizeFields attributes={attributes.filter(a=>a.attribute_type===2)} values={product.size_attribute_list??[]} onChange={v=>change(d=>{d.product.size_attribute_list=v})}/>
  </fieldset>
  <section className="space-y-4 rounded-xl border border-slate-200 p-4"><h3 className="font-semibold">本次使用的图片</h3><p className="text-xs text-slate-500">选择完整图片集合并确认用途，再将已批准图片放入目标商品位置。</p><div className="grid gap-3 sm:grid-cols-3">{source.images.map((image,i)=><div key={image.id} className="space-y-2 rounded-lg border border-slate-100 p-3"><Image unoptimized src={`/api/image-proxy?url=${encodeURIComponent(image.url)}`} width={120} height={120} alt={`来源图 ${i+1}`} className="h-28 w-full object-contain"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={disabled} checked={!!selectedImages[image.id]} onChange={e=>setSelectedImages(value=>{const next={...value};if(e.target.checked)next[image.id]="gallery";else delete next[image.id];return next})}/>使用来源图 {i+1}</label>{selectedImages[image.id]?<Select aria-label={`来源图 ${i+1} 用途`} disabled={disabled} value={selectedImages[image.id]} onChange={e=>setSelectedImages(value=>({...value,[image.id]:e.target.value as Role}))}>{Object.entries(roleLabel).map(([role,name])=><option key={role} value={role}>{name}</option>)}</Select>:null}</div>)}</div>
   <Button variant="outline" disabled={disabled||!selectionSafe||!Object.keys(selectedImages).length} onClick={()=>command.execute("approve",{selection,images:Object.entries(selectedImages).map(([id,role])=>({id,role})),approved:[]})}>确认完整图片选择</Button>
   <p className="text-xs text-slate-500">已批准 {inventory?.assets.length??0} 张图片</p>
   <fieldset disabled={disabled} className="space-y-3">{draft.images.map((slot,i)=><div className="grid gap-2 rounded-lg bg-slate-50 p-3 sm:grid-cols-3" key={i}><Field label={`图片 ${i+1}`}><Select value={slot.asset_id} onChange={e=>change(d=>{d.images[i]!.asset_id=e.target.value})}><option value="">选择已批准图片</option>{inventory?.assets.map((a,index)=><option key={a.id} value={a.id}>{index+1} · {roleLabel[a.role]}</option>)}</Select></Field><Field label="图片位置"><Select value={`${slot.group}:${slot.skc}:${slot.sku}`} onChange={e=>{const [group,skc,sku]=e.target.value.split(":");change(d=>{d.images[i]={...d.images[i]!,group:group as typeof slot.group,skc:Number(skc),sku:Number(sku)}})}}>{rules?.rules.fill.picture_config_list.some(p=>p.field_key==="spu_image_detail_show")?<option value="spu:0:0">SPU</option>:null}{product.skc_list.flatMap((skc,k)=>[<option key={`skc${k}`} value={`skc:${k}:0`}>SKC {k+1}</option>,<option key={`detail${k}`} value={`detail:${k}:0`}>SKC {k+1} 站点详情图</option>,...skc.sku_list.map((_,j)=><option key={`sku${k}:${j}`} value={`sku:${k}:${j}`}>SKC {k+1} / SKU {j+1}</option>)])}</Select></Field><Field label="图片类型"><Select value={slot.type} onChange={e=>change(d=>{d.images[i]!.type=Number(e.target.value)})}><option value="1">主图</option><option value="2">细节图</option><option value="5">方形图</option><option value="6">色块图</option><option value="7">站点详情图</option></Select></Field><Field label="排序"><Input type="number" min="1" max="100" value={slot.sort} onChange={e=>change(d=>{d.images[i]!.sort=Number(e.target.value)})}/></Field><Button size="sm" variant="ghost" onClick={()=>change(d=>{d.images.splice(i,1)})}>移除位置</Button></div>)}<Button variant="outline" size="sm" disabled={!inventory?.assets.length||draft.images.length>=10000} onClick={()=>change(d=>{d.images.push({asset_id:inventory!.assets[0]!.id,group:"skc",skc:0,sku:0,sort:1,type:1})})}>添加图片位置</Button></fieldset>
  </section>
  {existing?.result.issues.length?<section className="rounded-xl bg-amber-50 p-4"><h3 className="text-sm font-semibold">上次校验待补全项</h3><ul className="mt-3 space-y-2 text-sm">{existing.result.issues.map((issue,i)=><li key={i}>{issue.message}<span className="ml-2 break-all text-xs text-slate-500">{issue.field}</span></li>)}</ul></section>:null}
  <div className="flex justify-end gap-3"><Button disabled={disabled||loading||!rules||!inventory?.assets.length} onClick={save}>保存并校验平台资料</Button></div>
 </div>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid gap-2 text-sm">{label}{children}</label>}
function LanguageFields({label,values,multiline,onChange}:{label:string;values:{language:string;name:string}[];multiline?:boolean;onChange:(v:{language:string;name:string}[])=>void}){return <section className="space-y-3"><h3 className="text-sm font-semibold">{label}</h3>{values.map((value,i)=><div key={i} className="grid gap-2 sm:grid-cols-[120px_1fr_auto]"><Input aria-label={`${label}语种 ${i+1}`} value={value.language} onChange={e=>onChange(values.map((v,j)=>i===j?{...v,language:e.target.value}:v))}/>{multiline?<Textarea aria-label={`${label}内容 ${i+1}`} rows={3} value={value.name} onChange={e=>onChange(values.map((v,j)=>i===j?{...v,name:e.target.value}:v))}/>:<Input aria-label={`${label}内容 ${i+1}`} value={value.name} onChange={e=>onChange(values.map((v,j)=>i===j?{...v,name:e.target.value}:v))}/>}<Button variant="ghost" size="sm" onClick={()=>onChange(values.filter((_,j)=>i!==j))}>移除</Button></div>)}<Button variant="outline" size="sm" disabled={values.length>=32} onClick={()=>onChange([...values,{language:"",name:""}])}>添加{label}语种</Button></section>}
function AttributeFields({title,attributes,values,onChange,single=false}:{title:string;attributes:RuleAttribute[];values:AttributeValue[];onChange:(v:AttributeValue[])=>void;single?:boolean}){
 function update(id:number,selected:AttributeValue[]){onChange([...(single?[]:values.filter(v=>v.attribute_id!==id)),...selected])}
 return attributes.length?<section className="space-y-3"><h4 className="text-sm font-semibold">{title}</h4><div className="grid gap-3 sm:grid-cols-2">{attributes.filter(a=>a.attribute_is_show===1&&a.attribute_status!==1).map(a=>{const chosen=values.filter(v=>v.attribute_id===a.attribute_id),options=a.value_info_list.filter(v=>v.is_show===1);return <div key={a.attribute_id} className="space-y-2"><Field label={`${a.attribute_name}${a.attribute_status===3?" *":""}`}>{a.attribute_mode===0?<Input value={chosen[0]?.attribute_extra_value??""} inputMode="numeric" onChange={e=>update(a.attribute_id,e.target.value?[{attribute_id:a.attribute_id,attribute_extra_value:e.target.value}]:[])}/>:<Select multiple={a.attribute_mode===1||a.attribute_mode===4} value={a.attribute_mode===1||a.attribute_mode===4?chosen.map(v=>String(v.attribute_value_id)):String(chosen[0]?.attribute_value_id??"")} onChange={e=>update(a.attribute_id,Array.from(e.target.selectedOptions).filter(o=>o.value).map(o=>({attribute_id:a.attribute_id,attribute_value_id:Number(o.value),...a.attribute_mode===4?{attribute_extra_value:chosen.find(v=>v.attribute_value_id===Number(o.value))?.attribute_extra_value??""}:{}})))}><option value="">选择属性值</option>{options.map(o=><option key={o.attribute_value_id} value={o.attribute_value_id}>{o.attribute_value}</option>)}</Select>}</Field>{a.attribute_mode===4?chosen.map(v=><Field key={v.attribute_value_id} label={`${options.find(o=>o.attribute_value_id===v.attribute_value_id)?.attribute_value??"属性"} 输入值`}><Input value={v.attribute_extra_value??""} onChange={e=>update(a.attribute_id,chosen.map(c=>c===v?{...c,attribute_extra_value:e.target.value}:c))}/></Field>):null}</div>})}</div></section>:null;
}
function SKUFields({sku,index,mode,currency,warehouses,fullWarehouseCount,fieldShown,onChange}:{sku:SKU;index:string;mode?:SupplyRules["merchant"]["application_type"];currency?:string;warehouses:SupplyRules["rules"]["warehouses"];fullWarehouseCount:number;fieldShown:(name:string)=>boolean|undefined;onChange:(v:SKU)=>void}){
 function update(edit:(v:SKU)=>void){const next=structuredClone(sku);edit(next);onChange(next)}
 return <><div className="grid gap-3 sm:grid-cols-2"><Field label={`商家 SKU ${index}`}><Input value={sku.supplier_sku} onChange={e=>update(v=>{v.supplier_sku=e.target.value})}/></Field><Field label="销售状态"><Select value={sku.mall_state||""} onChange={e=>update(v=>{v.mall_state=Number(e.target.value)})}><option value="">选择</option><option value="1">在售</option><option value="2">停售</option></Select></Field>{mode==="self_operated"?<Field label="美国站售价 USD"><Input type="number" min="0.01" step="0.01" value={sku.price_info_list?.[0]?.base_price??""} onChange={e=>update(v=>{v.price_info_list=e.target.value?[{base_price:Number(e.target.value),currency:"USD",sub_site:"shein-us"}]:[]})}/></Field>:mode?<Field label={`供货价 ${currency??"币种不可用"}`}><Input disabled={!currency} inputMode="decimal" value={sku.cost_info?.cost_price??""} onChange={e=>update(v=>{if(e.target.value==="")delete v.cost_info;else v.cost_info={cost_price:e.target.value,currency:currency!}})}/></Field>:null}{mode==="fully_managed"?<Field label="采购状态"><Select value={sku.stop_purchase??""} onChange={e=>update(v=>{if(!e.target.value)delete v.stop_purchase;else v.stop_purchase=Number(e.target.value)})}><option value="">选择</option><option value="1">可采</option><option value="2">停采</option></Select></Field>:null}</div>
  <div className="grid gap-3 sm:grid-cols-4">{(["length","width","height"] as const).map((name,i)=><Field key={name} label={`${["含包装长","含包装宽","含包装高"][i]} cm`}><Input inputMode="decimal" value={sku[name]??""} onChange={e=>update(v=>{v[name]=e.target.value})}/></Field>)}<Field label="含包装重量 g"><Input type="number" min="0.01" step="0.01" value={sku.weight??""} onChange={e=>update(v=>{if(e.target.value==="")delete v.weight;else v.weight=Number(e.target.value)})}/></Field></div>
  <section className="space-y-2"><h5 className="text-sm font-medium">真实库存</h5>{sku.stock_info_list.map((stock,i)=><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]" key={i}>{mode!=="fully_managed"&&fullWarehouseCount>0?<Field label="库存仓库"><Select value={stock.supplier_warehouse_id??""} onChange={e=>update(v=>{const warehouse=warehouses.find(w=>w.warehouseCode===e.target.value);v.stock_info_list[i]={inventory_num:stock.inventory_num,...warehouse?{supplier_warehouse_id:warehouse.warehouseCode,supplier_warehouse_name:warehouse.warehouseName}:{}}})}><option value="">选择可维护的美国商家仓</option>{warehouses.map(w=><option key={w.warehouseCode} value={w.warehouseCode}>{w.warehouseName}</option>)}</Select></Field>:null}<Field label="库存数量"><Input type="number" min="0" max="99999" step="1" value={Number.isFinite(stock.inventory_num)?stock.inventory_num:""} onChange={e=>update(v=>{v.stock_info_list[i]!.inventory_num=e.target.value===""?Number.NaN:Number(e.target.value)})}/></Field><Button variant="ghost" size="sm" onClick={()=>update(v=>{v.stock_info_list.splice(i,1)})}>移除库存</Button></div>)}<Button variant="outline" size="sm" disabled={sku.stock_info_list.length>=(mode==="fully_managed"?1:20)} onClick={()=>update(v=>{v.stock_info_list.push({inventory_num:Number.NaN})})}>添加库存记录</Button></section>
  {fieldShown("quantity_info")?<div className="grid gap-3 sm:grid-cols-3"><Field label="件数类型"><Select value={sku.quantity_info?.quantity_type??""} onChange={e=>update(v=>{if(!e.target.value)delete v.quantity_info;else v.quantity_info={quantity_type:Number(e.target.value),quantity_unit:v.quantity_info?.quantity_unit??0,quantity:v.quantity_info?.quantity??0}})}><option value="">不填写</option><option value="1">单件</option><option value="2">同品多件</option><option value="3">混合套装</option></Select></Field>{sku.quantity_info?<><Field label="件数单位"><Select value={sku.quantity_info.quantity_unit||""} onChange={e=>update(v=>{v.quantity_info!.quantity_unit=Number(e.target.value)})}><option value="">选择</option><option value="1">件</option><option value="2">双</option><option value="3">套</option></Select></Field><Field label="件数"><Input type="number" value={sku.quantity_info.quantity} onChange={e=>update(v=>{v.quantity_info!.quantity=Number(e.target.value)})}/></Field></>:null}</div>:null}
  {fieldShown("package_type")?<Field label="包装类型"><Select value={sku.package_type??""} onChange={e=>update(v=>{if(e.target.value)v.package_type=e.target.value;else delete v.package_type})}><option value="">不填写</option><option value="0">清空包装</option><option value="1">软包装 + 软物</option><option value="2">软包装 + 硬物</option><option value="3">硬包装</option><option value="4">真空包装</option></Select></Field>:null}
  {fieldShown("minimum_stock_quantity")?<Field label="最小备货数量"><Input inputMode="numeric" value={sku.minimum_stock_quantity??""} onChange={e=>update(v=>{v.minimum_stock_quantity=e.target.value})}/></Field>:null}
  {fieldShown("reference_product_link")?<Field label="商品参考链接"><Input type="url" value={sku.competing_product_link??""} onChange={e=>update(v=>{v.competing_product_link=e.target.value})}/></Field>:null}
 </>;
}
function SizeFields({attributes,values,onChange}:{attributes:RuleAttribute[];values:NonNullable<OfficialProduct["size_attribute_list"]>;onChange:(v:NonNullable<OfficialProduct["size_attribute_list"]>)=>void}){return attributes.length?<section className="space-y-3"><h3 className="text-sm font-semibold">尺码表</h3>{values.map((v,i)=><div className="grid gap-2 rounded-xl bg-slate-50 p-3 sm:grid-cols-2" key={i}><Field label="尺码属性"><Select value={v.attribute_id||""} onChange={e=>onChange(values.map((a,j)=>i===j?{...a,attribute_id:Number(e.target.value)}:a))}><option value="">选择尺码属性</option>{attributes.map(a=><option key={a.attribute_id} value={a.attribute_id}>{a.attribute_name}{a.attribute_status===3?" *":""}</option>)}</Select></Field><Field label="尺码数值"><Input value={v.attribute_extra_value} onChange={e=>onChange(values.map((a,j)=>i===j?{...a,attribute_extra_value:e.target.value}:a))}/></Field><Field label="关联销售属性 ID（可选）"><Input type="number" value={v.relate_sale_attribute_id??""} onChange={e=>onChange(values.map((a,j)=>i===j?{...a,relate_sale_attribute_id:e.target.value?Number(e.target.value):undefined}:a))}/></Field><Field label="关联销售属性值 ID（可选）"><Input type="number" value={v.relate_sale_attribute_value_id??""} onChange={e=>onChange(values.map((a,j)=>i===j?{...a,relate_sale_attribute_value_id:e.target.value?Number(e.target.value):undefined}:a))}/></Field><Button variant="ghost" size="sm" onClick={()=>onChange(values.filter((_,j)=>i!==j))}>移除尺码</Button></div>)}<Button variant="outline" size="sm" onClick={()=>onChange([...values,{attribute_id:0,attribute_extra_value:""}])}>添加尺码行</Button></section>:null}
