package imageagent

import "context"

// ExecutionIdentity is the tenant/user identity verified at the command edge
// and durably captured in workflow input.
type ExecutionIdentity struct {
	TenantID       string
	UserID         string
	BusinessTaskID string
	TraceID        string
}

type SlotExecutor interface {
	ExecuteSlot(context.Context, SlotExecutionInput) (SlotExecutionResult, error)
}

// StagedSlotExecutor is the v3 boundary between transient provider generation
// and durable candidate construction. GenerateSlot may return transient
// provider material, while BuildSlotResult accepts only final, durable object
// references supplied by the artifact store.
//
// SlotExecutor remains the frozen v2 one-shot contract. Callers must select a
// wire version explicitly; this interface does not make v2 use v3 persistence.
type StagedSlotExecutor interface {
	GenerateSlot(context.Context, SlotExecutionInput) (SlotGeneratedOutput, error)
	BuildSlotResult(context.Context, SlotExecutionInput, PublishedSlotOutput) (SlotExecutionResult, error)
}

// BudgetedStagedSlotExecutor is additive so frozen v2 and legacy uncapped v3
// executors keep their historical wire behavior.
type BudgetedStagedSlotExecutor interface {
	StagedSlotExecutor
	QuoteSlot(context.Context, SlotExecutionInput, BudgetPolicy) (SlotUsageQuote, error)
	GenerateQuotedSlot(context.Context, SlotExecutionInput, SlotUsageQuote) (SlotGeneratedOutput, error)
}

type ApprovedAssetPublisher interface {
	PublishApproved(context.Context, PublishApprovedInput) (PublicationAcknowledgement, error)
}

// ApprovedAssetPublisherV3 is deliberately separate from the frozen v2
// publication port so Temporal can select its wire contract explicitly.
type ApprovedAssetPublisherV3 interface {
	PublishApprovedV3(context.Context, PublishApprovedV3Input) (PublicationAcknowledgement, error)
}

// DurableAssetPublicURLResolver turns a durable public object key into the
// readable URL stored in ListingKit. Storage adapters own the endpoint and
// public-base rules; the domain only defines this narrow boundary.
type DurableAssetPublicURLResolver interface {
	PublicURL(string) string
}

type PublicationAcknowledgement struct {
	TaskID            string
	RunID             string
	PlanRevision      int64
	ResultDigest      string
	IdempotencyKey    string
	CandidateAssetIDs []string
}

type SlotExecutionInput struct {
	RunID          string
	TenantID       string
	UserID         string
	PlanRevision   int64
	Slot           Slot
	Attempt        int
	IdempotencyKey string
	AssetCatalog   AssetCatalog
	ProductContext ProductContextRef
}

type SlotExecutionResult struct {
	SlotID     string
	Attempt    int
	Candidates []AssetCandidate
}

// PublishedSlotOutput is the v3 adapter input after the artifact store has
// finalized generated bytes. PublishedAssetRef is the complete durable
// allowlist; it excludes local paths, transient URLs, bytes, credentials, and
// arbitrary provider metadata.
type PublishedSlotOutput struct {
	SlotID  string
	Attempt int
	Assets  []PublishedAssetRef
}

type PublishApprovedInput struct {
	RunID             string
	TenantID          string
	UserID            string
	PlanRevision      int64
	CandidateAssetIDs []string
	IdempotencyKey    string
}

// PublishApprovedV3Input is the additive durable-approval payload. Keep the
// v2 input above unchanged for frozen Temporal histories.
type PublishApprovedV3Input struct {
	RunID             string
	TenantID          string
	UserID            string
	PlanRevision      int64
	CandidateAssetIDs []string
	IdempotencyKey    string
}

type StartRunInput struct {
	RunID              string
	BusinessTaskID     string
	Mode               RunMode
	IdempotencyKey     string
	Plan               Plan
	Budget             Budget
	MaxConcurrentSlots int
}

type WorkflowStart struct {
	Run                Run
	Plan               Plan
	Identity           ExecutionIdentity
	MaxConcurrentSlots int
	AssetCatalog       AssetCatalog
}

// RunProjection is the complete application snapshot exposed to transports.
// It deliberately contains only image-agent application contracts.
type RunProjection struct {
	Run                Run
	Plan               Plan
	Slots              []SlotProjection
	RecoverableEffects []RecoverableEffect
	ResultDigest       string
	Actions            []Action
	LastEventID        int64
	ProjectionVersion  int64
	AssetCatalog       AssetCatalog
	PendingCommand     *PendingCommandReceipt
	CommandIngress     CommandIngress
}

type SlotProjection struct {
	Slot       Slot
	Attempt    int
	Candidates []AssetCandidate
	ErrorCode  string
}

// WorkflowProjection is the workflow-owned portion of the application
// snapshot. Temporal adapters map query results into this contract.
type WorkflowProjection struct {
	Status             RunStatus
	Block              *Block
	Plan               Plan
	Slots              []SlotProjection
	RecoverableEffects []RecoverableEffect
	CompletedSlotIDs   []string
	ResultDigest       string
	PendingCommand     *PendingCommandReceipt
	CommandIngress     CommandIngress
}

type AssetCatalogScope struct {
	TenantID       string
	OwnerUserID    string
	BusinessTaskID string
	RunID          string
	// StyleReferenceIDs are the caller-selected, task-owned style assets that
	// may be promoted into the run-scoped authorization snapshot.
	StyleReferenceIDs []string
}

type AuthorizedAssetCatalog interface {
	Resolve(context.Context, AssetCatalogScope) (AssetCatalog, error)
}

type ReplacePlanCommand struct {
	RunID            string
	ExpectedRevision int64
	Plan             Plan
	ActorID          string
	ActionID         string
	Identity         ExecutionIdentity
}

type RetrySlotCommand struct {
	RunID        string
	PlanRevision int64
	SlotID       string
	ActorID      string
	ActionID     string
	Identity     ExecutionIdentity
}

type ApproveResultsCommand struct {
	RunID        string
	PlanRevision int64
	ResultDigest string
	ActorID      string
	ActionID     string
	Identity     ExecutionIdentity
}

type CancelRunCommand struct {
	RunID        string
	PlanRevision int64
	ActorID      string
	ActionID     string
	Identity     ExecutionIdentity
}

type RecoverEffectCommand struct {
	RunID        string
	PlanRevision int64
	SlotID       string
	Attempt      int
	ActionID     string
	Identity     ExecutionIdentity
	Projection   RunProjection
}

type ResumeCommand struct {
	RunID    string
	ActorID  string
	ActionID string
	Identity ExecutionIdentity
}

type CommandAcknowledgement struct {
	RunID        string
	PlanRevision int64
	ActionID     string
	Status       RunStatus
}

type WorkflowClient interface {
	StartManual(context.Context, WorkflowStart) error
	GetProjection(context.Context, RunScope, ExecutionIdentity) (WorkflowProjection, error)
	ReplacePlan(context.Context, ReplacePlanCommand) error
	RecoverEffect(context.Context, RecoverEffectCommand) error
	RetrySlot(context.Context, RetrySlotCommand) error
	ApproveResults(context.Context, ApproveResultsCommand) error
	Cancel(context.Context, CancelRunCommand) error
	Resume(context.Context, ResumeCommand) (CommandAcknowledgement, error)
}
