package imageagent

import (
	"errors"
	"fmt"
)

var ErrReviewDecision = errors.New("image review decision requires intervention")

// SlotReviewRequiredError carries generated bytes across the quality gate so
// the durable V3 activity can stage them without classifying the provider
// effect as unknown.
type SlotReviewRequiredError struct {
	Output SlotGeneratedOutput
	Reason string
	Cause  error
}

func (e *SlotReviewRequiredError) Error() string {
	if e == nil || e.Reason == "" {
		return "image review requires human intervention"
	}
	return fmt.Sprintf("image review requires human intervention: %s", e.Reason)
}

func (e *SlotReviewRequiredError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.Cause
}

func ReviewRequiredOutput(err error) (SlotGeneratedOutput, bool) {
	reviewErr, ok := err.(*SlotReviewRequiredError)
	if !ok || reviewErr == nil {
		return SlotGeneratedOutput{}, false
	}
	return reviewErr.Output, true
}
