package temporal

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"image"
	"image/png"
	"io"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
	"github.com/stretchr/testify/require"
	sdkactivity "go.temporal.io/sdk/activity"
	sdktemporal "go.temporal.io/sdk/temporal"
	"go.temporal.io/sdk/testsuite"
	"go.temporal.io/sdk/workflow"

	"task-processor/internal/imageagent"
	"task-processor/internal/imageagent/objectstore"
	"task-processor/internal/imageagent/store"
	storageinfra "task-processor/internal/infra/storage"
	"task-processor/internal/productimage"
)

func TestExecuteSlotV3RestoresProductImageBusinessIdentity(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-product-image-identity")
	input.Identity.BusinessTaskID = "task-product-image"
	input.Identity.TraceID = "trace-product-image"
	executor := &recordingStagedExecutor{generated: generatedV3Output(input, writeTinyPNG(t))}
	activities := newV3Activities(t, repository, repository.(imageagent.SlotExternalEffectV3Repository), executor, &recordingArtifactStore{})

	_, err := activities.ExecuteSlotV3(context.Background(), input)

	require.NoError(t, err)
	require.Equal(t, productimage.AIIdentity{
		TenantID: "tenant-a", UserID: "user-a", BusinessTaskID: "task-product-image", TraceID: "trace-product-image",
	}, executor.ProductImageIdentity())
}

func TestExecuteSlotV3CleansGeneratedLocalFileOnlyAfterDurableStaging(t *testing.T) {
	t.Run("durably staged", func(t *testing.T) {
		repository, input := initializedSlotEffectV3Activity(t, "run-v3-cleanup-staged")
		path := writeTinyPNG(t)
		executor := &recordingStagedExecutor{generated: generatedV3Output(input, path)}
		activities := newV3Activities(t, repository, repository.(imageagent.SlotExternalEffectV3Repository), executor, &recordingArtifactStore{})

		_, err := activities.ExecuteSlotV3(context.Background(), input)

		require.NoError(t, err)
		require.NoFileExists(t, path)
	})

	t.Run("staging failed after recovery preservation", func(t *testing.T) {
		repository, input := initializedSlotEffectV3Activity(t, "run-v3-cleanup-not-staged")
		path := writeTinyPNG(t)
		executor := &recordingStagedExecutor{generated: generatedV3Output(input, path)}
		artifacts := &recordingArtifactStore{ensureErrors: []error{errors.New("staging unavailable")}}
		activities := newV3Activities(t, repository, repository.(imageagent.SlotExternalEffectV3Repository), executor, artifacts)

		_, err := activities.ExecuteSlotV3(context.Background(), input)

		require.Error(t, err)
		require.NoFileExists(t, path, "the durable recovery bundle replaces the local copy")
	})

	t.Run("recovery preservation retries exhausted", func(t *testing.T) {
		repository, input := initializedSlotEffectV3Activity(t, "run-v3-cleanup-preserve-failed")
		path := writeTinyPNG(t)
		executor := &recordingStagedExecutor{generated: generatedV3Output(input, path)}
		artifacts := &recordingArtifactStore{preserveError: errors.New("recovery storage unavailable")}
		activities := newV3Activities(t, repository, repository.(imageagent.SlotExternalEffectV3Repository), executor, artifacts)

		_, err := activities.ExecuteSlotV3(context.Background(), input)

		requireV3ApplicationErrorType(t, err, slotProviderOutcomeUnknownCode)
		require.NoFileExists(t, path, "a fail-closed outcome cannot recover from worker-local bytes")
	})

	t.Run("retries transient recovery preservation while generated bytes are still local", func(t *testing.T) {
		repository, input := initializedSlotEffectV3Activity(t, "run-v3-cleanup-preserve-retry")
		path := writeTinyPNG(t)
		executor := &recordingStagedExecutor{generated: generatedV3Output(input, path)}
		artifacts := &recordingArtifactStore{preserveErrors: []error{errors.New("temporary recovery storage outage")}}
		activities := newV3Activities(t, repository, repository.(imageagent.SlotExternalEffectV3Repository), executor, artifacts)

		_, err := activities.ExecuteSlotV3(context.Background(), input)

		require.NoError(t, err)
		require.Equal(t, 2, artifacts.PreserveCalls())
		require.NoFileExists(t, path)
	})
}

func TestExecuteSlotV3DoesNotRegenerateAnUnownedProviderClaim(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-unowned-provider")
	effects := repository.(imageagent.SlotExternalEffectV3Repository)
	_, claimed, err := effects.ReserveSlotProviderV3(context.Background(), v3Reservation(input))
	require.NoError(t, err)
	require.True(t, claimed)
	executor := &recordingStagedExecutor{}
	activities := newV3Activities(t, repository, effects, executor, &recordingArtifactStore{})

	_, err = activities.ExecuteSlotV3(context.Background(), input)
	requireV3ApplicationErrorType(t, err, slotProviderOutcomeUnknownCode)
	require.Zero(t, executor.GenerateCalls())

	stored, err := effects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, err)
	require.Equal(t, imageagent.SlotEffectV3ProviderUnknown, stored.Phase)
	require.Equal(t, slotProviderOutcomeUnknownCode, stored.BlockedCode)
}

func TestExecuteSlotV3RetriesOnlyProvenUndispatchedProviderFailure(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-provider-not-dispatched")
	path := writeTinyPNG(t)
	executor := &recordingStagedExecutor{
		generated:   generatedV3Output(input, path),
		generateErr: &imageagent.ProviderDispatchError{State: imageagent.ProviderNotDispatched, Err: errors.New("request was never sent")},
	}
	activities := newV3Activities(t, repository, repository.(imageagent.SlotExternalEffectV3Repository), executor, &recordingArtifactStore{})

	_, err := activities.ExecuteSlotV3(context.Background(), input)

	var applicationError *sdktemporal.ApplicationError
	require.ErrorAs(t, err, &applicationError)
	require.Equal(t, imageagent.SlotProviderNotDispatchedCode, applicationError.Type())
	require.False(t, applicationError.NonRetryable())
	effect, getErr := repository.(imageagent.SlotExternalEffectV3Repository).GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, getErr)
	require.Equal(t, imageagent.SlotEffectV3ProviderNotDispatched, effect.Phase)

	executor.mu.Lock()
	executor.generateErr = nil
	executor.mu.Unlock()
	result, err := activities.ExecuteSlotV3(context.Background(), input)
	require.NoError(t, err)
	require.Len(t, result.Candidates, 1)
	require.Equal(t, 2, executor.GenerateCalls())
}

func TestExecuteSlotV3PersistsDispatchedOutcomeAfterCallerCancellation(t *testing.T) {
	repository, input, policy := initializedBudgetedV3Activity(t, "run-v3-provider-cancelled-after-dispatch", 16)
	input.BudgetAuthorization, input.BudgetPolicy = true, policy
	baseProvider := &recordingStagedExecutor{
		started:             make(chan struct{}),
		waitForCancellation: true,
		generateErr: &imageagent.ProviderDispatchError{
			State: imageagent.ProviderDispatchedUnknown,
			Err:   errors.New("provider request may have been dispatched"),
		},
	}
	provider := &budgetedRecordingExecutor{recordingStagedExecutor: baseProvider, quote: budgetActivityQuote("quote-cancelled-after-dispatch")}
	effects := &cancellationRejectingV3Repository{SlotExternalEffectV3Repository: repository.(imageagent.SlotExternalEffectV3Repository)}
	activities, newErr := NewActivities(ActivityDependencies{
		Repository: repository, SlotEffects: repository.(imageagent.SlotExternalEffectRepository), SlotExecutor: provider,
		SlotEffectsV3: effects, StagedSlotExecutor: provider, ArtifactStore: &recordingArtifactStore{},
		Publisher: &identityCheckingPublisher{t: t}, PublisherV3: &identityCheckingPublisher{t: t}, PublicationOwner: func(context.Context) (string, error) { return "workflow-run/activity/1", nil },
	})
	require.NoError(t, newErr)

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	go func() {
		<-baseProvider.started
		cancel()
	}()

	_, err := activities.ExecuteSlotV3(ctx, input)

	require.Error(t, err)
	require.True(t, effects.RecordedUnknown())
	require.False(t, effects.WriteSawCancelledContext())
}

func TestExecuteSlotV3CancellationTerminalizesSuccessfulProviderEffect(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-provider-success-cancelled")
	input.ExternalEffectFinalization = true
	path := writeTinyPNG(t)
	var cancel context.CancelFunc
	executor := &recordingStagedExecutor{
		generated: generatedV3Output(input, path),
		onGenerate: func() {
			cancel()
		},
	}
	effects := &cancellationObservingV3Repository{SlotExternalEffectV3Repository: repository.(imageagent.SlotExternalEffectV3Repository)}
	artifacts := &cancellationObservingArtifactStore{
		recordingArtifactStore: &recordingArtifactStore{ensureErrors: []error{objectstore.ErrObjectConflict}},
	}
	activities := newV3Activities(t, repository, effects, executor, artifacts)
	ctx, cancelCtx := context.WithCancel(context.Background())
	cancel = cancelCtx
	defer cancel()

	_, err := activities.ExecuteSlotV3(ctx, input)

	requireV3ApplicationErrorType(t, err, slotStagingOutcomeUnknownCode)
	require.False(t, artifacts.PreserveSawCancelledContext(), "recovery preservation must use the detached finalization context")
	require.False(t, artifacts.EnsureSawCancelledContext(), "staging must use the detached finalization context")
	require.False(t, effects.PrepareSawCancelledContext(), "staging transition must use the detached finalization context")
	require.False(t, effects.BlockSawCancelledContext(), "staging fallback must use the detached finalization context")

	stored, getErr := effects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, getErr)
	require.Equal(t, imageagent.SlotEffectV3StagingUnknown, stored.Phase)
	require.NotEqual(t, imageagent.SlotEffectV3ProviderClaimed, stored.Phase)
}

func TestExecuteSlotV3CancellationAfterProviderSuccessDetachesRecoveryPreservation(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-provider-success-cancelled-without-wire")
	path := writeTinyPNG(t)
	var cancel context.CancelFunc
	executor := &recordingStagedExecutor{
		generated:  generatedV3Output(input, path),
		onGenerate: func() { cancel() },
	}
	effects := &cancellationObservingV3Repository{SlotExternalEffectV3Repository: repository.(imageagent.SlotExternalEffectV3Repository)}
	artifacts := &cancellationObservingArtifactStore{
		recordingArtifactStore: &recordingArtifactStore{ensureErrors: []error{objectstore.ErrObjectConflict}},
	}
	activities := newV3Activities(t, repository, effects, executor, artifacts)
	ctx, cancelCtx := context.WithCancel(context.Background())
	cancel = cancelCtx
	defer cancel()

	_, err := activities.ExecuteSlotV3(ctx, input)

	requireV3ApplicationErrorType(t, err, slotStagingOutcomeUnknownCode)
	require.False(t, artifacts.PreserveSawCancelledContext())
	require.False(t, artifacts.EnsureSawCancelledContext())
	require.False(t, effects.PrepareSawCancelledContext())
	require.False(t, effects.BlockSawCancelledContext())
	stored, getErr := effects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, getErr)
	require.Equal(t, imageagent.SlotEffectV3StagingUnknown, stored.Phase)
}

func TestExecuteSlotV3StartsOneFinalizationWindowAfterProviderReturns(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-lazy-finalization-window")
	input.ExternalEffectFinalization = true
	path := writeTinyPNG(t)
	var providerReturnedAt time.Time
	executor := &recordingStagedExecutor{
		generated: generatedV3Output(input, path),
		onGenerate: func() {
			time.Sleep(250 * time.Millisecond)
			providerReturnedAt = time.Now()
		},
	}
	effects := &finalizationDeadlineObservingV3Repository{SlotExternalEffectV3Repository: repository.(imageagent.SlotExternalEffectV3Repository)}
	activities := newV3Activities(t, repository, effects, executor, &recordingArtifactStore{})

	result, err := activities.ExecuteSlotV3(context.Background(), input)

	require.NoError(t, err)
	require.Len(t, result.Candidates, 1)
	prepareDeadline, claimDeadline, completionDeadline := effects.FinalizationDeadlines()
	require.False(t, providerReturnedAt.IsZero())
	require.False(t, prepareDeadline.IsZero(), "staging must receive the bounded finalization context")
	require.False(t, claimDeadline.IsZero(), "publication claim must remain inside the same bounded context")
	require.False(t, completionDeadline.IsZero(), "publication completion must remain inside the same bounded context")
	require.GreaterOrEqual(t, prepareDeadline.Sub(providerReturnedAt), providerFinalizationTimeout-100*time.Millisecond,
		"provider execution must not consume the post-outcome finalization grace")
	require.True(t, prepareDeadline.Equal(claimDeadline), "publication must not create a second independent grace window")
	require.True(t, prepareDeadline.Equal(completionDeadline), "completion must use the original post-provider grace window")
}

func TestExecuteSlotV3CancellationPreservesLegacySuccessfulProviderBehaviorWithoutPatch(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-provider-success-legacy-cancelled")
	path := writeTinyPNG(t)
	var cancel context.CancelFunc
	executor := &recordingStagedExecutor{
		generated: generatedV3Output(input, path),
		onGenerate: func() {
			cancel()
		},
	}
	effects := &cancellationObservingV3Repository{SlotExternalEffectV3Repository: repository.(imageagent.SlotExternalEffectV3Repository)}
	artifacts := &cancellationObservingArtifactStore{
		recordingArtifactStore: &recordingArtifactStore{ensureErrors: []error{objectstore.ErrObjectConflict}},
	}
	activities := newV3Activities(t, repository, effects, executor, artifacts)
	ctx, cancelCtx := context.WithCancel(context.Background())
	cancel = cancelCtx
	defer cancel()

	_, err := activities.ExecuteSlotV3(ctx, input)

	require.ErrorContains(t, err, "ensure staged artifacts: context canceled")
	require.True(t, artifacts.PreserveSawCancelledContext(), "legacy path still uses the caller context during recovery preservation")
	require.True(t, artifacts.EnsureSawCancelledContext(), "legacy path still uses the caller context during staging")
	require.True(t, effects.PrepareSawCancelledContext(), "legacy path still uses the caller context during staging transition")
	require.False(t, effects.BlockSawCancelledContext(), "legacy path should not reach detached staging fallback")

	stored, getErr := effects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, getErr)
	require.Equal(t, imageagent.SlotEffectV3StagingPrepared, stored.Phase)
}

func TestExecuteSlotV3ResumesPersistedStagingWithoutRegeneration(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-resume-staging")
	effects := repository.(imageagent.SlotExternalEffectV3Repository)
	manifest := v3StagingManifest(input, tinyPNGBytes(t))
	seedV3StagingPrepared(t, effects, input, manifest)
	executor := &recordingStagedExecutor{}
	artifacts := &recordingArtifactStore{}
	activities := newV3Activities(t, repository, effects, executor, artifacts)

	result, err := activities.ExecuteSlotV3(context.Background(), input)
	require.NoError(t, err)
	require.Zero(t, executor.GenerateCalls())
	require.Zero(t, artifacts.PrepareCalls())
	require.Equal(t, 1, artifacts.EnsureCalls())
	require.Equal(t, manifest, artifacts.EnsuredManifest())
	require.Len(t, result.Candidates, 1)

	stored, err := effects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, err)
	require.Equal(t, imageagent.SlotEffectV3PublicationComplete, stored.Phase)
}

func TestEffectRecoveryWorkflowReconcilesClaimWithoutProviderCall(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-recovery-publication")
	effects := repository.(imageagent.SlotExternalEffectV3Repository)
	manifest := v3StagingManifest(input, tinyPNGBytes(t))
	seedV3ArtifactStaged(t, effects, input, manifest)
	executor := &recordingStagedExecutor{}
	artifacts := &recordingArtifactStore{}
	activities := newV3Activities(t, repository, effects, executor, artifacts)
	env := newEffectRecoveryWorkflowEnvWithoutParentProjection(t, activities)

	env.ExecuteWorkflow(ImageAgentEffectRecoveryWorkflow, effectRecoveryWorkflowInput(input))

	require.True(t, env.IsWorkflowCompleted())
	require.NoError(t, env.GetWorkflowError())
	var result EffectRecoveryResult
	require.NoError(t, env.GetWorkflowResult(&result))
	require.Equal(t, EffectRecoveryOutcomePublished, result.Outcome)
	require.Equal(t, imageagent.SlotEffectV3PublicationComplete, result.EffectPhase)
	require.Len(t, result.Published.Candidates, 1)
	require.Zero(t, executor.GenerateCalls(), "recovery must not regenerate the provider effect")
	require.Equal(t, 1, executor.BuildCalls(), "recovery should rebuild only the durable result")
	require.Equal(t, 1, artifacts.FinalizeCalls(), "recovery should finalize the durable staged artifacts")

	stored, err := effects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, err)
	require.Equal(t, imageagent.SlotEffectV3PublicationComplete, stored.Phase)
}

func TestExecuteSlotV3CancellationTerminalizesResumedStagingPreparedEffect(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-resume-staging-cancelled")
	input.ExternalEffectFinalization = true
	baseEffects := repository.(imageagent.SlotExternalEffectV3Repository)
	manifest := v3StagingManifest(input, tinyPNGBytes(t))
	seedV3StagingPrepared(t, baseEffects, input, manifest)
	effects := &cancellationObservingV3Repository{SlotExternalEffectV3Repository: baseEffects}
	var cancel context.CancelFunc
	artifacts := &cancellationObservingArtifactStore{
		recordingArtifactStore: &recordingArtifactStore{ensureErrors: []error{objectstore.ErrObjectConflict}},
		onEnsure: func() {
			cancel()
		},
	}
	activities := newV3Activities(t, repository, effects, &recordingStagedExecutor{}, artifacts)
	ctx, cancelCtx := context.WithCancel(context.Background())
	cancel = cancelCtx
	defer cancel()

	_, err := activities.ExecuteSlotV3(ctx, input)

	requireV3ApplicationErrorType(t, err, slotStagingOutcomeUnknownCode)
	require.Zero(t, artifacts.PreserveCalls(), "resumed staging must not regenerate or preserve again")
	require.False(t, artifacts.EnsureSawCancelledContext(), "resumed staging must use detached finalization context")
	require.False(t, effects.BlockSawCancelledContext(), "resumed staging fallback must use detached finalization context")

	stored, getErr := baseEffects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, getErr)
	require.Equal(t, imageagent.SlotEffectV3StagingUnknown, stored.Phase)
}

func TestExecuteSlotV3RecoversLostTransitionResponses(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-lost-transition-responses")
	baseEffects := repository.(imageagent.SlotExternalEffectV3Repository)
	effects := &lostResponseV3Repository{SlotExternalEffectV3Repository: baseEffects, loseStagedCommit: true, loseCompletion: true}
	path := writeTinyPNG(t)
	executor := &recordingStagedExecutor{generated: generatedV3Output(input, path)}
	artifacts := &recordingArtifactStore{}
	activities := newV3Activities(t, repository, effects, executor, artifacts)

	result, err := activities.ExecuteSlotV3(context.Background(), input)
	require.NoError(t, err)
	require.Len(t, result.Candidates, 1)
	require.Equal(t, 1, executor.GenerateCalls())
	require.Equal(t, 1, artifacts.EnsureCalls())
	require.Equal(t, 1, artifacts.FinalizeCalls())
	require.GreaterOrEqual(t, effects.RenewCalls(), 2)

	stored, err := baseEffects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, err)
	require.Equal(t, imageagent.SlotEffectV3PublicationComplete, stored.Phase)
}

func TestExecuteSlotV3RecoversLostStagingPreparationResponse(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-lost-staging-preparation")
	baseEffects := repository.(imageagent.SlotExternalEffectV3Repository)
	effects := &lostResponseV3Repository{SlotExternalEffectV3Repository: baseEffects, losePreparation: true}
	path := writeTinyPNG(t)
	executor := &recordingStagedExecutor{generated: generatedV3Output(input, path)}
	artifacts := &recordingArtifactStore{}
	activities := newV3Activities(t, repository, effects, executor, artifacts)

	result, err := activities.ExecuteSlotV3(context.Background(), input)
	require.NoError(t, err)
	require.Len(t, result.Candidates, 1)
	require.Equal(t, 1, executor.GenerateCalls())
	require.Equal(t, 1, artifacts.PrepareCalls())
	require.Equal(t, 1, artifacts.EnsureCalls())
}

func TestExecuteSlotV3RecoversLostPublicationClaimResponse(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-lost-claim-response")
	baseEffects := repository.(imageagent.SlotExternalEffectV3Repository)
	seedV3ArtifactStaged(t, baseEffects, input, v3StagingManifest(input, tinyPNGBytes(t)))
	effects := &lostResponseV3Repository{SlotExternalEffectV3Repository: baseEffects, loseClaim: true}
	artifacts := &recordingArtifactStore{}
	activities := newV3Activities(t, repository, effects, &recordingStagedExecutor{}, artifacts)
	result, err := activities.ExecuteSlotV3(context.Background(), input)
	require.NoError(t, err)
	require.Len(t, result.Candidates, 1)
	require.Equal(t, 1, artifacts.FinalizeCalls())
	stored, err := baseEffects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, err)
	require.EqualValues(t, 1, stored.Publication.Fence)
}

func TestExecuteSlotV3CancellationReconcilesLostPublicationResponsesWithinFinalizationWindow(t *testing.T) {
	for _, test := range []struct {
		name           string
		loseClaim      bool
		loseCompletion bool
	}{
		{name: "claim", loseClaim: true},
		{name: "completion", loseCompletion: true},
	} {
		t.Run(test.name, func(t *testing.T) {
			repository, input := initializedSlotEffectV3Activity(t, "run-v3-cancelled-lost-publication-"+test.name)
			input.ExternalEffectFinalization = true
			baseEffects := repository.(imageagent.SlotExternalEffectV3Repository)
			seedV3ArtifactStaged(t, baseEffects, input, v3StagingManifest(input, tinyPNGBytes(t)))
			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()
			effects := &lostResponseV3Repository{
				SlotExternalEffectV3Repository: baseEffects,
				loseClaim:                      test.loseClaim,
				loseCompletion:                 test.loseCompletion,
				rejectCancelledGet:             true,
			}
			if test.loseClaim {
				effects.onLostClaim = cancel
			} else {
				effects.onLostCompletion = cancel
			}
			activities := newV3Activities(t, repository, effects, &recordingStagedExecutor{}, &recordingArtifactStore{})

			result, err := activities.ExecuteSlotV3(ctx, input)

			require.NoError(t, err)
			require.Len(t, result.Candidates, 1)
			require.False(t, effects.ReconciliationGetSawCancelledContext(), "lost-response reconciliation must not fall back to the cancelled activity context")
			operationDeadline, reconciliationDeadline := effects.PublicationReconciliationDeadlines(test.loseClaim)
			require.False(t, operationDeadline.IsZero(), "publication operation must be bounded")
			require.False(t, reconciliationDeadline.IsZero(), "publication reconciliation must be bounded")
			require.True(t, operationDeadline.Equal(reconciliationDeadline), "lost-response reconciliation must share the one finalization window")
		})
	}
}

func TestImageSlotWorkflowV3StartsFreshActivityAfterFinalInnerAttemptLosesPublicationResponse(t *testing.T) {
	var suite testsuite.WorkflowTestSuite
	env := suite.NewTestWorkflowEnvironment()
	leaseDuration := 30 * time.Second
	repository := store.NewMemoryRepositoryWithClock(func() time.Time { return env.Now().UTC() })
	identity := imageagent.ExecutionIdentity{TenantID: "tenant-a", UserID: "user-a"}
	run := imageagent.Run{ID: "run-v3-delayed-takeover", BusinessTaskID: "task-delayed-takeover", TenantID: identity.TenantID, UserID: identity.UserID, Mode: imageagent.RunModeManual, IdempotencyKey: "run-delayed-takeover", Status: imageagent.RunStatusExecuting, ActivePlanRevision: 1, Version: 1}
	plan := imageagent.Plan{Revision: 1, IdempotencyKey: "plan-delayed-takeover", SourceAssetIDs: []string{"source-1"}, CreatedBy: identity.UserID, Slots: []imageagent.Slot{{ID: "slot-1", Role: imageagent.SlotRoleMain, SourceAssetIDs: []string{"source-1"}, IdempotencyKey: "slot-delayed-takeover"}}}
	initializeActivityProjection(t, repository, run, plan)
	input := ExecuteSlotV3ActivityInput{RunID: run.ID, Identity: identity, PlanRevision: plan.Revision, Slot: plan.Slots[0], Attempt: 1, IdempotencyKey: "slot-delayed-takeover:plan:1:attempt:1"}
	baseEffects := repository.(imageagent.SlotExternalEffectV3Repository)
	seedV3ArtifactStaged(t, baseEffects, input, v3StagingManifest(input, tinyPNGBytes(t)))
	effects := &delayedTakeoverV3Repository{SlotExternalEffectV3Repository: baseEffects, reserveFailures: 4}
	executor := &recordingStagedExecutor{}
	artifacts := &lostPublicationResponseArtifactStore{recordingArtifactStore: &recordingArtifactStore{}, loseFirstResponse: true}
	activities, err := NewActivities(ActivityDependencies{
		Repository: repository, SlotEffects: repository.(imageagent.SlotExternalEffectRepository), SlotExecutor: executor,
		SlotEffectsV3: effects, StagedSlotExecutor: executor, ArtifactStore: artifacts,
		Publisher: &identityCheckingPublisher{t: t}, PublisherV3: &identityCheckingPublisher{t: t}, PublicationLeaseDuration: leaseDuration,
	})
	require.NoError(t, err)
	env.RegisterWorkflow(ImageSlotWorkflowV3)
	env.RegisterActivityWithOptions(activities.ExecuteSlotV3, sdkactivity.RegisterOptions{Name: activityExecuteSlotV3})
	startedAt := env.Now()

	env.ExecuteWorkflow(ImageSlotWorkflowV3, SlotWorkflowV3Input{
		RunID: input.RunID, Identity: input.Identity, PlanRevision: input.PlanRevision, Slot: input.Slot,
		Attempt: input.Attempt, AssetCatalog: input.AssetCatalog, ExecuteActivityName: activityExecuteSlotV3,
	})

	require.NoError(t, env.GetWorkflowError())
	var result SlotWorkflowV3Result
	require.NoError(t, env.GetWorkflowResult(&result))
	require.Equal(t, imageagent.SlotStatusAccepted, result.Status)
	require.GreaterOrEqual(t, env.Now().Sub(startedAt), leaseDuration)
	require.Zero(t, executor.GenerateCalls(), "activity retries must resume staged artifacts without regeneration")
	require.Equal(t, 2, artifacts.FinalizeCalls(), "takeover may reconcile publication but must not multiply completion")
	require.Equal(t, 1, effects.CompletionCalls())
	owners, claims, acquired := effects.ClaimHistory()
	require.Len(t, owners, 2)
	require.True(t, strings.HasSuffix(owners[0], "/5"), owners)
	require.True(t, strings.HasSuffix(owners[1], "/1"), owners)
	firstOwner := strings.Split(owners[0], "/")
	secondOwner := strings.Split(owners[1], "/")
	require.Len(t, firstOwner, 3)
	require.Len(t, secondOwner, 3)
	require.NotEqual(t, firstOwner[1], secondOwner[1], "takeover must use a fresh activity execution with a reset inner retry budget")
	require.Equal(t, []bool{true, true}, acquired)
	require.EqualValues(t, 1, claims[0].Fence)
	require.EqualValues(t, 2, claims[1].Fence)
	stored, err := baseEffects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, err)
	require.Equal(t, imageagent.SlotEffectV3PublicationComplete, stored.Phase)
	require.Equal(t, owners[1], stored.Publication.Owner)
	require.EqualValues(t, 2, stored.Publication.Fence)
}

func TestExecuteSlotV3FencesLatePublicationOwner(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-stale-publication")
	effects := repository.(imageagent.SlotExternalEffectV3Repository)
	manifest := v3StagingManifest(input, tinyPNGBytes(t))
	seedV3ArtifactStaged(t, effects, input, manifest)
	final := v3FinalManifest(manifest)
	publicationFingerprint, err := imageagent.FinalManifestFingerprint(final)
	require.NoError(t, err)
	artifacts := &recordingArtifactStore{}
	artifacts.onFinalize = func() {
		time.Sleep(40 * time.Millisecond)
		_, successor, claimed, claimErr := effects.ClaimSlotPublicationV3(context.Background(), imageagent.PublicationClaimRequest{
			Reservation: v3Reservation(input), Owner: "workflow-run/activity/2", LeaseDuration: time.Minute,
			PublicationFingerprint: publicationFingerprint, FinalManifest: final,
		})
		require.NoError(t, claimErr)
		require.True(t, claimed)
		require.EqualValues(t, 2, successor.Fence)
	}
	executor := &recordingStagedExecutor{}
	activities := newV3Activities(t, repository, effects, executor, artifacts)
	activities.publicationLeaseDuration = 20 * time.Millisecond

	_, err = activities.ExecuteSlotV3(context.Background(), input)
	require.ErrorIs(t, err, imageagent.ErrRevisionConflict)
	require.Equal(t, 1, artifacts.FinalizeCalls(), "a stale owner may finish deterministic reconciliation")
	require.Zero(t, executor.BuildCalls(), "stale owner must stop before committing a result")

	stored, err := effects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, err)
	require.Equal(t, imageagent.SlotEffectV3PublicationClaimed, stored.Phase)
	require.Equal(t, "workflow-run/activity/2", stored.Publication.Owner)
	require.EqualValues(t, 2, stored.Publication.Fence)
	require.Empty(t, stored.Published.Candidates)
}

func TestExecuteSlotV3BlocksUnreconcilablePublication(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-publication-unknown")
	effects := repository.(imageagent.SlotExternalEffectV3Repository)
	seedV3ArtifactStaged(t, effects, input, v3StagingManifest(input, tinyPNGBytes(t)))
	artifacts := &recordingArtifactStore{finalizeError: objectstore.ErrObjectConflict}
	activities := newV3Activities(t, repository, effects, &recordingStagedExecutor{}, artifacts)

	_, err := activities.ExecuteSlotV3(context.Background(), input)
	requireV3ApplicationErrorType(t, err, slotPublicationOutcomeUnknownCode)
	stored, err := effects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, err)
	require.Equal(t, imageagent.SlotEffectV3PublicationUnknown, stored.Phase)
	require.Equal(t, slotPublicationOutcomeUnknownCode, stored.BlockedCode)

	_, err = activities.ExecuteSlotV3(context.Background(), input)
	requireV3ApplicationErrorType(t, err, slotPublicationOutcomeUnknownCode)
	require.Equal(t, 1, artifacts.FinalizeCalls(), "publication unknown must not expose blind activity retry")
}

func TestExecuteSlotV3CancellationTerminalizesPublicationClaim(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-publication-cancelled")
	input.ExternalEffectFinalization = true
	baseEffects := repository.(imageagent.SlotExternalEffectV3Repository)
	seedV3ArtifactStaged(t, baseEffects, input, v3StagingManifest(input, tinyPNGBytes(t)))
	effects := &cancellationObservingV3Repository{SlotExternalEffectV3Repository: baseEffects}
	var cancel context.CancelFunc
	artifacts := &cancellationObservingArtifactStore{
		recordingArtifactStore: &recordingArtifactStore{
			onProgress: func(int) {
				cancel()
			},
		},
	}
	executor := &recordingStagedExecutor{failBuildOnCancelledContext: true}
	activities := newV3Activities(t, repository, effects, executor, artifacts)
	ctx, cancelCtx := context.WithCancel(context.Background())
	cancel = cancelCtx
	defer cancel()

	result, err := activities.ExecuteSlotV3(ctx, input)

	require.NoError(t, err)
	require.Len(t, result.Candidates, 1)
	require.False(t, artifacts.FinalizeSawCancelledContext(), "publication finalization must use the detached finalization context")
	require.False(t, effects.RenewSawCancelledContext(), "publication lease renewal must use the detached finalization context")
	require.False(t, effects.CompleteSawCancelledContext(), "publication completion must use the detached finalization context")
	require.False(t, executor.BuildSawCancelledContext(), "result construction must use the detached finalization context")

	stored, getErr := baseEffects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, getErr)
	require.Equal(t, imageagent.SlotEffectV3PublicationComplete, stored.Phase)
}

func TestExecuteSlotV3CancellationAfterPublicationClaimDetachesFinalizationWithoutWire(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-publication-cancelled-without-wire")
	baseEffects := repository.(imageagent.SlotExternalEffectV3Repository)
	seedV3ArtifactStaged(t, baseEffects, input, v3StagingManifest(input, tinyPNGBytes(t)))
	effects := &cancellationObservingV3Repository{SlotExternalEffectV3Repository: baseEffects}
	var cancel context.CancelFunc
	artifacts := &cancellationObservingArtifactStore{
		recordingArtifactStore: &recordingArtifactStore{onProgress: func(int) { cancel() }},
	}
	executor := &recordingStagedExecutor{failBuildOnCancelledContext: true}
	activities := newV3Activities(t, repository, effects, executor, artifacts)
	ctx, cancelCtx := context.WithCancel(context.Background())
	cancel = cancelCtx
	defer cancel()

	result, err := activities.ExecuteSlotV3(ctx, input)

	require.NoError(t, err)
	require.Len(t, result.Candidates, 1)
	require.False(t, artifacts.FinalizeSawCancelledContext())
	require.False(t, effects.RenewSawCancelledContext())
	require.False(t, effects.CompleteSawCancelledContext())
	require.False(t, executor.BuildSawCancelledContext())
	stored, getErr := baseEffects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, getErr)
	require.Equal(t, imageagent.SlotEffectV3PublicationComplete, stored.Phase)
}

func TestExecuteSlotV3BlocksMissingPreparedBytesWithoutRegeneration(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-staging-unknown")
	effects := repository.(imageagent.SlotExternalEffectV3Repository)
	seedV3StagingPrepared(t, effects, input, v3StagingManifest(input, tinyPNGBytes(t)))
	executor := &recordingStagedExecutor{}
	artifacts := &recordingArtifactStore{ensureErrors: []error{objectstore.ErrArtifactUnavailable}, recoverError: objectstore.ErrArtifactUnavailable}
	activities := newV3Activities(t, repository, effects, executor, artifacts)

	_, err := activities.ExecuteSlotV3(context.Background(), input)
	requireV3ApplicationErrorType(t, err, slotStagingOutcomeUnknownCode)
	require.Zero(t, executor.GenerateCalls())
	stored, err := effects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, err)
	require.Equal(t, imageagent.SlotEffectV3StagingUnknown, stored.Phase)
}

func TestExecuteSlotV3ReturnsStoredExactResultWithoutEffects(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-exact-replay")
	effects := repository.(imageagent.SlotExternalEffectV3Repository)
	path := writeTinyPNG(t)
	executor := &recordingStagedExecutor{generated: generatedV3Output(input, path)}
	artifacts := &recordingArtifactStore{}
	activities := newV3Activities(t, repository, effects, executor, artifacts)

	first, err := activities.ExecuteSlotV3(context.Background(), input)
	require.NoError(t, err)
	second, err := activities.ExecuteSlotV3(context.Background(), input)
	require.NoError(t, err)
	require.Equal(t, first, second)
	require.Equal(t, 1, executor.GenerateCalls())
	require.Equal(t, 1, executor.BuildCalls())
	require.Equal(t, 1, artifacts.FinalizeCalls())
}

func TestExecuteSlotV3ResultPreservesDurableIdentityOnTheV3Wire(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-durable-result-wire")
	path := writeTinyPNG(t)
	activities := newV3Activities(t, repository, repository.(imageagent.SlotExternalEffectV3Repository), &recordingStagedExecutor{generated: generatedV3Output(input, path)}, &recordingArtifactStore{})

	result, err := activities.ExecuteSlotV3(context.Background(), input)
	require.NoError(t, err)
	encoded, err := json.Marshal(result)
	require.NoError(t, err)
	require.Contains(t, string(encoded), `"durable_asset"`)
	require.Contains(t, string(encoded), `"object_key"`)
	require.Contains(t, string(encoded), `"sha256"`)
}

func TestExecuteSlotV3PublicationOwnerIncludesTemporalRunActivityAndAttempt(t *testing.T) {
	owner, err := publicationOwnerFromActivityInfo(sdkactivity.Info{
		WorkflowExecution: workflow.Execution{RunID: "workflow-run-7"}, ActivityID: "activity-12", Attempt: 3,
	})
	require.NoError(t, err)
	require.Equal(t, "workflow-run-7/activity-12/3", owner)
}

func TestTemporalPublicationOwnerRejectsDirectContextWithoutPanic(t *testing.T) {
	require.NotPanics(t, func() {
		owner, err := temporalPublicationOwner(context.Background())
		require.Empty(t, owner)
		require.ErrorIs(t, err, errPublicationOwnerRequiresActivity)
	})
}

func TestExecuteSlotV3FailsClosedForUnknownPersistedPhase(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-unknown-phase")
	baseEffects := repository.(imageagent.SlotExternalEffectV3Repository)
	effects := &phaseOverrideV3Repository{SlotExternalEffectV3Repository: baseEffects, phase: "future_phase"}
	activities := newV3Activities(t, repository, effects, &recordingStagedExecutor{}, &recordingArtifactStore{})

	_, err := activities.ExecuteSlotV3(context.Background(), input)
	requireV3ApplicationErrorType(t, err, slotEffectPhaseInvalidCode)
}

func TestExecuteSlotV3FailsClosedForMismatchedPersistedBlockedPolicy(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-mismatched-policy")
	baseEffects := repository.(imageagent.SlotExternalEffectV3Repository)
	effects := &attemptOverrideV3Repository{SlotExternalEffectV3Repository: baseEffects, mutate: func(attempt *imageagent.SlotEffectV3Attempt) {
		attempt.Phase = imageagent.SlotEffectV3PublicationUnknown
		attempt.BlockedCode = imageagent.SlotProviderOutcomeUnknownCode
	}}
	activities := newV3Activities(t, repository, effects, &recordingStagedExecutor{}, &recordingArtifactStore{})

	_, err := activities.ExecuteSlotV3(context.Background(), input)
	requireV3ApplicationErrorType(t, err, slotEffectPolicyInvalidCode)
}

func TestExecuteSlotV3RejectsFaultyExecutorCompletionBijection(t *testing.T) {
	mutations := []struct {
		name   string
		mutate func(*imageagent.SlotExecutionResult)
	}{
		{name: "missing", mutate: func(result *imageagent.SlotExecutionResult) { result.Candidates = result.Candidates[:1] }},
		{name: "duplicate", mutate: func(result *imageagent.SlotExecutionResult) {
			result.Candidates[1].DurableAsset = result.Candidates[0].DurableAsset
		}},
		{name: "reordered", mutate: func(result *imageagent.SlotExecutionResult) {
			result.Candidates[0], result.Candidates[1] = result.Candidates[1], result.Candidates[0]
		}},
		{name: "false lineage", mutate: func(result *imageagent.SlotExecutionResult) { result.Candidates[1].SourceAssetID = "source-false" }},
	}
	for _, mutation := range mutations {
		t.Run(mutation.name, func(t *testing.T) {
			repository, input := initializedSlotEffectV3Activity(t, "run-v3-faulty-"+strings.ReplaceAll(mutation.name, " ", "-"))
			effects := repository.(imageagent.SlotExternalEffectV3Repository)
			manifest := v3StagingManifest(input, tinyPNGBytes(t))
			second := manifest.Assets[0]
			second.ObjectKey = strings.Replace(second.ObjectKey, "/0-", "/1-", 1)
			manifest.Assets = append(manifest.Assets, second)
			seedV3ArtifactStaged(t, effects, input, manifest)
			executor := &recordingStagedExecutor{mutateResult: mutation.mutate}
			activities := newV3Activities(t, repository, effects, executor, &recordingArtifactStore{})

			_, err := activities.ExecuteSlotV3(context.Background(), input)
			require.ErrorIs(t, err, imageagent.ErrRevisionConflict)
			stored, getErr := effects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
			require.NoError(t, getErr)
			require.Equal(t, imageagent.SlotEffectV3PublicationClaimed, stored.Phase)
		})
	}
}

func TestExecuteSlotV3RenewsLeaseBetweenAssetsToPreventTakeover(t *testing.T) {
	clock := time.Date(2026, time.August, 27, 12, 0, 0, 0, time.UTC)
	repository := store.NewMemoryRepositoryWithClock(func() time.Time { return clock })
	identity := imageagent.ExecutionIdentity{TenantID: "tenant-a", UserID: "user-a"}
	run := imageagent.Run{ID: "run-v3-progress-renewal", BusinessTaskID: "task-progress", TenantID: identity.TenantID, UserID: identity.UserID, Mode: imageagent.RunModeManual, IdempotencyKey: "run-progress", Status: imageagent.RunStatusExecuting, ActivePlanRevision: 1, Version: 1}
	plan := imageagent.Plan{Revision: 1, IdempotencyKey: "plan-progress", SourceAssetIDs: []string{"source-1"}, CreatedBy: identity.UserID, Slots: []imageagent.Slot{{ID: "slot-1", Role: imageagent.SlotRoleMain, SourceAssetIDs: []string{"source-1"}, IdempotencyKey: "slot-progress"}}}
	initializeActivityProjection(t, repository, run, plan)
	input := ExecuteSlotV3ActivityInput{RunID: run.ID, Identity: identity, PlanRevision: 1, Slot: plan.Slots[0], Attempt: 1, IdempotencyKey: "slot-progress:plan:1:attempt:1"}
	effects := repository.(imageagent.SlotExternalEffectV3Repository)
	manifest := v3StagingManifest(input, tinyPNGBytes(t))
	second := manifest.Assets[0]
	second.ObjectKey = strings.Replace(second.ObjectKey, "/0-", "/1-", 1)
	manifest.Assets = append(manifest.Assets, second)
	seedV3ArtifactStaged(t, effects, input, manifest)
	artifacts := &recordingArtifactStore{}
	var takeoverClaims int
	artifacts.onProgress = func(index int) {
		clock = clock.Add(40 * time.Second)
		final := v3FinalManifest(manifest)
		fingerprint, err := imageagent.FinalManifestFingerprint(final)
		require.NoError(t, err)
		_, _, claimed, err := effects.ClaimSlotPublicationV3(context.Background(), imageagent.PublicationClaimRequest{Reservation: v3Reservation(input), Owner: fmt.Sprintf("successor-%d", index), LeaseDuration: time.Minute, PublicationFingerprint: fingerprint, FinalManifest: final})
		require.NoError(t, err)
		if claimed {
			takeoverClaims++
		}
	}
	activities := newV3Activities(t, repository, effects, &recordingStagedExecutor{}, artifacts)
	activities.publicationLeaseDuration = time.Minute

	_, err := activities.ExecuteSlotV3(context.Background(), input)
	require.NoError(t, err)
	require.Zero(t, takeoverClaims)
	require.Equal(t, 2, artifacts.ProgressCalls())
	require.True(t, clock.After(time.Date(2026, time.August, 27, 12, 1, 0, 0, time.UTC)), "whole finalization exceeded the original lease")
}

func TestExecuteSlotV3CancelsBlockingSDKCallBeforeLeaseExpiryWithoutTakeover(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-blocking-sdk")
	effects := repository.(imageagent.SlotExternalEffectV3Repository)
	manifest := v3StagingManifest(input, tinyPNGBytes(t))
	seedV3ArtifactStaged(t, effects, input, manifest)
	staged := manifest.Assets[0]
	api := &statefulActivityS3API{
		objects: map[string]activityS3Object{
			staged.ObjectKey: {contentType: staged.ContentType, contentLength: staged.SizeBytes, metadata: map[string]string{"sha256": staged.SHA256, "size-bytes": fmt.Sprint(staged.SizeBytes)}},
		},
		blockHead: true,
	}
	artifacts := newProductionArtifactStore(t, api)
	activities := newV3Activities(t, repository, effects, &recordingStagedExecutor{}, artifacts)
	const lease = 200 * time.Millisecond
	activities.publicationLeaseDuration = lease

	started := time.Now()
	_, err := activities.ExecuteSlotV3(context.Background(), input)
	elapsed := time.Since(started)
	require.ErrorIs(t, err, context.DeadlineExceeded)
	require.Less(t, elapsed, lease)
	require.False(t, api.headDeadline.IsZero(), "blocking SDK call must receive a deadline")
	require.True(t, api.headDeadline.Before(started.Add(lease)), "SDK deadline must be strictly before lease expiry")

	stored, err := effects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, err)
	require.Equal(t, imageagent.SlotEffectV3PublicationClaimed, stored.Phase, "timeout is ambiguous and must remain reconcilable")
	final := v3FinalManifest(manifest)
	fingerprint, err := imageagent.FinalManifestFingerprint(final)
	require.NoError(t, err)
	_, _, tookOver, err := effects.ClaimSlotPublicationV3(context.Background(), imageagent.PublicationClaimRequest{
		Reservation: v3Reservation(input), Owner: "workflow-run/activity/2", LeaseDuration: lease,
		PublicationFingerprint: fingerprint, FinalManifest: final,
	})
	require.NoError(t, err)
	require.False(t, tookOver)
}

func TestExecuteSlotV3UsesProductionStoreToReconcileLostPutAndCopyResponses(t *testing.T) {
	repository, input := initializedSlotEffectV3Activity(t, "run-v3-production-lost-responses")
	path := writeTinyPNG(t)
	api := &statefulActivityS3API{objects: map[string]activityS3Object{}, loseNextPutAfterWrite: true, loseNextCopyAfterWrite: true}
	artifacts := newProductionArtifactStore(t, api)
	executor := &recordingStagedExecutor{generated: generatedV3Output(input, path)}
	activities := newV3Activities(t, repository, repository.(imageagent.SlotExternalEffectV3Repository), executor, artifacts)

	result, err := activities.ExecuteSlotV3(context.Background(), input)
	require.NoError(t, err)
	require.Len(t, result.Candidates, 1)
	require.Equal(t, 2, api.putCalls, "one recovery bundle and one staged asset must be uploaded")
	recoveryBundles := 0
	for key := range api.objects {
		if strings.HasSuffix(key, "/recovery.tar") {
			recoveryBundles++
		}
	}
	require.Equal(t, 1, recoveryBundles, "the generated bytes must have one durable recovery bundle")
	require.Equal(t, 1, api.copyCalls)
	stored, err := repository.(imageagent.SlotExternalEffectV3Repository).GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, err)
	require.Equal(t, imageagent.SlotEffectV3PublicationComplete, stored.Phase)
}

func TestExecuteSlotV3ProductionStoreReconcilesMultiAssetAfterLocalBytesVanish(t *testing.T) {
	for _, tc := range []struct {
		name      string
		configure func(*statefulActivityS3API, *failOnceStagedCommitRepository)
		wantPhase imageagent.SlotEffectV3Phase
		wantError string
	}{
		{name: "all matching", configure: func(_ *statefulActivityS3API, repository *failOnceStagedCommitRepository) { repository.fail = true }, wantPhase: imageagent.SlotEffectV3PublicationComplete},
		{name: "partial missing", configure: func(api *statefulActivityS3API, _ *failOnceStagedCommitRepository) { api.failPutCall = 2 }, wantPhase: imageagent.SlotEffectV3PublicationComplete},
		{name: "mismatch", configure: func(_ *statefulActivityS3API, repository *failOnceStagedCommitRepository) { repository.fail = true }, wantPhase: imageagent.SlotEffectV3StagingUnknown, wantError: slotStagingOutcomeUnknownCode},
	} {
		t.Run(tc.name, func(t *testing.T) {
			repository, input := initializedSlotEffectV3Activity(t, "run-v3-production-"+strings.ReplaceAll(tc.name, " ", "-"))
			baseEffects := repository.(imageagent.SlotExternalEffectV3Repository)
			effects := &failOnceStagedCommitRepository{SlotExternalEffectV3Repository: baseEffects}
			api := &statefulActivityS3API{objects: map[string]activityS3Object{}}
			tc.configure(api, effects)
			paths := []string{writeTinyPNG(t), writeTinyPNG(t)}
			generated := generatedV3Output(input, paths[0])
			generated.Assets = append(generated.Assets, generated.Assets[0])
			generated.Assets[1].URL = paths[1]
			generated.Assets[1].Metadata = map[string]string{"local_path": paths[1], "authorization": "must-not-persist"}
			executor := &recordingStagedExecutor{generated: generated}
			artifacts := newProductionArtifactStore(t, api)
			first := newV3Activities(t, repository, effects, executor, artifacts)
			_, firstErr := first.ExecuteSlotV3(context.Background(), input)
			require.Error(t, firstErr)
			for _, path := range paths {
				require.NoFileExists(t, path, "the durable recovery bundle replaces worker-local retry bytes")
			}
			if tc.name == "mismatch" {
				for key, object := range api.objects {
					if strings.Contains(key, "/1-") {
						object.metadata["sha256"] = strings.Repeat("c", 64)
						object.checksumSHA = "invalid-checksum"
						api.objects[key] = object
					}
				}
			}
			second := newV3Activities(t, repository, baseEffects, executor, artifacts)
			_, secondErr := second.ExecuteSlotV3(context.Background(), input)
			if tc.wantError == "" {
				require.NoError(t, secondErr)
			} else {
				requireV3ApplicationErrorType(t, secondErr, tc.wantError)
			}
			require.Equal(t, 1, executor.GenerateCalls(), "activity retry must never regenerate")
			stored, err := baseEffects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
			require.NoError(t, err)
			require.Equal(t, tc.wantPhase, stored.Phase)
		})
	}
}

func TestExecuteSlotV3ProductionStoreCompletionCrashTakesOverWithoutRecopy(t *testing.T) {
	clock := time.Date(2026, time.August, 27, 15, 0, 0, 0, time.UTC)
	repository := store.NewMemoryRepositoryWithClock(func() time.Time { return clock })
	identity := imageagent.ExecutionIdentity{TenantID: "tenant-a", UserID: "user-a"}
	run := imageagent.Run{ID: "run-v3-completion-crash", BusinessTaskID: "task-crash", TenantID: identity.TenantID, UserID: identity.UserID, Mode: imageagent.RunModeManual, IdempotencyKey: "run-crash", Status: imageagent.RunStatusExecuting, ActivePlanRevision: 1, Version: 1}
	plan := imageagent.Plan{Revision: 1, IdempotencyKey: "plan-crash", SourceAssetIDs: []string{"source-1"}, CreatedBy: identity.UserID, Slots: []imageagent.Slot{{ID: "slot-1", Role: imageagent.SlotRoleMain, SourceAssetIDs: []string{"source-1"}, IdempotencyKey: "slot-crash"}}}
	initializeActivityProjection(t, repository, run, plan)
	input := ExecuteSlotV3ActivityInput{RunID: run.ID, Identity: identity, PlanRevision: 1, Slot: plan.Slots[0], Attempt: 1, IdempotencyKey: "slot-crash:plan:1:attempt:1"}
	baseEffects := repository.(imageagent.SlotExternalEffectV3Repository)
	effects := &failOnceCompletionRepository{SlotExternalEffectV3Repository: baseEffects, fail: true}
	api := &statefulActivityS3API{objects: map[string]activityS3Object{}}
	artifacts := newProductionArtifactStore(t, api)
	executor := &recordingStagedExecutor{generated: generatedV3Output(input, writeTinyPNG(t))}
	first := newV3ActivitiesWithOwner(t, repository, effects, executor, artifacts, "workflow-run/activity/1")
	first.publicationLeaseDuration = time.Minute

	_, err := first.ExecuteSlotV3(context.Background(), input)
	require.ErrorIs(t, err, imageagent.ErrRevisionConflict)
	require.Equal(t, 1, api.copyCalls)
	clock = clock.Add(2 * time.Minute)
	second := newV3ActivitiesWithOwner(t, repository, baseEffects, executor, artifacts, "workflow-run/activity/2")
	second.publicationLeaseDuration = time.Minute
	result, err := second.ExecuteSlotV3(context.Background(), input)
	require.NoError(t, err)
	require.Len(t, result.Candidates, 1)
	require.Equal(t, 1, api.copyCalls, "takeover must reconcile the deterministic final object")
	stored, err := baseEffects.GetSlotExternalEffectV3(context.Background(), v3Reservation(input).Identity)
	require.NoError(t, err)
	require.Equal(t, imageagent.SlotEffectV3PublicationComplete, stored.Phase)
	require.EqualValues(t, 2, stored.Publication.Fence)
}

func initializedSlotEffectV3Activity(t *testing.T, runID string) (imageagent.Repository, ExecuteSlotV3ActivityInput) {
	t.Helper()
	repository, legacy := initializedSlotEffectActivity(t, runID)
	return repository, ExecuteSlotV3ActivityInput{
		RunID: legacy.RunID, Identity: legacy.Identity, PlanRevision: legacy.PlanRevision, Slot: legacy.Slot,
		Attempt: legacy.Attempt, IdempotencyKey: legacy.IdempotencyKey, AssetCatalog: legacy.AssetCatalog,
	}
}

func newV3Activities(t *testing.T, repository imageagent.Repository, effects imageagent.SlotExternalEffectV3Repository, executor *recordingStagedExecutor, artifacts DurableArtifactStore) *Activities {
	return newV3ActivitiesWithOwner(t, repository, effects, executor, artifacts, "workflow-run/activity/1")
}

func newV3ActivitiesWithOwner(t *testing.T, repository imageagent.Repository, effects imageagent.SlotExternalEffectV3Repository, executor *recordingStagedExecutor, artifacts DurableArtifactStore, owner string) *Activities {
	t.Helper()
	activities, err := NewActivities(ActivityDependencies{
		Repository: repository, SlotEffects: repository.(imageagent.SlotExternalEffectRepository), SlotExecutor: executor,
		SlotEffectsV3: effects, StagedSlotExecutor: executor, ArtifactStore: artifacts,
		Publisher: &identityCheckingPublisher{t: t}, PublisherV3: &identityCheckingPublisher{t: t}, PublicationOwner: func(context.Context) (string, error) { return owner, nil },
	})
	require.NoError(t, err)
	return activities
}

func newProductionArtifactStore(t *testing.T, api *statefulActivityS3API) *objectstore.S3DurableArtifactStore {
	t.Helper()
	uploader := storageinfra.NewS3UploaderWithAPI(api, storageinfra.S3UploaderOptions{Bucket: "assets", ArtifactCapabilities: storageinfra.ArtifactStorageCapabilities{Mode: storageinfra.ArtifactStorageModeAWS}})
	artifacts, err := objectstore.NewS3DurableArtifactStore(uploader, objectstore.S3DurableArtifactStoreConfig{MaxArtifactBytes: 1 << 20, MaxArtifactCount: 16, MaxAggregateBytes: 16 << 20, OperationTimeout: 100 * time.Millisecond})
	require.NoError(t, err)
	return artifacts
}

func v3Reservation(input ExecuteSlotV3ActivityInput) imageagent.SlotEffectV3Reservation {
	execution := imageagent.SlotExecutionInput{
		RunID: input.RunID, TenantID: input.Identity.TenantID, UserID: input.Identity.UserID,
		PlanRevision: input.PlanRevision, Slot: input.Slot, Attempt: input.Attempt,
		IdempotencyKey: input.IdempotencyKey, AssetCatalog: input.AssetCatalog,
	}
	return imageagent.SlotEffectV3Reservation{
		Identity:       imageagent.SlotExternalEffectIdentity{RunScope: imageagent.RunScope{TenantID: input.Identity.TenantID, OwnerUserID: input.Identity.UserID, RunID: input.RunID}, PlanRevision: input.PlanRevision, SlotID: input.Slot.ID, Attempt: input.Attempt},
		IdempotencyKey: input.IdempotencyKey, InputFingerprint: imageagent.SlotExecutionFingerprint(execution),
	}
}

func seedV3StagingPrepared(t *testing.T, effects imageagent.SlotExternalEffectV3Repository, input ExecuteSlotV3ActivityInput, manifest imageagent.StagingManifest) {
	t.Helper()
	_, claimed, err := effects.ReserveSlotProviderV3(context.Background(), v3Reservation(input))
	require.NoError(t, err)
	require.True(t, claimed)
	_, err = effects.PrepareSlotStagingV3(context.Background(), v3Reservation(input), manifest)
	require.NoError(t, err)
}

func seedV3ArtifactStaged(t *testing.T, effects imageagent.SlotExternalEffectV3Repository, input ExecuteSlotV3ActivityInput, manifest imageagent.StagingManifest) {
	t.Helper()
	seedV3StagingPrepared(t, effects, input, manifest)
	fingerprint, err := imageagent.StagingManifestFingerprint(manifest)
	require.NoError(t, err)
	_, err = effects.CommitSlotStagedV3(context.Background(), v3Reservation(input), fingerprint)
	require.NoError(t, err)
}

func generatedV3Output(input ExecuteSlotV3ActivityInput, path string) imageagent.SlotGeneratedOutput {
	return imageagent.SlotGeneratedOutput{
		SlotID: input.Slot.ID, Attempt: input.Attempt, SourceAssetID: input.Slot.SourceAssetIDs[0],
		Assets: []imageagent.GeneratedAsset{{URL: path, Type: "gallery_image", Width: 1, Height: 1, Operations: []string{"render_scene_model"}, Metadata: map[string]string{"local_path": path, "authorization": "must-not-persist"}}},
	}
}

func writeTinyPNG(t *testing.T) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "generated.png")
	require.NoError(t, os.WriteFile(path, tinyPNGBytes(t), 0o600))
	return path
}

func tinyPNGBytes(t *testing.T) []byte {
	t.Helper()
	var data strings.Builder
	writer := &stringWriter{builder: &data}
	require.NoError(t, png.Encode(writer, image.NewNRGBA(image.Rect(0, 0, 1, 1))))
	return []byte(data.String())
}

type stringWriter struct{ builder *strings.Builder }

func (w *stringWriter) Write(data []byte) (int, error) { return w.builder.WriteString(string(data)) }

func v3StagingManifest(input ExecuteSlotV3ActivityInput, data []byte) imageagent.StagingManifest {
	sum := sha256.Sum256(data)
	hash := hex.EncodeToString(sum[:])
	ownerKey, err := imageagent.ArtifactOwnerKey(input.Identity.UserID)
	if err != nil {
		panic(err)
	}
	return imageagent.StagingManifest{Assets: []imageagent.StagedAssetRef{{
		ObjectKey: fmt.Sprintf("image-agent/staging/%s/%s/%s/%d/%s/%d/0-%s.png", input.Identity.TenantID, ownerKey, input.RunID, input.PlanRevision, input.Slot.ID, input.Attempt, hash),
		SHA256:    hash, SizeBytes: int64(len(data)), ContentType: "image/png", Width: 1, Height: 1,
		SourceAssetID: input.Slot.SourceAssetIDs[0], Operations: []string{"render_scene_model"},
	}}}
}

func v3FinalManifest(staging imageagent.StagingManifest) imageagent.FinalManifest {
	assets := make([]imageagent.PublishedAssetRef, len(staging.Assets))
	for index, asset := range staging.Assets {
		assets[index] = imageagent.PublishedAssetRef{
			ObjectKey: strings.Replace(asset.ObjectKey, "image-agent/staging/", "image-agent/public/", 1),
			SHA256:    asset.SHA256, SizeBytes: asset.SizeBytes, ContentType: asset.ContentType, Width: asset.Width, Height: asset.Height,
			SourceAssetID: asset.SourceAssetID, Operations: append([]string(nil), asset.Operations...), ProviderReceiptID: asset.ProviderReceiptID,
		}
	}
	return imageagent.FinalManifest{Assets: assets}
}

func requireV3ApplicationErrorType(t *testing.T, err error, want string) {
	t.Helper()
	var applicationError *sdktemporal.ApplicationError
	require.ErrorAs(t, err, &applicationError)
	require.Equal(t, want, applicationError.Type())
	require.True(t, applicationError.NonRetryable())
}

type recordingStagedExecutor struct {
	mu                          sync.Mutex
	generated                   imageagent.SlotGeneratedOutput
	generateErr                 error
	generateCalls               int
	buildCalls                  int
	mutateResult                func(*imageagent.SlotExecutionResult)
	identity                    productimage.AIIdentity
	started                     chan struct{}
	onGenerate                  func()
	waitForCancellation         bool
	buildSawCancelledContext    bool
	failBuildOnCancelledContext bool
}

func (e *recordingStagedExecutor) QuoteSlot(context.Context, imageagent.SlotExecutionInput, imageagent.BudgetPolicy) (imageagent.SlotUsageQuote, error) {
	maximum := imageagent.UsageVector{Images: 16, AgentSteps: 1}
	return imageagent.SlotUsageQuote{Maximum: maximum, Operations: []imageagent.SlotUsageOperation{{Name: "recording_provider", Fingerprint: "recording-provider-v1", Maximum: maximum, MaximumOutputs: 16}}, Fingerprint: "recording-slot-quote-v1"}, nil
}

func (e *recordingStagedExecutor) GenerateQuotedSlot(ctx context.Context, input imageagent.SlotExecutionInput, _ imageagent.SlotUsageQuote) (imageagent.SlotGeneratedOutput, error) {
	generated, err := e.GenerateSlot(ctx, input)
	if err == nil {
		generated.UsageReceipt = imageagent.SlotUsageReceipt{Actual: imageagent.UsageVector{Images: int64(len(generated.Assets)), AgentSteps: 1}, CostBasis: imageagent.UsageCostReservedUpperBound}
	}
	return generated, err
}

func (e *recordingStagedExecutor) ExecuteSlot(context.Context, imageagent.SlotExecutionInput) (imageagent.SlotExecutionResult, error) {
	return imageagent.SlotExecutionResult{}, errors.New("v2 execute must not be used by ExecuteSlotV3")
}

func (e *recordingStagedExecutor) GenerateSlot(ctx context.Context, input imageagent.SlotExecutionInput) (imageagent.SlotGeneratedOutput, error) {
	e.mu.Lock()
	e.generateCalls++
	e.identity = productimage.AIIdentityFromContext(ctx)
	generated, generateErr := e.generated, e.generateErr
	started, onGenerate, waitForCancellation := e.started, e.onGenerate, e.waitForCancellation
	e.mu.Unlock()
	if started != nil {
		close(started)
	}
	if waitForCancellation {
		<-ctx.Done()
	}
	if generateErr != nil {
		return imageagent.SlotGeneratedOutput{}, generateErr
	}
	if generated.SlotID == "" {
		return imageagent.SlotGeneratedOutput{}, errors.New("generated output fixture is required")
	}
	if onGenerate != nil {
		onGenerate()
	}
	return generated, nil
}

type cancellationRejectingV3Repository struct {
	imageagent.SlotExternalEffectV3Repository
	mu                       sync.Mutex
	recordedUnknown          bool
	writeSawCancelledContext bool
}

func (r *cancellationRejectingV3Repository) MarkSlotProviderBudgetUnknownV3(ctx context.Context, reservation imageagent.SlotEffectV3Reservation) (imageagent.SlotEffectV3Attempt, error) {
	if r.rejectCancelledWrite(ctx) {
		return imageagent.SlotEffectV3Attempt{}, context.Canceled
	}
	attempt, err := r.SlotExternalEffectV3Repository.MarkSlotProviderBudgetUnknownV3(ctx, reservation)
	if err == nil {
		r.mu.Lock()
		r.recordedUnknown = true
		r.mu.Unlock()
	}
	return attempt, err
}

func (r *cancellationRejectingV3Repository) BlockSlotEffectV3(ctx context.Context, transition imageagent.SlotEffectV3BlockTransition) (imageagent.SlotEffectV3Attempt, error) {
	if r.rejectCancelledWrite(ctx) {
		return imageagent.SlotEffectV3Attempt{}, context.Canceled
	}
	return r.SlotExternalEffectV3Repository.BlockSlotEffectV3(ctx, transition)
}

func (r *cancellationRejectingV3Repository) rejectCancelledWrite(ctx context.Context) bool {
	if ctx.Err() == nil {
		return false
	}
	r.mu.Lock()
	r.writeSawCancelledContext = true
	r.mu.Unlock()
	return true
}

func (r *cancellationRejectingV3Repository) RecordedUnknown() bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.recordedUnknown
}

func (r *cancellationRejectingV3Repository) WriteSawCancelledContext() bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.writeSawCancelledContext
}

type cancellationObservingV3Repository struct {
	imageagent.SlotExternalEffectV3Repository
	mu                          sync.Mutex
	prepareSawCancelledContext  bool
	blockSawCancelledContext    bool
	renewSawCancelledContext    bool
	completeSawCancelledContext bool
}

func (r *cancellationObservingV3Repository) PrepareSlotStagingV3(ctx context.Context, reservation imageagent.SlotEffectV3Reservation, manifest imageagent.StagingManifest) (imageagent.SlotEffectV3Attempt, error) {
	if ctx.Err() != nil {
		r.mu.Lock()
		r.prepareSawCancelledContext = true
		r.mu.Unlock()
	}
	return r.SlotExternalEffectV3Repository.PrepareSlotStagingV3(ctx, reservation, manifest)
}

func (r *cancellationObservingV3Repository) BlockSlotEffectV3(ctx context.Context, transition imageagent.SlotEffectV3BlockTransition) (imageagent.SlotEffectV3Attempt, error) {
	if ctx.Err() != nil {
		r.mu.Lock()
		r.blockSawCancelledContext = true
		r.mu.Unlock()
	}
	return r.SlotExternalEffectV3Repository.BlockSlotEffectV3(ctx, transition)
}

func (r *cancellationObservingV3Repository) RenewSlotPublicationV3(ctx context.Context, renewal imageagent.PublicationLeaseRenewal) (imageagent.PublicationClaim, error) {
	if ctx.Err() != nil {
		r.mu.Lock()
		r.renewSawCancelledContext = true
		r.mu.Unlock()
	}
	return r.SlotExternalEffectV3Repository.RenewSlotPublicationV3(ctx, renewal)
}

func (r *cancellationObservingV3Repository) CompleteSlotPublicationV3(ctx context.Context, completion imageagent.PublicationCompletion) (imageagent.SlotEffectV3Attempt, error) {
	if ctx.Err() != nil {
		r.mu.Lock()
		r.completeSawCancelledContext = true
		r.mu.Unlock()
	}
	return r.SlotExternalEffectV3Repository.CompleteSlotPublicationV3(ctx, completion)
}

func (r *cancellationObservingV3Repository) PrepareSawCancelledContext() bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.prepareSawCancelledContext
}

func (r *cancellationObservingV3Repository) BlockSawCancelledContext() bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.blockSawCancelledContext
}

func (r *cancellationObservingV3Repository) RenewSawCancelledContext() bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.renewSawCancelledContext
}

func (r *cancellationObservingV3Repository) CompleteSawCancelledContext() bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.completeSawCancelledContext
}

func (e *recordingStagedExecutor) BuildSlotResult(ctx context.Context, input imageagent.SlotExecutionInput, published imageagent.PublishedSlotOutput) (imageagent.SlotExecutionResult, error) {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.buildCalls++
	if ctx.Err() != nil {
		e.buildSawCancelledContext = true
		if e.failBuildOnCancelledContext {
			return imageagent.SlotExecutionResult{}, ctx.Err()
		}
	}
	candidates := make([]imageagent.AssetCandidate, len(published.Assets))
	for index, asset := range published.Assets {
		candidates[index] = imageagent.AssetCandidate{AssetID: fmt.Sprintf("candidate-%d", index), SourceAssetID: asset.SourceAssetID, DurableAsset: imageagent.DurableAssetIdentity{ObjectKey: asset.ObjectKey, SHA256: asset.SHA256}}
	}
	result := imageagent.SlotExecutionResult{SlotID: input.Slot.ID, Attempt: input.Attempt, Candidates: candidates}
	if e.mutateResult != nil {
		e.mutateResult(&result)
	}
	return result, nil
}

func (e *recordingStagedExecutor) PublishSlot(context.Context, imageagent.SlotExecutionInput, imageagent.SlotGeneratedOutput) (imageagent.SlotExecutionResult, error) {
	return imageagent.SlotExecutionResult{}, errors.New("v2 publication must not be used by ExecuteSlotV3")
}

func (e *recordingStagedExecutor) GenerateCalls() int {
	e.mu.Lock()
	defer e.mu.Unlock()
	return e.generateCalls
}
func (e *recordingStagedExecutor) BuildCalls() int {
	e.mu.Lock()
	defer e.mu.Unlock()
	return e.buildCalls
}

func (e *recordingStagedExecutor) BuildSawCancelledContext() bool {
	e.mu.Lock()
	defer e.mu.Unlock()
	return e.buildSawCancelledContext
}

func (e *recordingStagedExecutor) ProductImageIdentity() productimage.AIIdentity {
	e.mu.Lock()
	defer e.mu.Unlock()
	return e.identity
}

type recordingArtifactStore struct {
	mu             sync.Mutex
	prepareCalls   int
	ensureCalls    int
	finalizeCalls  int
	preserveError  error
	preserveErrors []error
	preserveCalls  int
	ensureErrors   []error
	recoverError   error
	finalizeError  error
	prepared       imageagent.StagingManifest
	ensured        imageagent.StagingManifest
	onFinalize     func()
	onProgress     func(int)
	progressCalls  int
}

func (*recordingArtifactStore) PublicURL(key string) string { return "https://cdn.example.test/" + key }

func (s *recordingArtifactStore) PrepareSlotArtifacts(input objectstore.PrepareSlotArtifactsInput) (objectstore.PreparedSlotArtifacts, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.prepareCalls++
	if len(input.Assets) != 1 || len(input.Assets[0].Bytes) == 0 {
		return objectstore.PreparedSlotArtifacts{}, imageagent.ErrValidation
	}
	sum := sha256.Sum256(input.Assets[0].Bytes)
	hash := hex.EncodeToString(sum[:])
	ownerKey, err := imageagent.ArtifactOwnerKey(input.Identity.OwnerUserID)
	if err != nil {
		return objectstore.PreparedSlotArtifacts{}, imageagent.ErrValidation
	}
	s.prepared = imageagent.StagingManifest{Assets: []imageagent.StagedAssetRef{{
		ObjectKey: fmt.Sprintf("image-agent/staging/%s/%s/%s/%d/%s/%d/0-%s.png", input.Identity.TenantID, ownerKey, input.Identity.RunID, input.Identity.PlanRevision, input.Identity.SlotID, input.Identity.Attempt, hash),
		SHA256:    hash, SizeBytes: int64(len(input.Assets[0].Bytes)), ContentType: input.Assets[0].ContentType,
		Width: input.Assets[0].Width, Height: input.Assets[0].Height, SourceAssetID: input.Assets[0].SourceAssetID,
		Operations: append([]string(nil), input.Assets[0].Operations...), ProviderReceiptID: input.Assets[0].ProviderReceiptID,
	}}}
	return objectstore.PreparedSlotArtifacts{Manifest: s.prepared}, nil
}

func (s *recordingArtifactStore) PreserveSlotArtifacts(context.Context, imageagent.SlotExternalEffectIdentity, objectstore.PreparedSlotArtifacts) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	index := s.preserveCalls
	s.preserveCalls++
	if index < len(s.preserveErrors) {
		return s.preserveErrors[index]
	}
	return s.preserveError
}

func (s *recordingArtifactStore) PreserveCalls() int {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.preserveCalls
}

type cancellationObservingArtifactStore struct {
	*recordingArtifactStore
	mu                          sync.Mutex
	preserveSawCancelledContext bool
	ensureSawCancelledContext   bool
	finalizeSawCancelledContext bool
	onEnsure                    func()
}

func (s *cancellationObservingArtifactStore) PreserveSlotArtifacts(ctx context.Context, identity imageagent.SlotExternalEffectIdentity, prepared objectstore.PreparedSlotArtifacts) error {
	if ctx.Err() != nil {
		s.mu.Lock()
		s.preserveSawCancelledContext = true
		s.mu.Unlock()
	}
	return s.recordingArtifactStore.PreserveSlotArtifacts(ctx, identity, prepared)
}

func (s *cancellationObservingArtifactStore) EnsureStaged(ctx context.Context, prepared objectstore.PreparedSlotArtifacts) error {
	if s.onEnsure != nil {
		s.onEnsure()
	}
	if ctx.Err() != nil {
		s.mu.Lock()
		s.ensureSawCancelledContext = true
		s.mu.Unlock()
		return context.Canceled
	}
	return s.recordingArtifactStore.EnsureStaged(ctx, prepared)
}

func (s *cancellationObservingArtifactStore) FinalizeWithProgress(ctx context.Context, manifest imageagent.StagingManifest, progress func(context.Context, int) error) (imageagent.FinalManifest, error) {
	if ctx.Err() != nil {
		s.mu.Lock()
		s.finalizeSawCancelledContext = true
		s.mu.Unlock()
	}
	return s.recordingArtifactStore.FinalizeWithProgress(ctx, manifest, progress)
}

func (s *cancellationObservingArtifactStore) PreserveSawCancelledContext() bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.preserveSawCancelledContext
}

func (s *cancellationObservingArtifactStore) EnsureSawCancelledContext() bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.ensureSawCancelledContext
}

func (s *cancellationObservingArtifactStore) FinalizeSawCancelledContext() bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.finalizeSawCancelledContext
}

func (s *recordingArtifactStore) RecoverSlotArtifacts(_ context.Context, _ imageagent.SlotExternalEffectIdentity, expected imageagent.StagingManifest) (objectstore.PreparedSlotArtifacts, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.recoverError != nil {
		return objectstore.PreparedSlotArtifacts{}, s.recoverError
	}
	if len(expected.Assets) == 0 {
		return objectstore.PreparedSlotArtifacts{}, objectstore.ErrArtifactUnavailable
	}
	return objectstore.PreparedSlotArtifacts{Manifest: expected}, nil
}

func (s *recordingArtifactStore) EnsureStaged(_ context.Context, prepared objectstore.PreparedSlotArtifacts) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.ensured = prepared.Manifest
	index := s.ensureCalls
	s.ensureCalls++
	if index < len(s.ensureErrors) {
		return s.ensureErrors[index]
	}
	return nil
}

func (s *recordingArtifactStore) Finalize(_ context.Context, manifest imageagent.StagingManifest) (imageagent.FinalManifest, error) {
	return s.FinalizeWithProgress(context.Background(), manifest, nil)
}

func (s *recordingArtifactStore) FinalizeWithProgress(ctx context.Context, manifest imageagent.StagingManifest, progress func(context.Context, int) error) (imageagent.FinalManifest, error) {
	s.mu.Lock()
	s.finalizeCalls++
	err := s.finalizeError
	hook := s.onFinalize
	s.mu.Unlock()
	if hook != nil {
		hook()
	}
	if err != nil {
		return imageagent.FinalManifest{}, err
	}
	if progress != nil {
		for index := range manifest.Assets {
			if progressErr := progress(ctx, index); progressErr != nil {
				return imageagent.FinalManifest{}, progressErr
			}
			s.mu.Lock()
			s.progressCalls++
			hook := s.onProgress
			s.mu.Unlock()
			if hook != nil {
				hook(index)
			}
		}
	}
	return v3FinalManifest(manifest), nil
}

func (s *recordingArtifactStore) PrepareCalls() int {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.prepareCalls
}
func (s *recordingArtifactStore) EnsureCalls() int {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.ensureCalls
}
func (s *recordingArtifactStore) FinalizeCalls() int {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.finalizeCalls
}
func (s *recordingArtifactStore) ProgressCalls() int {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.progressCalls
}
func (s *recordingArtifactStore) EnsuredManifest() imageagent.StagingManifest {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.ensured
}

type lostResponseV3Repository struct {
	imageagent.SlotExternalEffectV3Repository
	mu                               sync.Mutex
	losePreparation                  bool
	loseStagedCommit                 bool
	loseClaim                        bool
	loseCompletion                   bool
	rejectCancelledGet               bool
	onLostClaim                      func()
	onLostCompletion                 func()
	claimDeadline                    time.Time
	completionDeadline               time.Time
	reconciliationDeadlines          []time.Time
	reconciliationGetSawCancelledCtx bool
	renewCalls                       int
}

type finalizationDeadlineObservingV3Repository struct {
	imageagent.SlotExternalEffectV3Repository
	mu                 sync.Mutex
	prepareDeadline    time.Time
	claimDeadline      time.Time
	completionDeadline time.Time
}

type delayedTakeoverV3Repository struct {
	imageagent.SlotExternalEffectV3Repository
	mu              sync.Mutex
	reserveFailures int
	owners          []string
	claims          []imageagent.PublicationClaim
	acquired        []bool
	completionCalls int
}

func (r *delayedTakeoverV3Repository) ReserveSlotProviderV3(ctx context.Context, reservation imageagent.SlotEffectV3Reservation) (imageagent.SlotEffectV3Attempt, bool, error) {
	r.mu.Lock()
	if r.reserveFailures > 0 {
		r.reserveFailures--
		r.mu.Unlock()
		return imageagent.SlotEffectV3Attempt{}, false, errors.New("transient repository read failure")
	}
	r.mu.Unlock()
	return r.SlotExternalEffectV3Repository.ReserveSlotProviderV3(ctx, reservation)
}

func (r *delayedTakeoverV3Repository) ClaimSlotPublicationV3(ctx context.Context, request imageagent.PublicationClaimRequest) (imageagent.SlotEffectV3Attempt, imageagent.PublicationClaim, bool, error) {
	attempt, claim, acquired, err := r.SlotExternalEffectV3Repository.ClaimSlotPublicationV3(ctx, request)
	if err == nil {
		r.mu.Lock()
		r.owners = append(r.owners, request.Owner)
		r.claims = append(r.claims, claim)
		r.acquired = append(r.acquired, acquired)
		r.mu.Unlock()
	}
	return attempt, claim, acquired, err
}

func (r *delayedTakeoverV3Repository) CompleteSlotPublicationV3(ctx context.Context, completion imageagent.PublicationCompletion) (imageagent.SlotEffectV3Attempt, error) {
	r.mu.Lock()
	r.completionCalls++
	r.mu.Unlock()
	return r.SlotExternalEffectV3Repository.CompleteSlotPublicationV3(ctx, completion)
}

func (r *delayedTakeoverV3Repository) ClaimHistory() ([]string, []imageagent.PublicationClaim, []bool) {
	r.mu.Lock()
	defer r.mu.Unlock()
	return append([]string(nil), r.owners...), append([]imageagent.PublicationClaim(nil), r.claims...), append([]bool(nil), r.acquired...)
}

func (r *delayedTakeoverV3Repository) CompletionCalls() int {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.completionCalls
}

type lostPublicationResponseArtifactStore struct {
	*recordingArtifactStore
	mu                sync.Mutex
	loseFirstResponse bool
}

func (s *lostPublicationResponseArtifactStore) FinalizeWithProgress(ctx context.Context, manifest imageagent.StagingManifest, progress func(context.Context, int) error) (imageagent.FinalManifest, error) {
	final, err := s.recordingArtifactStore.FinalizeWithProgress(ctx, manifest, progress)
	if err != nil {
		return final, err
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.loseFirstResponse {
		s.loseFirstResponse = false
		return imageagent.FinalManifest{}, errors.New("publication response lost after deterministic finalize")
	}
	return final, nil
}

type failOnceStagedCommitRepository struct {
	imageagent.SlotExternalEffectV3Repository
	fail bool
}

func (r *failOnceStagedCommitRepository) CommitSlotStagedV3(ctx context.Context, reservation imageagent.SlotEffectV3Reservation, fingerprint string) (imageagent.SlotEffectV3Attempt, error) {
	if r.fail {
		r.fail = false
		return imageagent.SlotEffectV3Attempt{}, errors.New("staged commit unavailable before write")
	}
	return r.SlotExternalEffectV3Repository.CommitSlotStagedV3(ctx, reservation, fingerprint)
}

type failOnceCompletionRepository struct {
	imageagent.SlotExternalEffectV3Repository
	fail bool
}

func (r *failOnceCompletionRepository) CompleteSlotPublicationV3(ctx context.Context, completion imageagent.PublicationCompletion) (imageagent.SlotEffectV3Attempt, error) {
	if r.fail {
		r.fail = false
		return imageagent.SlotEffectV3Attempt{}, errors.New("completion unavailable before write")
	}
	return r.SlotExternalEffectV3Repository.CompleteSlotPublicationV3(ctx, completion)
}

type statefulActivityS3API struct {
	objects                map[string]activityS3Object
	putCalls               int
	headCalls              int
	copyCalls              int
	failPutCall            int
	loseNextPutAfterWrite  bool
	loseNextCopyAfterWrite bool
	blockHead              bool
	headDeadline           time.Time
}

type activityS3Object struct {
	data          []byte
	contentType   string
	contentLength int64
	metadata      map[string]string
	checksumSHA   string
}

func (f *statefulActivityS3API) PutObject(_ context.Context, input *s3.PutObjectInput, _ ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	f.putCalls++
	if f.failPutCall == f.putCalls {
		return nil, errors.New("put failed before write")
	}
	f.savePut(input)
	if f.loseNextPutAfterWrite {
		f.loseNextPutAfterWrite = false
		return nil, errors.New("put response lost after write")
	}
	return &s3.PutObjectOutput{}, nil
}

func (f *statefulActivityS3API) HeadObject(ctx context.Context, input *s3.HeadObjectInput, _ ...func(*s3.Options)) (*s3.HeadObjectOutput, error) {
	f.headCalls++
	if f.blockHead {
		deadline, ok := ctx.Deadline()
		if !ok {
			return nil, errors.New("blocking SDK HEAD call has no deadline")
		}
		f.headDeadline = deadline
		<-ctx.Done()
		return nil, ctx.Err()
	}
	object, ok := f.objects[aws.ToString(input.Key)]
	if !ok {
		return nil, &types.NotFound{}
	}
	return &s3.HeadObjectOutput{ContentType: aws.String(object.contentType), ContentLength: aws.Int64(object.contentLength), Metadata: object.metadata, ChecksumSHA256: aws.String(object.checksumSHA)}, nil
}

func (f *statefulActivityS3API) GetObject(_ context.Context, input *s3.GetObjectInput, _ ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	object, ok := f.objects[aws.ToString(input.Key)]
	if !ok {
		return nil, &types.NoSuchKey{}
	}
	return &s3.GetObjectOutput{
		Body: io.NopCloser(bytes.NewReader(object.data)), ContentType: aws.String(object.contentType),
		ContentLength: aws.Int64(object.contentLength), Metadata: object.metadata,
		ChecksumSHA256: aws.String(object.checksumSHA),
	}, nil
}

func (f *statefulActivityS3API) CopyObject(_ context.Context, input *s3.CopyObjectInput, _ ...func(*s3.Options)) (*s3.CopyObjectOutput, error) {
	f.copyCalls++
	f.saveCopy(input)
	if f.loseNextCopyAfterWrite {
		f.loseNextCopyAfterWrite = false
		return nil, errors.New("copy response lost after write")
	}
	return &s3.CopyObjectOutput{}, nil
}

func (f *statefulActivityS3API) DeleteObject(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) (*s3.DeleteObjectOutput, error) {
	return nil, errors.New("not implemented")
}

func (f *statefulActivityS3API) savePut(input *s3.PutObjectInput) {
	metadata := make(map[string]string, len(input.Metadata))
	for key, value := range input.Metadata {
		metadata[key] = value
	}
	data, _ := io.ReadAll(input.Body)
	f.objects[aws.ToString(input.Key)] = activityS3Object{data: data, contentType: aws.ToString(input.ContentType), contentLength: aws.ToInt64(input.ContentLength), metadata: metadata, checksumSHA: aws.ToString(input.ChecksumSHA256)}
}

func (f *statefulActivityS3API) saveCopy(input *s3.CopyObjectInput) {
	if _, exists := f.objects[aws.ToString(input.Key)]; exists {
		return
	}
	source := strings.TrimPrefix(aws.ToString(input.CopySource), "assets/")
	object, ok := f.objects[source]
	if !ok {
		return
	}
	object.contentType = aws.ToString(input.ContentType)
	object.metadata = make(map[string]string, len(input.Metadata))
	for key, value := range input.Metadata {
		object.metadata[key] = value
	}
	f.objects[aws.ToString(input.Key)] = object
}

func (r *lostResponseV3Repository) PrepareSlotStagingV3(ctx context.Context, reservation imageagent.SlotEffectV3Reservation, manifest imageagent.StagingManifest) (imageagent.SlotEffectV3Attempt, error) {
	result, err := r.SlotExternalEffectV3Repository.PrepareSlotStagingV3(ctx, reservation, manifest)
	r.mu.Lock()
	defer r.mu.Unlock()
	if err == nil && r.losePreparation {
		r.losePreparation = false
		return imageagent.SlotEffectV3Attempt{}, errors.New("lost staging preparation response")
	}
	return result, err
}

func (r *lostResponseV3Repository) ClaimSlotPublicationV3(ctx context.Context, request imageagent.PublicationClaimRequest) (imageagent.SlotEffectV3Attempt, imageagent.PublicationClaim, bool, error) {
	deadline, _ := ctx.Deadline()
	result, claim, claimed, err := r.SlotExternalEffectV3Repository.ClaimSlotPublicationV3(ctx, request)
	r.mu.Lock()
	r.claimDeadline = deadline
	if err == nil && r.loseClaim {
		r.loseClaim = false
		onLostClaim := r.onLostClaim
		r.mu.Unlock()
		if onLostClaim != nil {
			onLostClaim()
		}
		return imageagent.SlotEffectV3Attempt{}, imageagent.PublicationClaim{}, false, errors.New("lost publication claim response")
	}
	r.mu.Unlock()
	return result, claim, claimed, err
}

func (r *lostResponseV3Repository) GetSlotExternalEffectV3(ctx context.Context, identity imageagent.SlotExternalEffectIdentity) (imageagent.SlotEffectV3Attempt, error) {
	r.mu.Lock()
	rejectCancelled := r.rejectCancelledGet && ctx.Err() != nil
	if rejectCancelled {
		r.reconciliationGetSawCancelledCtx = true
	}
	if deadline, ok := ctx.Deadline(); ok {
		r.reconciliationDeadlines = append(r.reconciliationDeadlines, deadline)
	}
	r.mu.Unlock()
	if rejectCancelled {
		return imageagent.SlotEffectV3Attempt{}, ctx.Err()
	}
	return r.SlotExternalEffectV3Repository.GetSlotExternalEffectV3(ctx, identity)
}

type phaseOverrideV3Repository struct {
	imageagent.SlotExternalEffectV3Repository
	phase imageagent.SlotEffectV3Phase
}

type attemptOverrideV3Repository struct {
	imageagent.SlotExternalEffectV3Repository
	mutate func(*imageagent.SlotEffectV3Attempt)
}

func (r *attemptOverrideV3Repository) ReserveSlotProviderV3(ctx context.Context, reservation imageagent.SlotEffectV3Reservation) (imageagent.SlotEffectV3Attempt, bool, error) {
	attempt, claimed, err := r.SlotExternalEffectV3Repository.ReserveSlotProviderV3(ctx, reservation)
	if err == nil {
		r.mutate(&attempt)
	}
	return attempt, claimed, err
}

func (r *phaseOverrideV3Repository) ReserveSlotProviderV3(ctx context.Context, reservation imageagent.SlotEffectV3Reservation) (imageagent.SlotEffectV3Attempt, bool, error) {
	attempt, _, err := r.SlotExternalEffectV3Repository.ReserveSlotProviderV3(ctx, reservation)
	attempt.Phase = r.phase
	return attempt, false, err
}

func (r *lostResponseV3Repository) CommitSlotStagedV3(ctx context.Context, reservation imageagent.SlotEffectV3Reservation, fingerprint string) (imageagent.SlotEffectV3Attempt, error) {
	result, err := r.SlotExternalEffectV3Repository.CommitSlotStagedV3(ctx, reservation, fingerprint)
	r.mu.Lock()
	defer r.mu.Unlock()
	if err == nil && r.loseStagedCommit {
		r.loseStagedCommit = false
		return imageagent.SlotEffectV3Attempt{}, errors.New("lost staged commit response")
	}
	return result, err
}

func (r *lostResponseV3Repository) RenewSlotPublicationV3(ctx context.Context, renewal imageagent.PublicationLeaseRenewal) (imageagent.PublicationClaim, error) {
	r.mu.Lock()
	r.renewCalls++
	r.mu.Unlock()
	return r.SlotExternalEffectV3Repository.RenewSlotPublicationV3(ctx, renewal)
}

func (r *lostResponseV3Repository) CompleteSlotPublicationV3(ctx context.Context, completion imageagent.PublicationCompletion) (imageagent.SlotEffectV3Attempt, error) {
	deadline, _ := ctx.Deadline()
	result, err := r.SlotExternalEffectV3Repository.CompleteSlotPublicationV3(ctx, completion)
	r.mu.Lock()
	r.completionDeadline = deadline
	if err == nil && r.loseCompletion {
		r.loseCompletion = false
		onLostCompletion := r.onLostCompletion
		r.mu.Unlock()
		if onLostCompletion != nil {
			onLostCompletion()
		}
		return imageagent.SlotEffectV3Attempt{}, errors.New("lost publication completion response")
	}
	r.mu.Unlock()
	return result, err
}

func (r *lostResponseV3Repository) ReconciliationGetSawCancelledContext() bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.reconciliationGetSawCancelledCtx
}

func (r *lostResponseV3Repository) PublicationReconciliationDeadlines(claim bool) (time.Time, time.Time) {
	r.mu.Lock()
	defer r.mu.Unlock()
	operationDeadline := r.completionDeadline
	if claim {
		operationDeadline = r.claimDeadline
	}
	if len(r.reconciliationDeadlines) == 0 {
		return operationDeadline, time.Time{}
	}
	return operationDeadline, r.reconciliationDeadlines[len(r.reconciliationDeadlines)-1]
}

func (r *finalizationDeadlineObservingV3Repository) PrepareSlotStagingV3(ctx context.Context, reservation imageagent.SlotEffectV3Reservation, manifest imageagent.StagingManifest) (imageagent.SlotEffectV3Attempt, error) {
	deadline, _ := ctx.Deadline()
	r.mu.Lock()
	r.prepareDeadline = deadline
	r.mu.Unlock()
	return r.SlotExternalEffectV3Repository.PrepareSlotStagingV3(ctx, reservation, manifest)
}

func (r *finalizationDeadlineObservingV3Repository) ClaimSlotPublicationV3(ctx context.Context, request imageagent.PublicationClaimRequest) (imageagent.SlotEffectV3Attempt, imageagent.PublicationClaim, bool, error) {
	deadline, _ := ctx.Deadline()
	r.mu.Lock()
	r.claimDeadline = deadline
	r.mu.Unlock()
	return r.SlotExternalEffectV3Repository.ClaimSlotPublicationV3(ctx, request)
}

func (r *finalizationDeadlineObservingV3Repository) CompleteSlotPublicationV3(ctx context.Context, completion imageagent.PublicationCompletion) (imageagent.SlotEffectV3Attempt, error) {
	deadline, _ := ctx.Deadline()
	r.mu.Lock()
	r.completionDeadline = deadline
	r.mu.Unlock()
	return r.SlotExternalEffectV3Repository.CompleteSlotPublicationV3(ctx, completion)
}

func (r *finalizationDeadlineObservingV3Repository) FinalizationDeadlines() (time.Time, time.Time, time.Time) {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.prepareDeadline, r.claimDeadline, r.completionDeadline
}

func (r *lostResponseV3Repository) RenewCalls() int {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.renewCalls
}

var _ imageagent.StagedSlotExecutor = (*recordingStagedExecutor)(nil)
var _ imageagent.RecoverableSlotExecutor = (*recordingStagedExecutor)(nil)
var _ DurableArtifactStore = (*recordingArtifactStore)(nil)
