apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-processor

resources:
  - ../../base

patches:
  - path: patch-ingress.yaml

images:
  - name: xuwei190/task-processor-product-listing-api
    newTag: latest
  - name: xuwei190/task-processor-listingkit-ui
    newTag: latest
