apiVersion: v1
kind: ConfigMap
metadata:
  name: listingkit-workbench-config
data:
  LISTINGKIT_API_BASE: "http://product-listing-api:8085/api/v1/listing-kits"
  LISTINGKIT_SERVICE_API_BASE: "http://product-listing-api:8085/api/v1"
  NEXT_TELEMETRY_DISABLED: "1"
  TASK_PROCESSOR_ENV: "prod"
  TASK_PROCESSOR_PRODUCTIMAGE_PUBLISHER_PROVIDER: "s3"
  TASK_PROCESSOR_PRODUCTIMAGE_PUBLISHER_PUBLICBASE: "https://oss.shuomiai.com/listingkit-assets"
  TASK_PROCESSOR_PRODUCTIMAGE_PUBLISHER_S3_BUCKET: "listingkit-assets"
  TASK_PROCESSOR_PRODUCTIMAGE_PUBLISHER_S3_REGION: "us-east-1"
  TASK_PROCESSOR_PRODUCTIMAGE_PUBLISHER_S3_ENDPOINT: "https://oss.shuomiai.com"
  TASK_PROCESSOR_PRODUCTIMAGE_PUBLISHER_S3_USEPATHSTYLE: "true"
