apiVersion: v1
kind: ConfigMap
metadata:
  name: listingkit-workbench-config
data:
  LISTINGKIT_API_BASE: "http://product-listing-api:8085/api/v1/listing-kits"
  LISTINGKIT_SERVICE_API_BASE: "http://product-listing-api:8085/api/v1"
  NEXT_TELEMETRY_DISABLED: "1"
  TASK_PROCESSOR_ENV: "prod"
