apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-processor

resources:
  - namespace.yaml
  - configmap.yaml
  - listingkit-ui-auth-config.yaml
  - imgproxy-deployment.yaml
  - imgproxy-service.yaml
  - image-agent-temporal-worker-deployment.yaml
  - image-agent-temporal-worker-v3-deployment.yaml
  - product-listing-api-deployment.yaml
  - product-listing-api-service.yaml
  - shein-login-worker-deployment.yaml
  - listingkit-ui-deployment.yaml
  - listingkit-ui-service.yaml
  - ingress.yaml
