apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-processor

resources:
  - namespace.yaml
  - configmap.yaml
  - product-listing-api-deployment.yaml
  - product-listing-api-service.yaml
  - listingkit-ui-deployment.yaml
  - listingkit-ui-service.yaml
  - traefik-basic-auth-middleware.yaml
  - ingress.yaml
