apiVersion: v1
kind: Service
metadata:
  name: listingkit-ui
  labels:
    app: listingkit-ui
spec:
  selector:
    app: listingkit-ui
  ports:
    - name: http
      port: 3000
      targetPort: http
