apiVersion: v1
kind: Service
metadata:
  name: product-listing-api
  labels:
    app: product-listing-api
spec:
  selector:
    app: product-listing-api
  ports:
    - name: http
      port: 8085
      targetPort: http
