package listingkit

type platformVisualPreviewPayloadBase = platformVisualPresentationBase

func buildPlatformVisualPreviewPayloadBase(base platformVisualPresentationBase) platformVisualPreviewPayloadBase {
	return base
}
