package listingkit

type taskGenerationActionExecuteRequestHandoffModePairingNormalizationPhase struct {
	retryResult *taskGenerationActionExecuteRequestHandoffRetryResultPhase
	queueResult *taskGenerationActionExecuteRequestHandoffQueueResultPhase
}

func buildTaskGenerationActionExecuteRequestHandoffModePairingNormalizationPhase() *taskGenerationActionExecuteRequestHandoffModePairingNormalizationPhase {
	return &taskGenerationActionExecuteRequestHandoffModePairingNormalizationPhase{
		retryResult: buildTaskGenerationActionExecuteRequestHandoffRetryResultPhase(),
		queueResult: buildTaskGenerationActionExecuteRequestHandoffQueueResultPhase(),
	}
}

func (p *taskGenerationActionExecuteRequestHandoffModePairingNormalizationPhase) fromRetryPage(retryPage *GenerationTaskPage) *taskGenerationActionExecuteRequestHandoff {
	return p.retryResult.run(retryPage)
}

func (p *taskGenerationActionExecuteRequestHandoffModePairingNormalizationPhase) fromQueuePage(queuePage *GenerationQueuePage) *taskGenerationActionExecuteRequestHandoff {
	return p.queueResult.run(queuePage)
}
