"use client";
import Link from "next/link";
import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {useWorkbenchContext} from "@/components/providers/workbench-context-provider";
import {ConsolePage,ConsoleState} from "@/components/workbench/console/console-page";
import {ResourceDialog} from "@/components/workbench/resources/resource-dialog";
import {Button} from "@/components/ui/button";
import {Card} from "@/components/ui/card";
import {ecoRequest,ecoPageSchema,ecoPolicy,type EcoScope,type EcoListing} from "@/lib/api/ecoservices";
import {EcoBoundary,EcoPagination,ReadFailure,categories,yuan,toMinor,useEcoCommands,date} from "./shared";
import {FileUpload,FileLinks} from "./files";
import {MerchantOnboarding} from "./merchant";
const applicationStates:Record<string,string>={SUBMITTED:"平台审核中",APPROVED:"平台已批准，待完成渠道准入",REJECTED:"平台已拒绝",ACTIVE:"已开通服务商"};
const lines=(v:string)=>v.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);
export function EcoservicesJoin(){return <EcoBoundary>{scope=><Join key={scope.userId+scope.organizationId} scope={scope}/>}</EcoBoundary>}
function Join({scope}:{scope:EcoScope}){
 const context=useWorkbenchContext(),commands=useEcoCommands(scope),[form,setForm]=useState(false),[formVersion,setFormVersion]=useState<string|undefined>(undefined),[company,setCompany]=useState(""),[registration,setRegistration]=useState(""),[selected,setSelected]=useState<string[]>([]),[regions,setRegions]=useState(""),[files,setFiles]=useState<string[]>([]),[agree,setAgree]=useState(false),[page,setPage]=useState(1),[listing,setListing]=useState<EcoListing|null|"new">(null);
 const canJoin=context.permissions.includes("workbench.ecoservices.join"),canManage=context.permissions.includes("workbench.ecoservices.manage");
 const query=useQuery({queryKey:["ecoservices",scope.userId,scope.organizationId,"applications",context.permissions.join("|")],queryFn:({signal})=>ecoRequest(scope,"applications?page=1&pageSize=20",ecoPageSchema,{signal}),enabled:canJoin,refetchInterval:30000});
 const listings=useQuery({queryKey:["ecoservices",scope.userId,scope.organizationId,"provider-listings",page,context.permissions.join("|")],queryFn:({signal})=>ecoRequest(scope,"provider/listings?page="+page+"&pageSize=20",ecoPageSchema,{signal}),enabled:canManage});
 const application=query.error?undefined:query.data?.applications?.[0],active=application?.state==="ACTIVE",rejected=application?.state==="REJECTED";
 function openApplication(){setFormVersion(rejected?application?.version:undefined);setCompany(application?.companyName??"");setRegistration(application?.registrationNumber??"");setSelected(application?.categories??[]);setRegions(application?.regions.join("\n")??"");setFiles(application?.fileIds??[]);setForm(true)}
 return <ConsolePage className="eco-page" title="申请加入" description="完善机构资料与服务能力，成为生态服务合作伙伴。" breadcrumbs={[{label:"生态服务"},{label:"申请加入"}]} actions={<Link href="/workbench/services/mine">查看我提供的服务 →</Link>}>
  {commands.notice}
  <Card className="eco-join-hero"><div><small>专业服务商合作</small><h2>加入生态服务，拓展业务合作</h2><p>围绕公司注册、商标注册、店铺开通和店铺代运营提供服务，按照约定报价、交付和售后。</p></div><aside><span>当前申请状态</span><strong>{query.isPending&&canJoin?"读取中":application?applicationStates[application.state]:canJoin?"尚未提交":"无申请权限"}</strong><p>资料审核、协议确认与渠道准入分别核实。</p></aside></Card>
  <div className="eco-join-grid"><Card><section><h2>入驻流程</h2><p>按原申请逐步完成，每一步显示真实状态。</p><div className="eco-steps">{[
   ["提交机构资料","机构身份、服务范围和私有证明材料",!!application],
   ["平台审核","审核资质与服务能力，记录审核结果",application?.state==="APPROVED"||active],
   ["协议与渠道准入","确认当前规则，完成微信商户审核、账户验证及签约",active],
   ["发布服务","开通后发布服务，按客户验收结果结算",!!listings.data?.listings?.some(v=>v.state==="PUBLISHED")],
  ].map(([title,description,done],i)=><div className="eco-step" key={i}><span>{i+1}</span><div><strong>{title}</strong><p>{description}</p></div><em>{done?"已完成":"待完成"}</em></div>)}</div><div className="eco-join-terms"><h2>合作与交易规则</h2><p>平台抽佣10%，服务商份额90%；支付手续费由平台承担，不产生个人推广佣金。客户验收后触发渠道分账，受理与到账分别确认。</p><p>服务开始前全额退款；开始后协商金额并由平台审核。已分账交易先回退相应佣金，再原路退款。临期订单保留人工审核，漏处理可能由渠道自动解冻。</p></div></section></Card><Card><section><h2>申请入口</h2><p>请以当前企业提交真实、完整的机构资料。</p><div className="eco-join-entry"><Button disabled={!canJoin||!!application&&!rejected||query.isPending||!!query.error||commands.locked} onClick={openApplication}>{rejected?"修正资料并重新提交 →":"提交机构入驻申请 →"}</Button><Button variant="outline" disabled={!active||!canManage} onClick={()=>setListing("new")}>发布专业服务 →</Button><Link href="/workbench/services/market">查看服务市场 →</Link></div>{application?<><p>{application.companyName}</p><p>{applicationStates[application.state]} · {date(application.updatedAt)}</p>{application.reviewReason?<p>平台审核意见：{application.reviewReason}</p>:null}<p>渠道状态：{application.onboardingState||"尚未进件"}</p></>:null}</section></Card></div>
  {!canJoin?<ConsoleState kind="unavailable" title="当前身份没有申请加入权限"/>:query.error?<ReadFailure error={query.error} retry={()=>void query.refetch()}/>:application?<Card className="eco-table-card" style={{marginTop:20}}><h2>原入驻申请</h2><dl className="eco-detail"><div><p>机构：{application.companyName} · 登记号：{application.registrationNumber}</p><p>服务：{application.categories.map(c=>categories.find(v=>v.id===c)?.name).join("、")}</p><p>地区：{application.regions.join("、")}</p><FileLinks scope={scope} ids={application.fileIds} application/></div></dl>{!application.agreementAccepted&&application.state==="APPROVED"?<div className="eco-form"><label><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/>我代表本企业同意上述交易规则、10%抽佣及人工处理临期订单的约定</label><Button disabled={!agree||commands.locked} onClick={()=>void commands.json("applications/"+application.id+"/agreement",{agreementVersion:ecoPolicy},application.version).catch(()=>undefined)}>确认当前协议</Button></div>:<p>协议：{application.agreementAccepted?"已确认当前规则":"未确认"}</p>}{application.state==="APPROVED"||active?<MerchantOnboarding scope={scope} application={application}/>:null}</Card>:null}
  {canManage&&active?<Card className="eco-table-card" style={{marginTop:20}}><div className="eco-table-heading"><h2>我提供的服务</h2><Button onClick={()=>setListing("new")} disabled={commands.locked}>新增服务</Button></div>{listings.isPending?<ConsoleState kind="loading" title="正在读取服务内容"/>:listings.error?<ReadFailure error={listings.error} retry={()=>void listings.refetch()}/>:listings.data?.listings?.length?<><div className="eco-table-wrap"><table className="eco-table"><thead><tr><th>服务</th><th>参考价</th><th>交付天数</th><th>发布状态</th><th>操作</th></tr></thead><tbody>{listings.data.listings.map(l=><tr key={l.id}><td>{l.title}<small>{categories.find(c=>c.id===l.category)?.name}</small></td><td>{yuan(l.priceMinor)}</td><td>{l.deliveryDays} 天</td><td>{l.state==="PUBLISHED"?"已发布":"草稿"}</td><td><div className="eco-actions"><Button variant="outline" disabled={commands.locked} onClick={()=>setListing(l)}>编辑</Button>{l.state==="DRAFT"?<Button disabled={commands.locked} onClick={()=>void commands.json("provider/listings/"+l.id+"/publish",{},l.version).catch(()=>undefined)}>发布</Button>:null}</div></td></tr>)}</tbody></table></div><EcoPagination page={page} total={listings.data.total} onPage={setPage}/></>:<ConsoleState kind="empty" title="尚未发布服务"/>}</Card>:null}
  {form?<ResourceDialog title={formVersion?"修正机构入驻资料":"提交机构入驻申请"} onClose={()=>setForm(false)} locked={commands.locked}><div className="eco-detail"><form onSubmit={e=>{e.preventDefault();void commands.json("applications",{companyName:company,registrationNumber:registration,categories:selected,regions:lines(regions),fileIds:files},formVersion).then(()=>setForm(false)).catch(()=>undefined)}}><fieldset disabled={commands.locked}><label>机构法定名称<input required maxLength={256} value={company} onChange={e=>setCompany(e.target.value)}/></label><label>统一社会信用代码或登记号<input required maxLength={128} value={registration} onChange={e=>setRegistration(e.target.value)}/></label><div className="eco-checkboxes">{categories.map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,c.id]:v.filter(x=>x!==c.id))}/>{c.name}</label>)}</div><label>服务地区（每行一项）<textarea required maxLength={3840} value={regions} onChange={e=>setRegions(e.target.value)}/></label><p>请至少提供一张清晰的营业执照 JPG 或 PNG（不超过2 MiB），渠道进件将使用已审核的该材料。</p><FileUpload commands={commands} path="applications/files" ids={files} onFiles={setFiles} maxBytes={2*1024*1024} accept=".png,.jpg,.jpeg"/>{formVersion?<><p>更正资料将生成原申请的新版本，须由平台重新审核；原审核记录和材料保留。</p><Button type="button" variant="outline" disabled={!files.length} onClick={()=>setFiles([])}>清空当前材料选择</Button></>:null}<Button type="submit" disabled={!selected.length||!files.length}>{formVersion?"提交更正版本":"提交原申请"}</Button></fieldset></form>{commands.notice}</div></ResourceDialog>:null}
  {listing?<ListingForm key={listing==="new"?"new":listing.id+listing.version} scope={scope} listing={listing==="new"?undefined:listing} onClose={()=>{setListing(null);void listings.refetch()}}/>:null}
 </ConsolePage>;
}
function ListingForm({scope,listing,onClose}:{scope:EcoScope;listing?:EcoListing;onClose:()=>void}){
 const commands=useEcoCommands(scope),[category,setCategory]=useState(listing?.category??categories[0].id),[title,setTitle]=useState(listing?.title??""),[description,setDescription]=useState(listing?.description??""),[items,setItems]=useState(listing?.items.join("\n")??""),[regions,setRegions]=useState(listing?.regions.join("\n")??""),[platforms,setPlatforms]=useState(listing?.platforms?.join("\n")??""),[amount,setAmount]=useState(listing?yuan(listing.priceMinor).slice(1):""),[days,setDays]=useState(String(listing?.deliveryDays??7));
 return <ResourceDialog title={listing?"编辑服务内容":"新增专业服务"} onClose={onClose} locked={commands.locked}><div className="eco-detail"><form onSubmit={e=>{e.preventDefault();try{void commands.json("provider/listings"+(listing?"/"+listing.id:""),{category,title,description,items:lines(items),regions:lines(regions),platforms:lines(platforms),priceMinor:toMinor(amount),deliveryDays:Number(days)},listing?.version,false,listing?"PUT":"POST").then(onClose).catch(()=>undefined)}catch(err){commands.setMessage(err instanceof Error?err.message:"金额不正确")}}}><fieldset disabled={commands.locked}><label>服务类型<select value={category} onChange={e=>setCategory(e.target.value as typeof category)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>服务名称<input required maxLength={128} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>服务描述<textarea required maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>包含服务（每行一项，最多10项）<textarea required value={items} onChange={e=>setItems(e.target.value)}/></label><label>服务地区（每行一项）<textarea required value={regions} onChange={e=>setRegions(e.target.value)}/></label><label>适用平台（每行一项，可留空）<textarea value={platforms} onChange={e=>setPlatforms(e.target.value)}/></label><label>参考价（元）<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>预计交付天数<input required type="number" min="1" max="180" value={days} onChange={e=>setDays(e.target.value)}/></label><p>交付周期须在本平台获准冻结期限内；修改已发布内容后需要重新发布。</p><Button type="submit">保存服务草稿</Button></fieldset></form>{commands.notice}</div></ResourceDialog>;
}
