"use client";
import {FinancialFacts} from "./financial";
import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {QRCodeSVG} from "qrcode.react";
import {useWorkbenchContext} from "@/components/providers/workbench-context-provider";
import {ResourceDialog} from "@/components/workbench/resources/resource-dialog";
import {ConsoleState} from "@/components/workbench/console/console-page";
import {Button} from "@/components/ui/button";
import {ecoRequest,ecoPageSchema,ecoPolicy,ecoCheckoutSchema,type EcoScope} from "@/lib/api/ecoservices";
import {useEcoCommands,date,yuan,toMinor,serviceStates,financialStates,ReadFailure} from "./shared";
import {FileLinks,FileUpload} from "./files";
export function RequestDetail({scope,id,onClose,admin=false}:{scope:EcoScope;id:string;onClose:()=>void;admin?:boolean}){
 const context=useWorkbenchContext(),commands=useEcoCommands(scope),[amount,setAmount]=useState(""),[content,setContent]=useState(""),[criteria,setCriteria]=useState(""),[days,setDays]=useState("7"),[reason,setReason]=useState(""),[files,setFiles]=useState<string[]>([]),[quoteAgreement,setQuoteAgreement]=useState(""),[deliveryAgreement,setDeliveryAgreement]=useState("");
 const query=useQuery({queryKey:["ecoservices",scope.userId,scope.organizationId,"request",id,admin,context.permissions.join("|")],queryFn:({signal})=>ecoRequest(scope,"requests/"+id,ecoPageSchema,{signal},admin),refetchInterval:15000,enabled:!context.isLoading&&!context.isSwitching&&!context.error&&!context.blockingError});
 const r=query.error?undefined:query.data?.requests?.[0],buyer=!admin&&r?.side==="buyer"&&context.permissions.includes("workbench.ecoservices.purchase"),provider=!admin&&r?.side==="provider"&&context.permissions.includes("workbench.ecoservices.manage"),prefix=provider?"provider/requests/":"requests/";
 const qr=commands.resolved?.intent.output==="checkout"?ecoCheckoutSchema.safeParse(commands.resolved.data):null;
 const action=(name:string,body:unknown={})=>r?commands.json(prefix+r.id+"/"+name,body,r.version,admin).catch(()=>undefined):Promise.resolve();
 function numericAction(name:string,body:Record<string,unknown>){try{void action(name,{...body,amountMinor:toMinor(amount)})}catch(e){commands.setMessage(e instanceof Error?e.message:"金额不正确")}}
 return <ResourceDialog title={r?.title??"服务详情"} onClose={onClose} locked={commands.locked}><div className="eco-detail">
  {commands.notice}
  {query.isPending?<ConsoleState kind="loading" title="正在读取原服务状态"/>:query.error?<ReadFailure error={query.error} retry={()=>void query.refetch()}/>:!r?<ConsoleState kind="empty" title="服务不存在或不属于当前企业"/>:<>
   <dl><dt>服务状态</dt><dd>{serviceStates[r.state]??r.state}</dd><dt>资金状态</dt><dd>{financialStates[r.financialState]??"尚未收款"}</dd><dt>当前身份</dt><dd>{admin?"平台审核":r.side==="buyer"?"客户":"服务商"}</dd><dt>提交时间</dt><dd>{date(r.createdAt)}</dd>{r.fundsExpireAt?<><dt>冻结到期</dt><dd>{date(r.fundsExpireAt)}（到期仍未处理，渠道可能自动解冻）</dd></>:null}</dl>
   {r.financialHold?<p role="status">当前争议或资金核实未结束，开始、交付、验收及后续资金操作暂停。</p>:null}
   {admin&&r.orderId&&r.financialState&&!['CREATED','AWAITING_PAYMENT','CLOSED_UNPAID'].includes(r.financialState)?<FinancialFacts scope={scope} id={r.id} commands={commands}/>:null}
   <section><h3>客户需求</h3><p style={{whiteSpace:"pre-wrap"}}>{r.description}</p><FileLinks scope={scope} ids={r.fileIds??[]} admin={admin}/></section>
   {r.quote?<section><h3>报价 {yuan(r.quote.amountMinor)}</h3><p>预计 {r.quote.deliveryDays} 天 · 报价版本 {r.quote.version}</p><h4>服务范围</h4><p style={{whiteSpace:"pre-wrap"}}>{r.quote.scope}</p><h4>验收条件</h4><p style={{whiteSpace:"pre-wrap"}}>{r.quote.acceptanceCriteria}</p><p>平台抽佣10%，渠道手续费由平台承担；本服务不产生推广佣金。</p></section>:null}
   {provider&&["REQUESTED","QUOTED"].includes(r.state)?<form onSubmit={e=>{e.preventDefault();numericAction("quote",{scope:content,acceptanceCriteria:criteria,deliveryDays:Number(days)})}}><fieldset disabled={commands.locked}><h3>提供成交报价</h3><label>总费用（元）<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>交付天数<input type="number" required min="1" max="180" value={days} onChange={e=>setDays(e.target.value)}/></label><label>具体服务范围<textarea required maxLength={10000} value={content} onChange={e=>setContent(e.target.value)}/></label><label>可检查的验收条件<textarea required maxLength={5000} value={criteria} onChange={e=>setCriteria(e.target.value)}/></label><Button type="submit">保存报价</Button></fieldset></form>:null}
   {buyer&&r.state==="QUOTED"&&r.quote?<fieldset disabled={commands.locked}><label><input type="checkbox" checked={quoteAgreement===r.quote.version} onChange={e=>setQuoteAgreement(e.target.checked?r.quote!.version:"")}/>我同意当前报价及规则：开始前全额退款；开始后协商金额并经平台审核；客户验收后渠道分账；临期由平台人工处理，漏处理可能自动解冻。</label><Button disabled={quoteAgreement!==r.quote.version} onClick={()=>void action("confirm-quote",{quoteVersion:r.quote!.version,policyAccepted:ecoPolicy})}>确认报价并生成订单</Button></fieldset>:null}
   {buyer&&r.state==="ORDER_PENDING"&&r.orderId&&!r.financialHold?<section><p>付款成功并经渠道确认后，服务商才能开始服务。</p><Button disabled={commands.locked} onClick={()=>void commands.execute({path:"orders/"+r.orderId+"/checkout",key:crypto.randomUUID(),body:"{}",output:"checkout"}).catch(()=>undefined)}>获取微信付款码</Button>{qr?.success&&qr.data.orderId===r.orderId?<div className="eco-qr"><QRCodeSVG value={qr.data.codeUrl} size={200}/><p>使用微信扫码支付 {r.quote?yuan(r.quote.amountMinor):""}</p><p>正在定期核实付款状态，扫码后请等待确认。</p></div>:null}</section>:null}
   {buyer&&["REQUESTED","QUOTED","ORDER_PENDING","PAID_READY"].includes(r.state)&&!r.financialHold?<Button variant="outline" disabled={commands.locked} onClick={()=>void action("cancel")}>取消服务{["ORDER_PENDING","PAID_READY"].includes(r.state)?"，已付款则全额原路退款":""}</Button>:null}
   {provider&&r.state==="PAID_READY"&&!r.financialHold?<Button disabled={commands.locked} onClick={()=>void action("start")}>开始服务</Button>:null}
   {r.delivery?<section><h3>交付版本 {r.delivery.version}</h3><p>{date(r.delivery.submittedAt)}</p><p style={{whiteSpace:"pre-wrap"}}>{r.delivery.content}</p><FileLinks scope={scope} ids={r.delivery.fileIds??[]} admin={admin}/>{r.delivery.rejection?<div><h4>客户拒收交付版本 {r.delivery.rejection.deliveryVersion}</h4><p>{date(r.delivery.rejection.rejectedAt)}</p><p style={{whiteSpace:"pre-wrap"}}>{r.delivery.rejection.reason}</p></div>:null}</section>:null}
   {provider&&r.state==="SERVICING"&&!r.financialHold?<form onSubmit={e=>{e.preventDefault();void action("delivery",{content,fileIds:files})}}><fieldset disabled={commands.locked}><label>本次交付说明<textarea required maxLength={10000} value={content} onChange={e=>setContent(e.target.value)}/></label><FileUpload commands={commands} path={prefix+r.id+"/files"} ids={files} onFiles={setFiles}/><Button type="submit">提交交付，等待客户验收</Button></fieldset></form>:null}
   {buyer&&r.state==="AWAITING_ACCEPTANCE"&&r.delivery&&!r.financialHold?<fieldset disabled={commands.locked}><p>请按报价中的验收条件检查本次交付。确认后将触发渠道分账。</p><label><input type="checkbox" checked={deliveryAgreement===r.delivery.version} onChange={e=>setDeliveryAgreement(e.target.checked?r.delivery!.version:"")}/>已检查并确认交付版本 {r.delivery.version} 符合约定</label><Button disabled={deliveryAgreement!==r.delivery.version} onClick={()=>void action("accept",{deliveryVersion:r.delivery!.version})}>确认验收并结算</Button><label>需要服务商修改的问题<textarea maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button variant="outline" disabled={!reason.trim()} onClick={()=>void action("reject",{deliveryVersion:r.delivery!.version,reason})}>拒收本次交付，要求修改</Button></fieldset>:null}
   {r.refund?<section><h3>退款协商 {yuan(r.refund.amountMinor)}</h3><p>{r.refund.reason}</p><p>客户：{r.refund.buyerConfirmed?"已确认":"待确认"} · 服务商：{r.refund.providerConfirmed?"已确认":"待确认"} · {({NEGOTIATING:"协商中",APPROVED:"平台已批准，等待渠道退款",REJECTED:"平台已拒绝",REFUNDED:"退款已确认",FAILED:"渠道退款失败"} as Record<string,string>)[r.refund.state]}</p>{(buyer&&!r.refund.buyerConfirmed||provider&&!r.refund.providerConfirmed)&&r.refund.state==="NEGOTIATING"?<Button disabled={commands.locked} onClick={()=>void action("refund-confirmation",{refundVersion:r.refund!.version})}>同意此退款金额与原因</Button>:null}{admin&&r.refund.state==="NEGOTIATING"&&r.refund.buyerConfirmed&&r.refund.providerConfirmed?<fieldset disabled={commands.locked}><label>平台审核理由<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="eco-actions">{["refund-approve","refund-reject"].map(a=><Button key={a} disabled={!reason.trim()} variant={a==="refund-reject"?"outline":"default"} onClick={()=>void action(a,{refundVersion:r.refund!.version,reason})}>{a==="refund-approve"?"批准原退款金额":"拒绝此退款申请"}</Button>)}</div></fieldset>:null}</section>:null}
   {(buyer||provider)&&["SERVICING","AWAITING_ACCEPTANCE","ACCEPTED"].includes(r.state)&&r.refund?.state!=="APPROVED"?<form onSubmit={e=>{e.preventDefault();numericAction("refund-proposals",{reason})}}><fieldset disabled={commands.locked}><h3>提出退款方案</h3><label>退款金额（元）<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>退款原因<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>对方需确认同一版本，之后由平台审核。已分账的先回退对应佣金，再执行原路退款。</p><Button variant="outline" type="submit">保存退款方案并暂停后续操作</Button></fieldset></form>:null}
   <Button variant="outline" onClick={()=>void query.refetch()}>刷新原服务状态</Button>
  </>}
 </div></ResourceDialog>;
}
