apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shein-listing-secret
  namespace: task-processor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: task-processor-secrets
  target:
    name: shein-listing-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: TASK_PROCESSOR_RABBITMQ_URL
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_RABBITMQ_URL
    - secretKey: TASK_PROCESSOR_OPENAI_API_KEY
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_OPENAI_API_KEY
    - secretKey: TASK_PROCESSOR_OPENAI_MODEL
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_OPENAI_MODEL
    - secretKey: TASK_PROCESSOR_OPENAI_BASE_URL
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_OPENAI_BASE_URL
    - secretKey: TASK_PROCESSOR_AMAZON_REMOTE_API_BASE_URL
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_AMAZON_REMOTE_API_BASE_URL
    - secretKey: TASK_PROCESSOR_REDIS_HOST
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_REDIS_HOST
    - secretKey: TASK_PROCESSOR_REDIS_PORT
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_REDIS_PORT
    - secretKey: TASK_PROCESSOR_REDIS_PASSWORD
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_REDIS_PASSWORD
    - secretKey: TASK_PROCESSOR_REDIS_DB
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_REDIS_DB
    - secretKey: TASK_PROCESSOR_DATABASE_HOST
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_DATABASE_HOST
    - secretKey: TASK_PROCESSOR_DATABASE_PORT
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_DATABASE_PORT
    - secretKey: TASK_PROCESSOR_DATABASE_USER
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_DATABASE_USER
    - secretKey: TASK_PROCESSOR_DATABASE_PASSWORD
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_DATABASE_PASSWORD
    - secretKey: TASK_PROCESSOR_DATABASE_NAME
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_DATABASE_NAME
    - secretKey: TASK_PROCESSOR_DATABASE_MAX_CONNECTIONS
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_DATABASE_MAX_CONNECTIONS
    - secretKey: TASK_PROCESSOR_DATABASE_MAX_IDLE_CONNECTIONS
      remoteRef:
        key: task-processor/prod/shein-listing
        property: TASK_PROCESSOR_DATABASE_MAX_IDLE_CONNECTIONS
