apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-processor

resources:
  - ../../base
  - secret.yaml

images:
  - name: xuwei190/task-processor-shein-listing
    digest: sha256:2e4617a0c381bc8bdf4a5b6e1bb4cc351ac9013a4f9299057e6ea0201786bc08

patches:
  - path: patch-deployment.yaml
  - path: patch-hpa.yaml
