apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-processor

resources:
  - ../../base
  - secret.yaml

images:
  - name: xuwei190/task-processor-shein-listing
    newTag: latest

patches:
  - path: patch-deployment.yaml
  - path: patch-hpa.yaml
