apiVersion: apps/v1
kind: Deployment
metadata:
  name: shein-listing
  namespace: task-processor
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: shein-listing
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
