apiVersion: v1
kind: Secret
metadata:
  name: shein-listing-secret
  namespace: task-processor
type: Opaque
stringData:
  TASK_PROCESSOR_MANAGEMENT_BASE_URL: "http://management-api.default.svc.cluster.local:8080"
  TASK_PROCESSOR_MANAGEMENT_CLIENT_ID: "go-listing"
  TASK_PROCESSOR_MANAGEMENT_CLIENT_SECRET: "replace-me"
  TASK_PROCESSOR_MANAGEMENT_TOKEN_URL: "http://management-api.default.svc.cluster.local:8080/admin-api/system/oauth2/token"
  TASK_PROCESSOR_RABBITMQ_URL: "amqp://admin:replace-me@rabbitmq.default.svc.cluster.local:5672/"
  TASK_PROCESSOR_OPENAI_API_KEY: "replace-me"
  TASK_PROCESSOR_OPENAI_MODEL: "gemini-2.5-flash"
  TASK_PROCESSOR_OPENAI_BASE_URL: "https://ai.linkcloudai.com/v1"
  TASK_PROCESSOR_AMAZON_REMOTE_API_BASE_URL: "http://amazon-crawler-api.task-processor.svc.cluster.local:8080"
  TASK_PROCESSOR_REDIS_HOST: "redis-master.default.svc.cluster.local"
  TASK_PROCESSOR_REDIS_PORT: "6379"
  TASK_PROCESSOR_REDIS_PASSWORD: ""
  TASK_PROCESSOR_REDIS_DB: "0"
