apiVersion: v1
kind: Secret
metadata:
  name: shein-listing-secret
  namespace: task-processor
type: Opaque
stringData:
  TASK_PROCESSOR_MANAGEMENT_BASE_URL: "http://yudao-gateway.yudao-cloud.svc.cluster.local:48080"
  TASK_PROCESSOR_MANAGEMENT_CLIENT_ID: "go-listing"
  TASK_PROCESSOR_MANAGEMENT_CLIENT_SECRET: "go-listing-secret"
  TASK_PROCESSOR_MANAGEMENT_TOKEN_URL: "http://yudao-gateway.yudao-cloud.svc.cluster.local:48080/admin-api/system/oauth2/token"
  TASK_PROCESSOR_RABBITMQ_URL: "amqp://admin:RabbitMQ%402026%23Prod@rabbitmq.yudao-cloud.svc.cluster.local:5672/"
  TASK_PROCESSOR_OPENAI_API_KEY: "sk-ctFAGZDOnkWNKfCcAoJ2LEm19xYhXPS92HbXZxTEITVemv8o"
  TASK_PROCESSOR_OPENAI_MODEL: "gemini-2.5-flash-lite"
  TASK_PROCESSOR_OPENAI_BASE_URL: "https://api.gptbest.vip/v1"
  TASK_PROCESSOR_AMAZON_REMOTE_API_BASE_URL: "http://amazon-crawler-external-lb.task-processor.svc.cluster.local:8080"
  TASK_PROCESSOR_REDIS_HOST: "redis-master.yudao-cloud.svc.cluster.local"
  TASK_PROCESSOR_REDIS_PORT: "6379"
  TASK_PROCESSOR_REDIS_PASSWORD: "8idSRwLEauYs0taf_MYEDaV%"
  TASK_PROCESSOR_REDIS_DB: "0"
  TASK_PROCESSOR_DATABASE_HOST: "postgresql.yudao-cloud.svc.cluster.local"
  TASK_PROCESSOR_DATABASE_PORT: "5432"
  TASK_PROCESSOR_DATABASE_USER: "postgres"
  TASK_PROCESSOR_DATABASE_PASSWORD: "postgresql2026Zone$"
  TASK_PROCESSOR_DATABASE_NAME: "ruoyi-vue-pro"
  TASK_PROCESSOR_DATABASE_MAX_CONNECTIONS: "10"
  TASK_PROCESSOR_DATABASE_MAX_IDLE_CONNECTIONS: "5"
