services:
  task:
    image: xuwei190/task-processor-task:${TASK_IMAGE_TAG:-8324377}
    container_name: task
    restart: unless-stopped
    env_file:
      - /app/task/.env
    environment:
      TASK_PROCESSOR_ENV: prod
    volumes:
      - /app/task/config:/app/config
      - /app/task/logs:/app/logs
      - /app/task/tmp:/app/tmp
      - /app/task/chrome:/app/chrome
    ports:
      - "8081:8081"
      - "8082:8082"
