services:
  amazon-crawler-api:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.amazon-crawler-api
    image: xuwei190/task-processor-amazon-crawler-api:latest
    container_name: amazon-crawler-api
    restart: unless-stopped
    env_file:
      - /app/amazon-crawler-api/.env
    environment:
      TASK_PROCESSOR_ENV: prod
      TASK_PROCESSOR_REDIS_HOST: redis
      TASK_PROCESSOR_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    volumes:
      - /app/amazon-crawler-api/config:/app/config
      - /app/amazon-crawler-api/logs:/app/logs
      - /app/amazon-crawler-api/tmp:/app/tmp
      - /app/amazon-crawler-api/chrome:/app/chrome
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: amazon-crawler-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - /app/amazon-crawler-api/redis:/data
