services:
  amazon-crawler-api:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.amazon-crawler-api
    image: xuwei190/task-processor-amazon-crawler-api:latest
    container_name: amazon-crawler-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TASK_PROCESSOR_ENV=prod
      - TASK_PROCESSOR_REDIS_HOST=${REDIS_HOST:-127.0.0.1}
      - TASK_PROCESSOR_REDIS_PORT=${REDIS_PORT:-6379}
      - TASK_PROCESSOR_REDIS_PASSWORD=${REDIS_PASSWORD:-}
    ports:
      - "${HOST_PORT:-8080}:8080"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./tmp:/app/tmp
      - ./chrome:/app/chrome
