apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-processor

resources:
  - listingkit-api-release-role.yaml
  - listingkit-api-release-rolebinding.yaml
  - listingkit-ui-release-role.yaml
  - listingkit-ui-release-rolebinding.yaml
  - listingkit-release-gate-runners.yaml
