"use client";
import Link from "next/link";
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { z } from "zod";
import { useWorkbenchContext } from "@/components/providers/workbench-context-provider";
import { ConsolePage, ConsoleState } from "../console/console-page";
import { useResourcePending } from "../resources/resource-pending";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { cockpitRequest, cockpitErrorText, CockpitError, type CockpitScope } from "@/lib/api/operations-cockpit";
import { cockpitCapabilities, cockpitDetail, cockpitEndpoint, cockpitGoal, cockpitGoals, cockpitMatrix, cockpitRecord, cockpitReceipt, cockpitRules, centsInput, moneyCents, moneyText, ratioText, type CockpitCapabilities, type CockpitGoalConfig, type CockpitRecord, type CockpitRule } from "@/lib/contracts/operations-cockpit";
import styles from "./cockpit.module.css";

type Mode = "goals" | "settings" | "stores" | "alerts" | "advice";
type Period = { startDate: string; endDate: string };
const names = { goals: "目标管理", settings: "设置经营目标", stores: "店铺矩阵", alerts: "经营预警", advice: "经营建议" };
const stateNames: Record<string, string> = { loss: "亏损", break_even: "收支平衡", recorded_complete: "录入完整", data_incomplete: "数据不完整", normal: "正常", attention: "需关注", abnormal: "异常", not_started: "尚未开始", pending_data: "待完整数据" };
const fields = ["revenue", "refunds", "procurement", "logistics", "platform", "advertising", "other"] as const;
const labels = ["销售收入（退款前）", "退款", "本期已销售商品采购成本", "物流成本", "平台费用", "广告成本", "其他成本"];
function addDays(day: string, count: number) { const d = new Date(day + "T00:00:00Z"); d.setUTCDate(d.getUTCDate() + count); return d.toISOString().slice(0, 10); }
function lastPeriod(today: string): Period { return { startDate: addDays(today, -7), endDate: addDays(today, -1) }; }
function naturalPeriod(day: string, frequency: CockpitGoalConfig["frequency"]): Period {
 const d = new Date(day + "T00:00:00Z");
 if (frequency === "day") return { startDate: day, endDate: day };
 if (frequency === "week") { const startDate = addDays(day, -(d.getUTCDay() + 6) % 7); return { startDate, endDate: addDays(startDate, 6) }; }
 const startDate = day.slice(0, 7) + "-01", next = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + 1, 1)).toISOString().slice(0, 10); return { startDate, endDate: addDays(next, -1) };
}
function periodQuery(p: Period) { return new URLSearchParams(p).toString(); }
function linkedPeriod(today:string):Period {
 const query=typeof window==="undefined"?new URLSearchParams():new URLSearchParams(window.location.search),startDate=query.get("startDate")??"",endDate=query.get("endDate")??"";
 if(z.iso.date().safeParse(startDate).success && z.iso.date().safeParse(endDate).success && startDate<=endDate && endDate<today && (Date.parse(endDate)-Date.parse(startDate))/86400000<366)return {startDate,endDate};
 return lastPeriod(today);
}
const intentSchema = z.strictObject({ key: z.uuid(), path: z.enum(["facts", "goals", "goals/restore"]), body: z.string().max(16384) }).refine(v => { try { return cockpitEndpoint(v.path, "POST")?.input?.safeParse(JSON.parse(v.body)).success === true; } catch { return false; } });
type Intent = z.infer<typeof intentSchema>;
function useCommands(scope: CockpitScope) {
 const context = useWorkbenchContext(), live = useRef(context), mounted = useRef(true), running = useRef(false), client = useQueryClient(), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [lastSaved, setLastSaved] = useState<z.infer<typeof cockpitReceipt> | null>(null);
 // Read the render's current identity before accepting a late result.
 useEffect(() => {live.current = context;},[context]);
 useEffect(() => {mounted.current=true;return () => { mounted.current = false; };}, []);
 const pending = useResourcePending({ expectedUserId: scope.userId, expectedOrganizationId: scope.organizationId }, ["operations-cockpit"], intentSchema, { maxLength: 32768 });
 useEffect(() => context.registerOrganizationSwitchGuard(() => !running.current && !pending.error), [context, pending.error]);
 function stillCurrent() { const c = live.current; return mounted.current && c.user?.id === scope.userId && c.effectiveOrganization?.id === scope.organizationId && !c.error && !c.blockingError && !c.isLoading && !c.isSwitching; }
 async function execute(intent: Intent) {
  if (!stillCurrent() || running.current || !pending.ready) return false;
  try {
   pending.persist(intentSchema.parse(intent)); running.current = true; setBusy(true); setMessage("");
   const receipt = await cockpitRequest(scope, intent.path, cockpitReceipt, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": intent.key }, body: intent.body });
   const body = JSON.parse(intent.body); if (receipt.commandId !== intent.key || receipt.id !== body.id) throw new CockpitError("OUTCOME_UNKNOWN");
   pending.clear(intent);
   if (!stillCurrent()) return false;
   await client.invalidateQueries({ queryKey: ["operations-cockpit", scope.userId, scope.organizationId] });
   if (!stillCurrent()) return false; setLastSaved(receipt); setMessage(`已保存，当前版本 V${receipt.revision}。`); return true;
  } catch (error) {
   if (error instanceof CockpitError && ["INVALID_REQUEST", "PERIOD_OVERLAP", "REVISION_MISMATCH", "AMOUNT_OUT_OF_RANGE"].includes(error.code)) { try { pending.clear(intent); } catch {} }
   if (stillCurrent()) setMessage(cockpitErrorText(error)); return false;
  } finally { running.current = false; if (mounted.current) setBusy(false); }
 }
 return { busy, message, pending, lastSaved, execute, save: (path: Intent["path"], body: unknown) => execute({ path, key: crypto.randomUUID(), body: JSON.stringify(body) }) };
}
type Commands = ReturnType<typeof useCommands>;
function Panel({ title, children, className = "" }: { title: string; children: ReactNode; className?: string }) { return <Card className={`${styles.panel} ${className}`}><h2>{title}</h2>{children}</Card>; }
function Badge({ state }: { state: string }) { return <span className={styles.badge} data-state={state}>{stateNames[state] ?? state}</span>; }
function Empty({ title, children }: { title: string; children?: ReactNode }) { return <ConsoleState kind="empty" title={title}>{children}</ConsoleState>; }
export function CockpitPage({ mode }: { mode: Mode }) {
 const context = useWorkbenchContext();
 if (context.isLoading || context.isSwitching) return <ConsoleState kind="loading" title="正在确认当前企业" />;
 if (context.error || context.blockingError) return <ConsoleState kind="error" title="身份上下文不可用"><Button onClick={() => void context.retry()}>重新确认</Button></ConsoleState>;
 if (!context.user || !context.effectiveOrganization || context.selectionRequired) return <ConsoleState kind="unavailable" title="请先选择企业" />;
 const moduleName = mode === "settings" ? "goals" : mode;
 if (!context.operationsCockpitAvailable) return <ConsoleState kind="unavailable" title="当前实例尚未开放运营驾驶舱" />;
 if (!context.permissions.includes(`workbench.cockpit.${moduleName}.read`)) return <ConsoleState kind="unavailable" title="请申请该经营模块的访问权限" />;
 const scope = { userId: context.user.id, organizationId: context.effectiveOrganization.id };
 return <ScopedCockpit key={JSON.stringify([scope, mode, context.permissions])} mode={mode} scope={scope} />;
}
function ScopedCockpit({ mode, scope }: { mode: Mode; scope: CockpitScope }) {
 const commands = useCommands(scope), client = useQueryClient();
 const capabilities = useQuery({ queryKey: ["operations-cockpit", scope.userId, scope.organizationId, "capabilities"], queryFn: ({ signal }) => cockpitRequest(scope, "capabilities", cockpitCapabilities, { signal }), retry: false });
 if (capabilities.isPending) return <ConsoleState kind="loading" title="正在读取店铺与当前权限" />;
 if (capabilities.error) return <ConsoleState kind="error" title={cockpitErrorText(capabilities.error)}><Button onClick={() => void capabilities.refetch()}>重新读取</Button></ConsoleState>;
 if (!capabilities.data) return null;
 return <ConsolePage className={styles.cockpit} title={names[mode]} description={mode === "settings" ? "选择经营店铺、目标周期和利润目标，保存后启用。金额均为人民币。" : "基于已保存的人工经营收入与成本查看经营表现。缺少数据时保留待判断状态。"} breadcrumbs={[{ label: "运营驾驶舱" }, { label: names[mode] }]} actions={<Button variant="outline" onClick={() => void client.invalidateQueries({ queryKey: ["operations-cockpit", scope.userId, scope.organizationId] })}>刷新数据</Button>}>
  {commands.message && <p role="status" className={styles.message}>{commands.message}</p>}
  {commands.pending.error && <ConsoleState kind="error" title="原操作无法读取，请保留本浏览器状态并联系管理员" />}
  {commands.pending.command && <Panel title="保存结果待确认"><p>原操作及编号已保存在本浏览器当前身份、企业下。请重试确认原结果。</p><Button disabled={commands.busy} onClick={() => void commands.execute(commands.pending.command!)}>重试原操作</Button></Panel>}
  {mode === "goals" || mode === "settings" ? <Goals mode={mode} scope={scope} capabilities={capabilities.data} commands={commands} /> : mode === "stores" ? <Matrix scope={scope} capabilities={capabilities.data} commands={commands} /> : <Rules mode={mode} scope={scope} capabilities={capabilities.data} />}
 </ConsolePage>;
}
function Goals({ mode, scope, capabilities, commands }: { mode: "goals" | "settings"; scope: CockpitScope; capabilities: CockpitCapabilities; commands: Commands }) {
 const [before,setBefore]=useState("");
 const period = lastPeriod(capabilities.today), goals = useQuery({ queryKey: ["operations-cockpit", scope.userId, scope.organizationId, "goals"], queryFn: ({ signal }) => cockpitRequest(scope, "goals?" + periodQuery(period), cockpitGoals, { signal }), retry: false });
 const history = useQuery({ queryKey: ["operations-cockpit", scope.userId, scope.organizationId, "goal-history",before], queryFn: ({ signal }) => cockpitRequest(scope, "goals/history"+(before?"?beforeRevision="+before:""), z.array(cockpitGoal).max(20), { signal }), retry: false, enabled: mode === "goals" && !!goals.data?.goal });
 if (goals.isPending) return <ConsoleState kind="loading" title="正在读取经营目标" />;
 if (goals.error) return <ConsoleState kind="error" title={cockpitErrorText(goals.error)} />;
 const data = goals.data!;
 if (mode === "settings") return <GoalForm key={(data.goal?.revision ?? data.head?.revision ?? "new") + data.goalUnavailable} scope={scope} capabilities={capabilities} data={data} commands={commands} />;
 return <>
  <div className={styles.banner}><div><Badge state={data.evaluation?.state ?? "pending_data"} /><h2>{data.goal ? `当前经营目标 · V${data.goal.revision}` : data.goalUnavailable ? "当前目标关联店铺不可访问" : "尚未启用经营目标"}</h2><p>{data.goal ? `${data.goal.config.period.startDate} 至 ${data.goal.config.period.endDate} · ${data.goal.config.storeIds.map(id => capabilities.stores.find(s => s.id === id)?.name ?? "店铺").join("、")}` : "由创建人或当前具备目标管理权限的人维护。"}</p></div>{data.head?.canReconfigure || !data.goal && !data.goalUnavailable && capabilities.access.goalsCreate ? <Link className={styles.primaryLink} href="/workbench/overview/goals/settings">{data.goal || data.head ? "维护经营目标" : "设置经营目标"}</Link> : null}</div>
  <div className={styles.twoColumns}><Panel title="经营目标"><div className={styles.stats}><div>利润目标<strong>{data.goal ? moneyText(data.goal.config.profit) : "—"}</strong></div><div>已完成期间净利润<strong>{data.evaluation && ["normal", "attention", "abnormal"].includes(data.evaluation.state) ? moneyText(data.evaluation.totals.netProfit) : "待完整数据"}</strong></div><div>利润进度<strong>{ratioText(data.evaluation?.completion)}</strong></div></div><p>评判截止日：{data.evaluation?.through || "尚无已完成自然日"}。各店必须完整覆盖该期间；跨界记录不会按天摊销。</p></Panel><Panel title="评判规则"><p>按已完成自然日计算期间应完成的利润，再与已保存收入及成本比较。</p><div className={styles.ruleLine}>正常 <strong>≥ {data.goal ? data.goal.config.normalBps / 100 : 90}%</strong></div><div className={styles.ruleLine}>需关注 <strong>≥ {data.goal ? data.goal.config.attentionBps / 100 : 70}%</strong></div><div className={styles.ruleLine}>异常 <strong>低于关注阈值</strong></div><p>最低利润率：{data.goal?.config.minimumMarginBps != null ? `${data.goal.config.minimumMarginBps / 100}%` : "未启用"}；净收入≤0时不评价利润率。</p></Panel><Panel title="处理方式"><p>首版提供规则判断依据，由人到已有页面核查和处理。</p><Link className={styles.secondaryLink} href="/workbench/overview/stores">查看收入与成本明细 →</Link><p>AI方案、自动任务和平台财务导入后续接入。</p></Panel><Panel title="版本记录">{history.isPending && data.goal ? <p>正在读取版本…</p> : history.error ? <p>{cockpitErrorText(history.error)}</p> : history.data?.length ? history.data.map(v => <div className={styles.version} key={v.revision}><div><strong>V{v.revision} · {moneyText(v.config.profit)}</strong><p>{v.config.period.startDate} 至 {v.config.period.endDate} · {v.updatedAt}</p></div>{v.revision === data.goal?.revision ? <span>当前生效</span> : data.head?.canReconfigure ? <Button variant="outline" disabled={commands.busy || !!commands.pending.command} onClick={() => void commands.save("goals/restore", { id: v.id, expectedRevision: data.head!.revision, sourceRevision: v.revision })}>恢复为新版本</Button> : null}</div>) : <p>尚无版本记录。</p>}</Panel></div>
  {(before||history.data?.length===20)&&<div className={styles.inline}><Button variant="outline" disabled={!before} onClick={()=>setBefore("")}>最新版本</Button><Button variant="outline" disabled={history.data?.length!==20} onClick={()=>setBefore(history.data!.at(-1)!.revision)}>更早版本</Button></div>}
  <Panel title="目标所用经营事实">{data.basis.length ? data.basis.map(b=><details key={b.storeId}><summary>{capabilities.stores.find(s=>s.id===b.storeId)?.name??"授权店铺"} · {b.complete?"完整覆盖":"数据不完整"} · {b.period.startDate} 至 {b.period.endDate}</summary><p>已录入部分净利润 {moneyText(b.totals.netProfit)}；纳入 {b.recordCount} 条记录，缺口 {b.gapCount} 个，跨界排除 {b.excludedCount} 条。</p><p>纳入记录（最多展示20条）：{b.records.map(r=>`${r.period.startDate} 至 ${r.period.endDate} · V${r.revision} · ${r.id}`).join("；")||"无"}</p><p>缺口（最多展示20个）：{b.gaps.map(p=>`${p.startDate} 至 ${p.endDate}`).join("；")||"无"}</p><p>跨界记录（最多展示20条）：{b.excluded.map(r=>`${r.period.startDate} 至 ${r.period.endDate} · V${r.revision}`).join("；")||"无"}</p><Link className={styles.secondaryLink} href={`/workbench/overview/stores?storeId=${b.storeId}&${periodQuery(b.period)}`}>核查本店该期间的记录与历史 →</Link></details>):<p>目标尚未开始、尚未设置或范围不可访问时，暂无可用评判依据。</p>}</Panel>
  <p className={styles.note}>数据读取时间：{data.capturedAt} · 经营事实保存在当前实例的专用数据库中。</p>
 </>;
}
function GoalForm({ capabilities, data, commands }: { scope: CockpitScope; capabilities: CockpitCapabilities; data: z.infer<typeof cockpitGoals>; commands: Commands }) {
 const current = data.goal?.config, id = useRef(crypto.randomUUID()), [storeIds, setStoreIds] = useState(current?.storeIds ?? []), [frequency, setFrequency] = useState<CockpitGoalConfig["frequency"]>(current?.frequency ?? "month"), [day, setDay] = useState(current?.period.startDate ?? capabilities.today), [profit, setProfit] = useState(current ? centsInput(current.profit) : ""), [margin, setMargin] = useState(current?.minimumMarginBps != null ? String(current.minimumMarginBps / 100) : ""), [normal, setNormal] = useState(String((current?.normalBps ?? 9000) / 100)), [attention, setAttention] = useState(String((current?.attentionBps ?? 7000) / 100)), [error, setError] = useState("");
 const period = day ? naturalPeriod(day, frequency) : null, canSave = !!data.head?.canReconfigure || !data.goal && !data.goalUnavailable && capabilities.access.goalsCreate;
 async function submit(event: FormEvent) {
  event.preventDefault(); const amount = moneyCents(profit), normalBps = moneyCents(normal), attentionBps = moneyCents(attention), minimumMarginBps = margin === "" ? null : moneyCents(margin);
  if (!period || !storeIds.length || storeIds.length > 50 || amount == null || amount <= 0 || normalBps == null || attentionBps == null || attentionBps <= 0 || attentionBps >= normalBps || normalBps > 10000 || margin !== "" && (minimumMarginBps == null || minimumMarginBps > 10000)) { setError("请选择 1–50 家店铺，填写正利润目标及有效百分比；关注阈值须低于正常阈值。"); return; }
  setError(""); await commands.save("goals", { id: data.goal?.id ?? data.head?.goalId ?? id.current, expectedRevision: data.goal?.revision ?? data.head?.revision ?? "0", goal: { storeIds, frequency, period, profit: amount, minimumMarginBps, normalBps, attentionBps } });
 }
 return <form onSubmit={event => void submit(event)}><div className={styles.settings}><Panel title="目标配置"><fieldset><legend>1　经营范围</legend><p>仅列出当前有权限的店铺；目标按所选店铺合计评判。</p><div className={styles.storeChoices}>{capabilities.stores.map(s => <label key={s.id}><input type="checkbox" checked={storeIds.includes(s.id)} onChange={e => setStoreIds(e.target.checked ? [...storeIds, s.id] : storeIds.filter(id => id !== s.id))} />{s.name} · {s.region}</label>)}</div>{!capabilities.stores.length && <p>暂无获授权店铺，请先在店铺中心创建或申请访问。</p>}</fieldset><fieldset><legend>2　目标周期与日期</legend><div className={styles.inline}>{(["day", "week", "month"] as const).map((v, i) => <Button key={v} type="button" variant={v === frequency ? "default" : "outline"} onClick={() => setFrequency(v)}>{["每日", "每周", "每月"][i]}</Button>)}<label>周期内日期<Input type="date" value={day} onChange={e => setDay(e.target.value)} required /></label></div><p>{period?.startDate} 至 {period?.endDate}；按自然日、周一开始的一周或完整自然月生效。</p></fieldset><fieldset><legend>3　利润目标</legend><label>目标净利润（人民币元）<Input inputMode="decimal" value={profit} onChange={e => setProfit(e.target.value)} placeholder="输入目标金额" required /></label></fieldset><fieldset><legend>4　利润率底线（可选）</legend><label>最低净利润率（%）<Input inputMode="decimal" value={margin} onChange={e => setMargin(e.target.value)} placeholder="不填写则不启用" /></label><div className={styles.inline}><label>正常阈值（%）<Input value={normal} onChange={e => setNormal(e.target.value)} inputMode="decimal" required /></label><label>关注阈值（%）<Input value={attention} onChange={e => setAttention(e.target.value)} inputMode="decimal" required /></label></div></fieldset></Panel><Panel title="配置结果预览"><dl><dt>经营店铺</dt><dd>{storeIds.map(id => capabilities.stores.find(s => s.id === id)?.name).join("、") || "尚未选择"}</dd><dt>目标期间</dt><dd>{period ? `${period.startDate} 至 ${period.endDate}` : "请选择日期"}</dd><dt>利润目标</dt><dd>{moneyCents(profit) != null ? moneyText(moneyCents(profit)!) : "待填写"}</dd><dt>利润率底线</dt><dd>{margin ? `${margin}%` : "未启用"}</dd></dl><div className={styles.previewNotice}><strong>保存后启用</strong><p>创建新版本，保留创建人及历史。目标设置不自动创建任务或修改平台商品。</p></div>{data.goalUnavailable && <p>旧范围不可访问。此次提交完整新范围和配置，以当前版本安全重配。</p>}</Panel></div>{error && <p role="alert">{error}</p>}<footer className={styles.footer}><p>修改仅为本页草稿；点击保存后才成为当前经营目标。</p><Link href="/workbench/overview/goals">取消</Link><Button type="submit" disabled={!canSave || commands.busy || !!commands.pending.command || commands.pending.error || !commands.pending.ready}>保存并启用</Button></footer>{!canSave && <p>当前身份可查看目标。维护需创建人身份或当前目标管理权限。</p>}</form>;
}

function PeriodToolbar({ period, setPeriod, today, children }: { period: Period; setPeriod: (value: Period) => void; today: string; children?: ReactNode }) {
 return <Card className={styles.toolbar}><div className={styles.inline}><span>统计期间</span><Button variant="outline" onClick={() => setPeriod(lastPeriod(today))}>近7个完整日</Button><Button variant="outline" onClick={() => setPeriod({ startDate: addDays(today, -30), endDate: addDays(today, -1) })}>近30个完整日</Button><label>开始日期<Input type="date" value={period.startDate} onChange={e => setPeriod({ ...period, startDate: e.target.value })} /></label><label>结束日期<Input type="date" value={period.endDate} onChange={e => setPeriod({ ...period, endDate: e.target.value })} /></label></div><div className={styles.inline}>{children}</div></Card>;
}
function Matrix({ scope, capabilities, commands }: { scope: CockpitScope; capabilities: CockpitCapabilities; commands: Commands }) {
 const [period, setPeriod] = useState(()=>linkedPeriod(capabilities.today)), [page, setPage] = useState(1), [search, setSearch] = useState(""), [state, setState] = useState(""), [selected, setSelected] = useState<string[]>([]), [compare, setCompare] = useState(false), [storeId, setStoreId] = useState(() => typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("storeId") ?? "");
 const query = new URLSearchParams({ ...period, page: String(page), search, state, sort: "profit" });
 if (compare) selected.forEach(id => query.append("storeId", id));
 const matrix = useQuery({ queryKey: ["operations-cockpit", scope.userId, scope.organizationId, "matrix", query.toString()], queryFn: ({ signal }) => cockpitRequest(scope, "stores?" + query, cockpitMatrix, { signal }), retry: false });
 function changePeriod(p: Period) { setPeriod(p); setPage(1); setCompare(false); setSelected([]); }
 return <>
  <PeriodToolbar today={capabilities.today} period={period} setPeriod={changePeriod}><label>经营状态<select value={state} onChange={e => { setState(e.target.value); setPage(1); }}>{["", "loss", "break_even", "recorded_complete", "data_incomplete"].map(v => <option key={v} value={v}>{stateNames[v] ?? "全部状态"}</option>)}</select></label><label>搜索店铺<Input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} maxLength={100} placeholder="店铺名称" /></label></PeriodToolbar>
  {matrix.isPending ? <ConsoleState kind="loading" title="正在读取同周期经营事实" /> : matrix.error ? <ConsoleState kind="error" title={cockpitErrorText(matrix.error)} /> : matrix.data ? <>
   <div className={styles.fourStats}>{[ ["当前授权店铺", Object.values(matrix.data.states).reduce((a, b) => a + b, 0)], ["录入完整", matrix.data.states.recorded_complete + matrix.data.states.break_even], ["本期亏损", matrix.data.states.loss], ["数据不完整", matrix.data.states.data_incomplete] ].map(([label, value]) => <Card key={label} className={styles.stat}><span>{label}</span><strong>{value}</strong></Card>)}</div>
   <Panel title={compare ? "已选店铺同周期比较" : "店铺经营对比"}><p>{matrix.data.summaryComplete ? "完整覆盖的所选店铺合计净利润" : "完整录入店铺部分的合计净利润"}：{moneyText(matrix.data.summary.netProfit)}。单店状态仅依据人工经营数据。</p><div className={styles.tableScroll}><table><thead><tr><th>选择</th><th>店铺</th><th>平台 · 站点</th><th>净收入</th><th>净利润</th><th>利润率</th><th>较前一等长期间</th><th>经营数据状态</th><th>操作</th></tr></thead><tbody>{matrix.data.rows.map(row => <tr key={row.store.id}><td><input type="checkbox" aria-label={`选择${row.store.name}`} checked={selected.includes(row.store.id)} disabled={!selected.includes(row.store.id) && selected.length >= 5} onChange={e => { setCompare(false); setSelected(e.target.checked ? [...selected, row.store.id] : selected.filter(id => id !== row.store.id)); }} /></td><td><strong>{row.store.name}</strong><small>{row.store.status === "active" ? "店铺记录启用" : "店铺记录停用"}</small></td><td>{row.store.platform.toUpperCase()} · {row.store.region}</td><td>{row.complete ? moneyText(row.totals.netRevenue) : "已录入部分 " + moneyText(row.totals.netRevenue)}</td><td>{row.complete ? moneyText(row.totals.netProfit) : "待完整数据"}</td><td>{row.complete ? ratioText(row.totals.margin) : "—"}</td><td>{ratioText(row.growth)}</td><td><Badge state={row.state} /></td><td><Button variant="outline" onClick={() => setStoreId(row.store.id)}>查看 / 录入</Button></td></tr>)}</tbody></table></div>{!matrix.data.rows.length && <p>所选范围暂无店铺。</p>}<div className={styles.pagination}><span>共{matrix.data.total}家 · 第{page}页</span><Button variant="outline" disabled={page === 1} onClick={() => setPage(page - 1)}>上一页</Button><Button variant="outline" disabled={page * 50 >= matrix.data.total} onClick={() => setPage(page + 1)}>下一页</Button></div></Panel>
   <div className={styles.selection}><span>已选 {selected.length} 家店铺，支持 2–5 家比较。</span><Button variant="outline" onClick={() => { setSelected([]); setCompare(false); }}>取消选择</Button><Button disabled={selected.length < 2 || selected.length > 5} onClick={() => { setCompare(true); setSearch(""); setState(""); setPage(1); }}>开始对比</Button></div><p className={styles.note}>数据读取时间：{matrix.data.capturedAt} · 前一等长期间完整且利润为正时才提供变化比例。</p>
  </> : null}
  {storeId && <StoreDetail key={storeId + period.startDate + period.endDate} scope={scope} storeId={storeId} period={period} today={capabilities.today} canWrite={capabilities.access.factsWrite} commands={commands} close={() => setStoreId("")} />}
 </>;
}
function StoreDetail({ scope, storeId, period, today, canWrite, commands, close }: { scope: CockpitScope; storeId: string; period: Period; today: string; canWrite: boolean; commands: Commands; close: () => void }) {
 const [recordPage, setRecordPage] = useState(1), [edit, setEdit] = useState<CockpitRecord | null>(null), [form, setForm] = useState(false), [formReceipt, setFormReceipt] = useState(commands.lastSaved), [historyID, setHistoryID] = useState(""), [before, setBefore] = useState("");
 const detail = useQuery({ queryKey: ["operations-cockpit", scope.userId, scope.organizationId, "store", storeId, period], queryFn: ({ signal }) => cockpitRequest(scope, `stores/${storeId}?${periodQuery(period)}`, cockpitDetail, { signal }), retry: false });
 const records = useQuery({ queryKey: ["operations-cockpit", scope.userId, scope.organizationId, "facts", storeId, recordPage], queryFn: ({ signal }) => cockpitRequest(scope, `facts?storeId=${storeId}&page=${recordPage}`, z.array(cockpitRecord).max(50), { signal }), retry: false });
 const history = useQuery({ queryKey: ["operations-cockpit", scope.userId, scope.organizationId, "fact-history", historyID, before], queryFn: ({ signal }) => cockpitRequest(scope, `facts/${historyID}/history${before ? "?beforeRevision=" + before : ""}`, z.array(cockpitRecord).max(20), { signal }), retry: false, enabled: !!historyID });
 return <Panel title={detail.data?.store.name ?? "经营明细"}><div className={styles.inline}><Button variant="outline" onClick={close}>关闭明细</Button>{canWrite && <Button disabled={commands.busy || !!commands.pending.command} onClick={() => { setEdit(null); setFormReceipt(commands.lastSaved); setForm(true); }}>录入经营数据</Button>}</div>{detail.isPending ? <p>正在读取经营期间…</p> : detail.error ? <p role="alert">{cockpitErrorText(detail.error)}</p> : detail.data ? <><p><Badge state={detail.data.aggregate.complete ? detail.data.aggregate.totals.netProfit < 0 ? "loss" : "recorded_complete" : "data_incomplete"} /> · {period.startDate} 至 {period.endDate}</p><div className={styles.stats}><div>已录入净收入<strong>{moneyText(detail.data.aggregate.totals.netRevenue)}</strong></div><div>已录入净利润<strong>{moneyText(detail.data.aggregate.totals.netProfit)}</strong></div></div><p>净利润 = 退款前收入 − 退款 − 本期售出采购成本 − 物流 − 平台费用 − 广告 − 其他成本。</p>{detail.data.aggregate.gaps.length > 0 && <p>未覆盖区间：{detail.data.aggregate.gaps.map(p => `${p.startDate} 至 ${p.endDate}`).join("；")}</p>}{detail.data.aggregate.excluded.length > 0 && <p>跨查询边界、未计入：{detail.data.aggregate.excluded.map(r => `${r.period.startDate} 至 ${r.period.endDate}（V${r.revision}）`).join("；")}</p>}<p className={styles.note}>读取时间：{detail.data.capturedAt}</p></> : null}
  {form && formReceipt === commands.lastSaved && <FactForm key={edit?.id + ":" + edit?.revision + ":" + commands.lastSaved?.commandId} record={edit} storeId={storeId} period={period} today={today} commands={commands} close={() => setForm(false)} />}
  <h3>当前已保存记录</h3><p>按录入区间显示，包含所选查询期间之外的记录；日期和金额修正会保留历史。</p>{records.isPending ? <p>正在读取记录…</p> : records.error ? <p role="alert">{cockpitErrorText(records.error)}</p> : records.data?.map(record => <div className={styles.version} key={record.id}><div><strong>{record.period.startDate} 至 {record.period.endDate} · V{record.revision}</strong><p>收入 {moneyText(record.amounts.revenue)}，退款 {moneyText(record.amounts.refunds)}；录入人 {record.updatedBy}</p><small>{record.updatedAt}</small></div><div className={styles.inline}>{canWrite && <Button variant="outline" disabled={commands.busy || !!commands.pending.command} onClick={() => { setEdit(record); setFormReceipt(commands.lastSaved); setForm(true); }}>修正</Button>}<Button variant="outline" onClick={() => { setHistoryID(record.id); setBefore(""); }}>历史</Button></div></div>)}<div className={styles.pagination}><span>记录第{recordPage}页</span><Button variant="outline" disabled={recordPage === 1} onClick={() => setRecordPage(recordPage - 1)}>上一页</Button><Button variant="outline" disabled={!records.data || records.data.length < 50} onClick={() => setRecordPage(recordPage + 1)}>下一页</Button></div>
  {historyID && <div className={styles.history}><h3>不可变版本记录</h3><Button variant="outline" onClick={() => setHistoryID("")}>收起</Button>{history.isPending ? <p>正在读取历史…</p> : history.error ? <p>{cockpitErrorText(history.error)}</p> : history.data?.map(v => <div key={v.revision}><strong>V{v.revision} · {v.period.startDate} 至 {v.period.endDate}</strong><p>{fields.map((key, i) => `${labels[i]} ${moneyText(v.amounts[key])}`).join("；")}</p><p>{v.note || "无备注"} · {v.updatedBy} · {v.updatedAt}</p></div>)}{history.data?.length === 20 && <Button variant="outline" onClick={() => setBefore(history.data!.at(-1)!.revision)}>更早版本</Button>}</div>}
 </Panel>;
}
function FactForm({ record, storeId, period, today, commands, close }: { record: CockpitRecord | null; storeId: string; period: Period; today: string; commands: Commands; close: () => void }) {
 const id = useRef(crypto.randomUUID()), [start, setStart] = useState(record?.period.startDate ?? period.startDate), [end, setEnd] = useState(record?.period.endDate ?? (period.endDate < today ? period.endDate : addDays(today, -1))), [values, setValues] = useState(() => fields.map(key => record ? centsInput(record.amounts[key]) : "")), [note, setNote] = useState(record?.note ?? ""), [error, setError] = useState("");
 async function submit(event: FormEvent) {
  event.preventDefault(); const parsed = values.map(moneyCents);
  const days = (new Date(end + "T00:00:00Z").getTime() - new Date(start + "T00:00:00Z").getTime()) / 86400000 + 1;
  if (parsed.some(v => v === null) || !start || !end || end >= today || days < 1 || days > 366 || !Number.isFinite(days) || [...note].length > 1000) { setError("请填写已完成且不超过366天的区间及全部收入、成本。没有发生的项目请明确填写0，金额最多两位小数。"); return; }
  setError(""); const amounts = Object.fromEntries(fields.map((field, index) => [field, parsed[index]]));
  if (await commands.save("facts", { id: record?.id ?? id.current, storeId, expectedRevision: record?.revision ?? "0", fact: { period: { startDate: start, endDate: end }, amounts, note } })) close();
 }
 return <form className={styles.factForm} onSubmit={e => void submit(e)}><h3>{record ? `修正记录 · 当前V${record.revision}` : "录入经营数据"}</h3><p>人民币元，人工录入。采购成本填写本期已经销售商品的成本。</p><div className={styles.inline}><label>开始日期<Input type="date" required value={start} onChange={e => setStart(e.target.value)} max={addDays(today, -1)} /></label><label>结束日期<Input type="date" required value={end} onChange={e => setEnd(e.target.value)} max={addDays(today, -1)} /></label></div><div className={styles.amountGrid}>{fields.map((key, i) => <label key={key}>{labels[i]}<Input inputMode="decimal" required value={values[i]} placeholder="未发生请填0" onChange={e => setValues(values.map((v, j) => i === j ? e.target.value : v))} /></label>)}</div><label>备注<textarea value={note} maxLength={2000} onChange={e => setNote(e.target.value)} /></label>{error && <p role="alert">{error}</p>}<div className={styles.inline}><Button type="button" variant="outline" onClick={close}>取消</Button><Button type="submit" disabled={commands.busy || !!commands.pending.command || !commands.pending.ready || commands.pending.error}>{record ? "保存为新版本" : "保存经营数据"}</Button></div></form>;
}

function RuleDetail({ rule, name }: { rule: CockpitRule; name?: string }) {
 return <><div className={styles.inline}><Badge state={rule.level === "critical" ? "abnormal" : rule.level === "attention" ? "attention" : "data_incomplete"} /><span>{name ?? "企业目标"} · 人工经营规则</span></div><h2>{rule.title}</h2><p>{rule.reason}</p><div className={styles.stats}><div>依据区间<strong>{rule.period.startDate} 至 {rule.period.endDate}</strong></div><div>完整净利润<strong>{rule.profit != null ? moneyText(rule.profit) : "待完整数据"}</strong></div></div>{rule.goalBasis && <p>目标 V{rule.goalRevision}：{moneyText(rule.goalBasis.target)}；正常阈值 {rule.goalBasis.normalBps / 100}%，关注阈值 {rule.goalBasis.attentionBps / 100}%，截至 {rule.goalBasis.evaluation.through} 的利润进度 {ratioText(rule.goalBasis.evaluation.completion)}，净利润率 {ratioText(rule.goalBasis.evaluation.totals.margin)}。</p>}{!rule.goalBasis && <p>当前保存记录 {rule.recordCount ?? 0} 条；缺口 {rule.gapCount ?? 0} 个，跨界排除 {rule.excludedCount ?? 0} 条。</p>}<div className={styles.previewNotice}><h3>建议处理</h3><p>{rule.advice}</p><Link className={styles.primaryLink} href={rule.actionPath}>{rule.actionLabel} →</Link></div><p className={styles.note}>依据读取时间：{rule.capturedAt}。规则不保存处理状态；核查后刷新当前事实。</p></>;
}
function Rules({ mode, scope, capabilities }: { mode: "alerts" | "advice"; scope: CockpitScope; capabilities: CockpitCapabilities }) {
 const [period, setPeriod] = useState(lastPeriod(capabilities.today)), [page, setPage] = useState(1), [level, setLevel] = useState(""), [kind, setKind] = useState(""), [storeId, setStoreId] = useState(""), [selected, setSelected] = useState("");
 const query = new URLSearchParams({ ...period, page: String(page), level, kind }); if (storeId) query.append("storeId", storeId);
 const rules = useQuery({ queryKey: ["operations-cockpit", scope.userId, scope.organizationId, mode, query.toString()], queryFn: ({ signal }) => cockpitRequest(scope, mode + "?" + query, cockpitRules, { signal }), retry: false });
 const current = rules.data?.rules.find(rule => rule.id === selected) ?? rules.data?.rules[0];
 function update(action: () => void) { action(); setPage(1); setSelected(""); }
 return <><PeriodToolbar today={capabilities.today} period={period} setPeriod={p => update(() => setPeriod(p))}><label>店铺<select value={storeId} onChange={e => update(() => setStoreId(e.target.value))}><option value="">全部当前授权店铺</option>{capabilities.stores.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>等级<select value={level} onChange={e => update(() => setLevel(e.target.value))}><option value="">全部等级</option><option value="critical">目标异常</option><option value="attention">需关注</option><option value="data">数据提醒</option></select></label><label>类型<select value={kind} onChange={e => update(() => setKind(e.target.value))}><option value="">全部类型</option><option value="period_loss">经营亏损</option><option value="goal_assessment">目标评判</option><option value="data_missing">录入缺失</option></select></label></PeriodToolbar>
  {rules.isPending ? <ConsoleState kind="loading" title="正在读取当前规则依据" /> : rules.error ? <ConsoleState kind="error" title={cockpitErrorText(rules.error)} /> : rules.data ? <>
   {rules.data.goalUnavailable && <p>企业当前目标或关联店铺不可访问，目标评判暂不可用。</p>}
   {mode === "advice" ? <div className={styles.advice}><Panel title="建议队列"><span>当前筛选共 {rules.data.total} 条</span>{rules.data.rules.map(rule => <button className={styles.queueItem} aria-pressed={current?.id === rule.id} key={rule.id} onClick={() => setSelected(rule.id)}><strong>{rule.title}</strong><small>{capabilities.stores.find(s => s.id === rule.storeId)?.name ?? "企业目标"}</small><Badge state={rule.level === "data" ? "data_incomplete" : "attention"} /></button>)}</Panel><Panel title="经营建议 · 规则依据">{current ? <RuleDetail rule={current} name={capabilities.stores.find(s => s.id === current.storeId)?.name} /> : <Empty title="当前范围没有触发经营规则">这仅表示已读取范围内没有规则结果；缺少平台观察仍按下方状态显示。</Empty>}</Panel></div> : <Panel title="当前经营问题"><span>当前筛选共 {rules.data.total} 条</span>{rules.data.rules.map(rule => <div className={styles.alertRow} key={rule.id}><Badge state={rule.level === "critical" ? "abnormal" : rule.level === "data" ? "data_incomplete" : "attention"} /><div><strong>{rule.title}</strong><p>{capabilities.stores.find(s => s.id === rule.storeId)?.name ?? "企业目标"} · {rule.period.startDate} 至 {rule.period.endDate}</p><small>{rule.reason}</small></div><Button variant="outline" onClick={() => setSelected(selected === rule.id ? "" : rule.id)}>查看依据</Button>{selected === rule.id && <div className={styles.alertDetail}><RuleDetail rule={rule} name={capabilities.stores.find(s => s.id === rule.storeId)?.name} /></div>}</div>)}{!rules.data.rules.length && <p>当前已读取范围没有触发经营规则。</p>}</Panel>}
   <div className={styles.pagination}><span>第{page}页</span><Button variant="outline" disabled={page === 1} onClick={() => { setPage(page - 1); setSelected(""); }}>上一页</Button><Button variant="outline" disabled={page * 50 >= rules.data.total} onClick={() => { setPage(page + 1); setSelected(""); }}>下一页</Button></div>
   <Panel title="平台订单观察 · 独立于人工经营期间"><p>来源：已有 SHEIN 订单观察；这里只读保存事实。其观察日期和范围与上方经营期间独立。</p><p>观察状态：{{ unavailable: "当前未取得观察能力", permission_required: "需要订单观察 / 店铺权限", no_active_store: "暂无可观察的启用店铺", available: "已保存观察范围完整", incomplete: "已保存观察范围不完整", latest_incomplete: "最新获取未完成，已有事实保留原时间" }[rules.data.observations.state]}。</p>{["available", "incomplete", "latest_incomplete"].includes(rules.data.observations.state) && <p>已保存范围内平台异常订单：{rules.data.observations.exceptional}；{rules.data.observations.complete ? "范围完整" : "范围不完整，不代表店铺全部订单"}。</p>}<details><summary>查看来源、观察时间与范围</summary>{rules.data.observations.sources.map(source => <p key={source.syncId}>{capabilities.stores.find(s => s.id === source.storeId)?.name ?? "授权店铺"} · {source.status} · {source.observedAt ?? "无完成时间"}<br />{source.start ?? "范围未知"} 至 {source.end ?? "范围未知"} · 观察编号 {source.syncId}</p>)}{rules.data.observations.latest.map(source => <p key={"latest" + source.syncId}>最近获取：{source.status} {source.errorCode} · {source.observedAt ?? "尚无完成时间"}</p>)}</details><Link className={styles.secondaryLink} href={rules.data.observations.actionPath}>到订单履约核查，发货 / 售后由人到平台处理 →</Link></Panel><p className={styles.note}>人工经营事实读取时间：{rules.data.capturedAt} · AI方案与确认后自动创建任务尚未开放。</p>
  </> : null}
 </>;
}
