import {z} from "zod";
import * as c from "../contracts/pod";
import {MarketAPIError,type MarketScope} from "./supply-market";
import {readBoundedStrictJSON} from "./strict-json-response";
export async function podRequest<T>(scope:MarketScope,path:string,schema:z.ZodType<T>,signal?:AbortSignal,write?:{key:string;body:unknown}):Promise<T>{
 const controller=new AbortController(),abort=()=>controller.abort();signal?.addEventListener("abort",abort,{once:true});if(signal?.aborted)abort();const timer=setTimeout(abort,37000);let sent=false;
 try{const headers=new Headers({Accept:"application/json","X-Expected-User-ID":scope.userId,"X-Expected-Organization-ID":scope.organizationId});let body:string|undefined;if(write){headers.set("Idempotency-Key",c.podID.parse(write.key));headers.set("Content-Type","application/json");body=JSON.stringify(write.body)}controller.signal.throwIfAborted();sent=true;const response=await fetch("/api/workbench/pod/"+path,{method:write?"POST":"GET",headers,body,credentials:"same-origin",cache:"no-store",redirect:"error",signal:controller.signal});const raw=await readBoundedStrictJSON(response,2*1024*1024,controller.signal);if(!response.ok){const code=(raw as {code?:unknown})?.code;throw new MarketAPIError(typeof code==="string"&&/^[A-Z_]{1,80}$/.test(code)?code:write?"OUTCOME_UNKNOWN":"DEPENDENCY_UNAVAILABLE",response.status)}const parsed=schema.safeParse(raw);if(response.status!==200||!parsed.success)throw new Error();return parsed.data}catch(e){if(e instanceof MarketAPIError)throw e;throw new MarketAPIError(write&&sent?"OUTCOME_UNKNOWN":"DEPENDENCY_UNAVAILABLE",502)}finally{clearTimeout(timer);signal?.removeEventListener("abort",abort)}
}
export const listPODTemplates=(s:MarketScope,page:number,keyword:string,signal?:AbortSignal)=>podRequest(s,"templates?"+new URLSearchParams({page:String(page),size:"10",keyword}),c.podTemplatesSchema,signal);
export const readPODTemplate=(s:MarketScope,id:string,signal?:AbortSignal)=>podRequest(s,"templates/"+id,c.podTemplateDetailSchema,signal);
export const readPODManifest=(s:MarketScope,item:string,variant:string,signal?:AbortSignal)=>podRequest(s,"manifests/"+c.podID.parse(item)+"?variant="+variant,c.podManifestSchema,signal);
export const readPODArtwork=(s:MarketScope,id:string,signal?:AbortSignal)=>podRequest(s,"artwork/"+c.podID.parse(id),c.podArtworkSchema,signal);
export const readPODProgress=(s:MarketScope,id:string,verify=false,signal?:AbortSignal)=>podRequest(s,"designs/"+c.podID.parse(id)+(verify?"/verify":""),c.podProgressSchema,signal);
export function writePOD(s:MarketScope,i:c.PODIntent,signal?:AbortSignal):Promise<c.PODResult>{const intent=c.podIntentSchema.parse(i);switch(intent.kind){case"template":return podRequest(s,"templates/select",c.podReceiptSchema,signal,intent);case"finished":return podRequest(s,"designs/"+intent.id+"/select",c.podReceiptSchema,signal,intent);case"approval":return podRequest(s,"approvals",c.podApprovalSchema,signal,intent);case"design":return podRequest(s,"designs",c.podProgressSchema,signal,intent)}}
export function resolvePOD(s:MarketScope,i:c.PODIntent,signal?:AbortSignal):Promise<c.PODResult>{switch(i.kind){case"template":case"finished":return podRequest(s,"imports/by-key/"+i.key,c.podReceiptSchema,signal);case"design":return podRequest(s,"by-key/"+i.key,c.podProgressSchema,signal);case"approval":return podRequest(s,"artwork/"+i.body.selection.itemId+"/approvals/"+i.key,c.podApprovalSchema,signal)}}
