import {beforeEach,afterEach,expect,it,vi} from "vitest";
import {proxyProjectCenter} from "./project-center-proxy";
import {WORKBENCH_COOKIE_NAME} from "./workbench-proxy";
const id="550e8400-e29b-41d4-a716-446655440000";
const fetcher=vi.fn();
beforeEach(()=>{vi.stubGlobal("fetch",fetcher);fetcher.mockReset();process.env.LISTINGKIT_PUBLIC_BASE_URL="https://app.example";process.env.LISTINGKIT_SERVICE_API_BASE="http://127.0.0.1:8080/api/v1";});afterEach(()=>{vi.unstubAllGlobals();});
function request(path="",body:unknown={title:"项目",goal:"目标",kind:"OTHER",dueDate:""},method="POST"){return new Request("https://app.example/api/workbench/projects"+path,{method,headers:{Origin:"https://app.example","Sec-Fetch-Site":"same-origin",Cookie:WORKBENCH_COOKIE_NAME+"=org-a","X-Expected-User-ID":"user-a","X-Expected-Organization-ID":"org-a","Content-Type":"application/json","Idempotency-Key":id},body:JSON.stringify(body)});}
it("forwards the authenticated private scope and preserves the operation key",async()=>{fetcher.mockResolvedValue(Response.json({id,revision:1,replayed:false}));const result=await proxyProjectCenter(request(),"token","user-a");expect(result.status).toBe(200);const init=fetcher.mock.calls[0][1];expect(init.headers.get("X-Requested-Organization-ID")).toBe("org-a");expect(init.headers.get("Idempotency-Key")).toBe(id);expect(init.headers.get("Authorization")).toBe("Bearer token");expect(init.redirect).toBe("manual");});
it("rejects cross origin writes and stale actor or enterprise before dispatch",async()=>{const r=request();r.headers.set("Origin","https://other.example");expect((await proxyProjectCenter(r,"token","user-a")).status).toBe(403);expect((await proxyProjectCenter(request(),"token","user-b")).status).toBe(409);const b=request();b.headers.set("X-Expected-Organization-ID","org-b");expect((await proxyProjectCenter(b,"token","user-a")).status).toBe(409);expect(fetcher).not.toHaveBeenCalled();});
it("requires a revision for archive and preserves ambiguity after dispatch",async()=>{expect((await proxyProjectCenter(request("/"+id+"/archive",{}),"token","user-a")).status).toBe(400);const r=request("/"+id+"/archive",{});r.headers.set("If-Match","1");fetcher.mockRejectedValue(new Error("response lost"));const result=await proxyProjectCenter(r,"token","user-a");expect(await result.json()).toEqual({code:"OUTCOME_UNKNOWN"});expect(fetcher).toHaveBeenCalledTimes(1);});
it("rejects duplicate input keys and denied reference metadata",async()=>{const r=request();const duplicate=new Request(r,{body:'{"title":"one","title":"two","goal":"goal","kind":"OTHER","dueDate":""}'});expect((await proxyProjectCenter(duplicate,"token","user-a")).status).toBe(400);expect(fetcher).not.toHaveBeenCalled();});
