package shein

import sheinmarketplace "task-processor/internal/marketplace/shein/workspace"

type EditorRecommendationMeta = sheinmarketplace.EditorRecommendationMeta
type EditorAttributeSuggestion = sheinmarketplace.EditorAttributeSuggestion
type EditorSaleCandidateSuggestion = sheinmarketplace.EditorSaleCandidateSuggestion
type EditorEffect = sheinmarketplace.EditorEffect
type EditorProgress = sheinmarketplace.EditorProgress
type EditorProgressSection = sheinmarketplace.EditorProgressSection
