package shein

import sheinmarketplace "task-processor/internal/marketplace/shein/workspace"

type RevisionInput = sheinmarketplace.RevisionInput
type CategoryResolutionPatch = sheinmarketplace.CategoryResolutionPatch
type AttributeResolutionPatch = sheinmarketplace.AttributeResolutionPatch
type SaleAttributeResolutionPatch = sheinmarketplace.SaleAttributeResolutionPatch
type SKCRevisionPatch = sheinmarketplace.SKCRevisionPatch
type SKURevisionPatch = sheinmarketplace.SKURevisionPatch
type EditorRevisionSkeleton = sheinmarketplace.EditorRevisionSkeleton
