package productsourcing

import (
	"context"
	"encoding/json"
	"errors"
	"os"
	"strings"
	"sync"
	"sync/atomic"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
	"task-processor/internal/authz"
	"task-processor/internal/product/sourcing"
)

func browserReadOnlyDatabase(t *testing.T, db *gorm.DB) *gorm.DB {
	t.Helper()
	var name string
	require.NoError(t, db.Raw("SELECT current_database()").Scan(&name).Error)
	require.True(t, strings.HasPrefix(name, "issue398_app_"), "database must be generated by the existing task-isolated helper")
	dsn := os.Getenv("ISSUE398_TEST_DSN") + " dbname=" + name + " options='-c default_transaction_read_only=on'"
	reader, err := gorm.Open(postgres.Open(dsn), &gorm.Config{Logger: logger.Default.LogMode(logger.Silent)})
	require.NoError(t, err)
	pool, err := reader.DB()
	require.NoError(t, err)
	pool.SetMaxOpenConns(2)
	t.Cleanup(func() { require.NoError(t, pool.Close()) })
	var mode string
	require.NoError(t, reader.Raw("SHOW default_transaction_read_only").Scan(&mode).Error)
	require.Equal(t, "on", mode)
	return reader
}

func TestBrowserCaptureBusinessChainExactVersionsReplayAndAuth(t *testing.T) {
	// Existing Public fixture infrastructure is pointed at this task's new PG,
	// never the previous task's container or business data.
	db := acquisitionDatabase(t)
	permissions, err := authz.NewListingKitAuthorizer(nil, nil)
	require.NoError(t, err)
	var revoked atomic.Bool
	live := liveRolesFunc(func(context.Context, string, string) ([]string, error) {
		if revoked.Load() {
			return []string{"listingkit_viewer"}, nil
		}
		return []string{"listingkit_operator"}, nil
	})
	_, err = NewBrowserAcquisition(context.Background(), db, live, permissions)
	require.Error(t, err)
	var tables int64
	require.NoError(t, db.Raw("SELECT count(*) FROM information_schema.tables WHERE table_schema='public'").Scan(&tables).Error)
	require.Zero(t, tables)
	require.NoError(t, InstallAcquisitionSchema(db))
	service, err := NewBrowserAcquisition(context.Background(), db, live, permissions)
	require.NoError(t, err)
	require.Nil(t, service.core.provider)
	body, _, _ := browserApplicationFixture(t)
	ctx := acquisitionIdentity("browser-org", "browser-actor")
	key := uuid.NewString()
	first, err := service.Capture(ctx, key, body)
	require.NoError(t, err)
	require.NotNil(t, first.Publication)
	require.Equal(t, "棉质收纳袋", first.Publication.Snapshot.Title)
	require.Equal(t, "crawler:1688:981645030344", first.Publication.Receipt.ProductKey)
	require.EqualValues(t, 1, first.Publication.Receipt.CatalogVersion)
	require.Equal(t, sourcing.BrowserAcquisitionProducerKind, first.Publication.Receipt.Producer.Kind)
	require.Equal(t, first.Operation.CaptureSHA256, first.Publication.Envelope.RawReference.Metadata["capture_sha256"])
	require.Equal(t, "browser_capture", first.Publication.Envelope.RawReference.Metadata["channel"])
	require.NotEmpty(t, first.Publication.Envelope.MissingFacts)
	provider, fetches, _ := acquisitionFixture(t)
	public, err := NewPublicAcquisition(context.Background(), db, live, permissions, provider)
	require.NoError(t, err)
	_, err = public.Acquire(ctx, key, "981645030344")
	require.ErrorIs(t, err, sourcing.ErrAcquisitionConflict)
	require.Zero(t, fetches.Load())
	publicKey := uuid.NewString()
	second, err := public.Acquire(ctx, publicKey, "981645030344")
	require.NoError(t, err)
	require.EqualValues(t, 2, second.Publication.Receipt.CatalogVersion)
	_, err = service.Capture(ctx, publicKey, body)
	require.ErrorIs(t, err, sourcing.ErrAcquisitionConflict)
	replayed, err := service.Capture(ctx, key, body)
	require.NoError(t, err)
	require.True(t, replayed.Replayed)
	require.Equal(t, first.Publication, replayed.Publication)
	changed := []byte(strings.Replace(string(body), "12.34000001", "12.34000002", 1))
	_, err = service.Capture(ctx, key, changed)
	require.ErrorIs(t, err, sourcing.ErrAcquisitionConflict)
	_, err = service.ByKey(acquisitionIdentity("other-org", "browser-actor"), key)
	require.ErrorIs(t, err, sourcing.ErrAcquisitionNotFound)
	_, err = service.ByKey(acquisitionIdentity("browser-org", "other-actor"), key)
	require.ErrorIs(t, err, sourcing.ErrAcquisitionNotFound)
	revoked.Store(true)
	_, err = service.ByKey(ctx, key)
	require.ErrorIs(t, err, sourcing.ErrPublicationForbidden)
	_, err = service.Verify(ctx, key, body)
	require.ErrorIs(t, err, sourcing.ErrPublicationForbidden)
	_, err = service.Capture(ctx, uuid.NewString(), body)
	require.ErrorIs(t, err, sourcing.ErrPublicationForbidden)
	for _, table := range []string{"product_snapshot_versions", "product_source_publications", "product_source_publication_receipts", "product_acquisition_operations"} {
		var count int64
		require.NoError(t, db.Table(table).Count(&count).Error)
		require.EqualValues(t, 2, count, table)
	}
}

func TestBrowserCaptureBusinessChainLostResponseReadOnlyRecovery(t *testing.T) {
	db := acquisitionDatabase(t)
	require.NoError(t, InstallAcquisitionSchema(db))
	permissions, err := authz.NewListingKitAuthorizer(nil, nil)
	require.NoError(t, err)
	live := liveRolesFunc(func(context.Context, string, string) ([]string, error) { return []string{"listingkit_operator"}, nil })
	service, err := NewBrowserAcquisition(context.Background(), db, live, permissions)
	require.NoError(t, err)
	lost := &acquisitionLostPublicationResponse{AcquisitionPublisher: service.core.publisher}
	service.core.publisher = lost
	body, _, _ := browserApplicationFixture(t)
	ctx := acquisitionIdentity("browser-org", "browser-actor")
	key := uuid.NewString()
	_, err = service.Capture(ctx, key, body)
	require.ErrorIs(t, err, sourcing.ErrAcquisitionUnknown)
	require.Equal(t, 1, lost.publishes)
	op, err := service.core.operations.ByKey(ctx, sourcing.PublicationScope{OrganizationID: "browser-org", ActorID: "browser-actor"}, key)
	require.NoError(t, err)
	require.Equal(t, sourcing.AcquisitionPublishing, op.State)
	original, err := json.Marshal(op.Command)
	require.NoError(t, err)
	require.Equal(t, lost.command, original)
	recovery, err := NewBrowserAcquisition(context.Background(), browserReadOnlyDatabase(t, db), live, permissions)
	require.NoError(t, err)
	for _, read := range []func() (sourcing.AcquisitionResult, error){
		func() (sourcing.AcquisitionResult, error) { return recovery.ByKey(ctx, key) },
		func() (sourcing.AcquisitionResult, error) { return recovery.Verify(ctx, key, body) },
		func() (sourcing.AcquisitionResult, error) { return recovery.Read(ctx, op.ID) },
	} {
		result, err := read()
		require.NoError(t, err)
		require.NotNil(t, result.Publication)
		require.EqualValues(t, 1, result.Publication.Receipt.CatalogVersion)
	}
	unchanged, err := service.core.operations.ByKey(ctx, op.Scope, key)
	require.NoError(t, err)
	require.Equal(t, sourcing.AcquisitionPublishing, unchanged.State, "readonly recovery cannot Finish")
	raw, err := json.Marshal(unchanged.Command)
	require.NoError(t, err)
	require.Equal(t, original, raw)
	var count int64
	require.NoError(t, db.Table("product_snapshot_versions").Count(&count).Error)
	require.EqualValues(t, 1, count)
}

func TestBrowserCaptureBusinessChainReadOnlyUnknownStates(t *testing.T) {
	for _, state := range []string{sourcing.AcquisitionAcquiring, sourcing.AcquisitionPrepared, sourcing.AcquisitionFailed} {
		t.Run(state, func(t *testing.T) {
			db := acquisitionDatabase(t)
			require.NoError(t, InstallAcquisitionSchema(db))
			permissions, err := authz.NewListingKitAuthorizer(nil, nil)
			require.NoError(t, err)
			live := liveRolesFunc(func(context.Context, string, string) ([]string, error) { return []string{"listingkit_operator"}, nil })
			service, err := NewBrowserAcquisition(context.Background(), db, live, permissions)
			require.NoError(t, err)
			_, request, _ := browserApplicationFixture(t)
			command := *request.Command
			request.Command = nil
			ctx := acquisitionIdentity(request.Scope.OrganizationID, request.Scope.ActorID)
			op, claim, err := service.core.operations.Start(ctx, request)
			require.NoError(t, err)
			require.True(t, claim)
			if state == sourcing.AcquisitionPrepared {
				_, err = service.core.operations.Prepare(ctx, op, command)
				require.NoError(t, err)
			}
			if state == sourcing.AcquisitionFailed {
				require.NoError(t, service.core.operations.Finish(ctx, op, state, "INVALID_SOURCE"))
			}
			recovery, err := NewBrowserAcquisition(context.Background(), browserReadOnlyDatabase(t, db), live, permissions)
			require.NoError(t, err)
			_, err = recovery.ByKey(ctx, op.Key)
			if state == sourcing.AcquisitionFailed {
				require.ErrorIs(t, err, sourcing.ErrAcquisitionFailed)
			} else {
				require.ErrorIs(t, err, sourcing.ErrAcquisitionUnknown)
			}
			current, err := service.core.operations.ByKey(ctx, op.Scope, op.Key)
			require.NoError(t, err)
			require.Equal(t, state, current.State)
			var count int64
			require.NoError(t, db.Table("product_source_publications").Count(&count).Error)
			require.Zero(t, count)
		})
	}
}

type browserPublicationCounter struct {
	sourcing.AcquisitionPublisher
	publishes atomic.Int32
}

func (p *browserPublicationCounter) Publish(ctx context.Context, command sourcing.PublicationCommand) (sourcing.PublicationReceipt, error) {
	p.publishes.Add(1)
	return p.AcquisitionPublisher.Publish(ctx, command)
}

func TestBrowserCaptureBusinessChainConcurrentSinglePublication(t *testing.T) {
	db := acquisitionDatabase(t)
	require.NoError(t, InstallAcquisitionSchema(db))
	permissions, err := authz.NewListingKitAuthorizer(nil, nil)
	require.NoError(t, err)
	live := liveRolesFunc(func(context.Context, string, string) ([]string, error) { return []string{"listingkit_operator"}, nil })
	service, err := NewBrowserAcquisition(context.Background(), db, live, permissions)
	require.NoError(t, err)
	counter := &browserPublicationCounter{AcquisitionPublisher: service.core.publisher}
	service.core.publisher = counter
	body, _, _ := browserApplicationFixture(t)
	ctx := acquisitionIdentity("browser-concurrent", "actor")
	key := uuid.NewString()
	var wg sync.WaitGroup
	results := make(chan error, 12)
	start := make(chan struct{})
	for i := 0; i < 12; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			<-start
			_, err := service.Capture(ctx, key, body)
			results <- err
		}()
	}
	close(start)
	wg.Wait()
	close(results)
	for err := range results {
		if err != nil && !errors.Is(err, sourcing.ErrAcquisitionUnknown) {
			t.Errorf("unexpected concurrent result: %v", err)
		}
	}
	require.EqualValues(t, 1, counter.publishes.Load())
	for _, table := range []string{"product_snapshot_versions", "product_source_publication_receipts", "product_acquisition_operations"} {
		var count int64
		require.NoError(t, db.Table(table).Count(&count).Error)
		require.EqualValues(t, 1, count, table)
	}
}

func TestBrowserCaptureBusinessChainCanceledAndInvalidInputsDoNotAdmit(t *testing.T) {
	db := acquisitionDatabase(t)
	require.NoError(t, InstallAcquisitionSchema(db))
	permissions, err := authz.NewListingKitAuthorizer(nil, nil)
	require.NoError(t, err)
	live := liveRolesFunc(func(context.Context, string, string) ([]string, error) { return []string{"listingkit_operator"}, nil })
	service, err := NewBrowserAcquisition(context.Background(), db, live, permissions)
	require.NoError(t, err)
	body, _, _ := browserApplicationFixture(t)
	ctx := acquisitionIdentity("browser-invalid", "actor")
	canceled, cancel := context.WithCancel(ctx)
	cancel()
	_, err = service.Capture(canceled, uuid.NewString(), body)
	require.Error(t, err)
	for _, changed := range [][]byte{
		[]byte(strings.Replace(string(body), "1.23000001", "not-a-price", 1)),
		[]byte(strings.Replace(string(body), "https://cbu01.alicdn.com/img/ibank/fixture.jpg", "javascript:alert(1)", 1)),
		append([]byte(strings.Repeat(" ", sourcing.BrowserCaptureMaxBytes)), body...),
	} {
		_, err = service.Capture(ctx, uuid.NewString(), changed)
		require.Error(t, err)
	}
	var count int64
	require.NoError(t, db.Table("product_acquisition_operations").Count(&count).Error)
	require.Zero(t, count)
}
