package canonicalinspect

import "encoding/json"

var inputSchema = json.RawMessage(`{
  "$schema":"https://json-schema.org/draft/2020-12/schema",
  "type":"object",
  "additionalProperties":false,
  "required":["task_id"],
  "properties":{
    "task_id":{"type":"string","minLength":1,"maxLength":128,"pattern":"^(?:\\S|\\S(?:.*\\S))$"}
  }
}`)

var outputSchema = json.RawMessage(`{
  "$schema":"https://json-schema.org/draft/2020-12/schema",
  "type":"object",
  "additionalProperties":false,
  "required":["task_id","product_key","snapshot_version","snapshot","source_lineage","diagnostics"],
  "properties":{
    "task_id":{"type":"string","minLength":1,"maxLength":128},
    "product_key":{"type":"string","minLength":1},
    "snapshot_version":{"type":"integer","minimum":1},
    "snapshot":{"$ref":"#/$defs/product_snapshot"},
    "source_lineage":{"anyOf":[{"$ref":"#/$defs/source_lineage"},{"type":"null"}]},
    "diagnostics":{"$ref":"#/$defs/diagnostics"}
  },
  "$defs":{
    "source_lineage":{
      "type":"object","additionalProperties":false,
      "properties":{
        "key":{"type":"string"},"type":{"type":"string"},"platform":{"type":"string"},
        "id":{"type":"string"},"url":{"type":"string"}
      }
    },
    "diagnostics":{
      "type":"object","additionalProperties":false,
      "required":["needs_review","review_reasons","warnings"],
      "properties":{
        "needs_review":{"type":"boolean"},
        "review_reasons":{"type":"array","items":{"type":"string"}},
        "warnings":{"type":"array","items":{"$ref":"#/$defs/warning"}}
      }
    },
    "product_snapshot":{
      "type":"object","additionalProperties":false,
      "properties":{
        "title":{"type":"string"},"brand":{"type":"string"},
        "category_path":{"type":"array","items":{"type":"string"}},
        "description":{"type":"string"},
        "selling_points":{"type":"array","items":{"type":"string"}},
        "seo_keywords":{"type":"array","items":{"type":"string"}},
        "attributes":{"type":"array","items":{"$ref":"#/$defs/attribute"}},
        "specifications":{"$ref":"#/$defs/specifications"},
        "variants":{"type":"array","items":{"$ref":"#/$defs/variant"}},
        "images":{"type":"array","items":{"$ref":"#/$defs/image"}},
        "review":{"$ref":"#/$defs/review"},
        "sources":{"type":"array","items":{"$ref":"#/$defs/source_record"}},
        "warnings":{"type":"array","items":{"$ref":"#/$defs/warning"}}
      }
    },
    "attribute":{
      "type":"object","additionalProperties":false,
      "properties":{"name":{"type":"string"},"value":{"type":"string"},"trace":{"$ref":"#/$defs/trace"}}
    },
    "image":{
      "type":"object","additionalProperties":false,
      "properties":{
        "url":{"type":"string"},"role":{"type":"string"},"width":{"type":"integer"},
        "height":{"type":"integer"},"trace":{"$ref":"#/$defs/trace"}
      }
    },
    "variant":{
      "type":"object","additionalProperties":false,
      "properties":{
        "source_id":{"type":"string"},"title":{"type":"string"},"sku":{"type":"string"},
        "attributes":{"type":"array","items":{"$ref":"#/$defs/attribute"}},
        "price":{"$ref":"#/$defs/price"},"stock":{"type":"integer"},
        "images":{"type":"array","items":{"$ref":"#/$defs/image"}},
        "barcode":{"type":"string"},"is_default":{"type":"boolean"},"trace":{"$ref":"#/$defs/trace"}
      }
    },
    "price":{
      "type":"object","additionalProperties":false,
      "properties":{
        "currency":{"type":"string"},"amount":{"type":"number"},"compare_at":{"type":"number"},
        "cost_price":{"type":"number"},"wholesale_min":{"type":"integer"}
      }
    },
    "specifications":{
      "type":"object","additionalProperties":false,
      "properties":{
        "dimensions":{"$ref":"#/$defs/dimensions"},"weight":{"$ref":"#/$defs/weight"},
        "package":{"$ref":"#/$defs/package"},
        "technical":{
          "type":"object",
          "propertyNames":{"not":{"enum":["tenant_id","user_id","roles","permission","call_id","agent_id","agent_version","agent_run_id","business_task_id","trace_id","idempotency_key","tool_id","tool_version"]}},
          "additionalProperties":{"type":"string"}
        }
      }
    },
    "dimensions":{
      "type":"object","additionalProperties":false,
      "properties":{"length":{"type":"number"},"width":{"type":"number"},"height":{"type":"number"},"unit":{"type":"string"}}
    },
    "weight":{
      "type":"object","additionalProperties":false,
      "properties":{"value":{"type":"number"},"unit":{"type":"string"}}
    },
    "package":{
      "type":"object","additionalProperties":false,
      "properties":{"dimensions":{"$ref":"#/$defs/dimensions"},"weight":{"$ref":"#/$defs/weight"},"quantity":{"type":"integer"}}
    },
    "review":{
      "type":"object","additionalProperties":false,"required":["needs_review"],
      "properties":{"needs_review":{"type":"boolean"},"reasons":{"type":"array","items":{"type":"string"}}}
    },
    "warning":{
      "type":"object","additionalProperties":false,"required":["code","message"],
      "properties":{"code":{"type":"string"},"field":{"type":"string"},"message":{"type":"string"}}
    },
    "trace":{
      "type":"object","additionalProperties":false,
      "properties":{
        "sources":{"type":"array","items":{"$ref":"#/$defs/source_record"}},
        "confidence":{"type":"number"},"is_inferred":{"type":"boolean"},"needs_review":{"type":"boolean"}
      }
    },
    "source_record":{
      "type":"object","additionalProperties":false,
      "properties":{
        "type":{"type":"string"},"detail":{"type":"string"},"platform":{"type":"string"},
        "source_id":{"type":"string"},"source_version":{"type":"string"},"reference_type":{"type":"string"},
        "url":{"type":"string"},"snapshot_id":{"type":"string"},"checksum":{"type":"string"},
        "captured_at":{"type":"string"},"source_run_id":{"type":"string"},"request_id":{"type":"string"},
        "notes":{"type":"array","items":{"type":"string"}}
      }
    }
  }
}`)

func InputSchema() json.RawMessage  { return append(json.RawMessage(nil), inputSchema...) }
func OutputSchema() json.RawMessage { return append(json.RawMessage(nil), outputSchema...) }
