package httpapi

import (
	"net/http"

	"task-processor/internal/httproute"
)

func appendAdminRouteDescriptors(routes []httproute.Descriptor, handler AdminRouteHandler) []httproute.Descriptor {
	return append(routes,
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/stores", Module: "listing-kit-admin", Handler: handler.ListAdminStores},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/stores/simple", Module: "listing-kit-admin", Handler: handler.ListSimpleAdminStores},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/stores/deleted", Module: "listing-kit-admin", Handler: handler.ListDeletedAdminStores},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/stores/:id", Module: "listing-kit-admin", Handler: handler.GetAdminStore},
		httproute.Descriptor{Method: http.MethodPost, Path: "/api/v1/listing-kits/admin/stores", Module: "listing-kit-admin", Handler: handler.CreateAdminStore},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/stores/:id", Module: "listing-kit-admin", Handler: handler.UpdateAdminStore},
		httproute.Descriptor{Method: http.MethodPatch, Path: "/api/v1/listing-kits/admin/stores/:id/status", Module: "listing-kit-admin", Handler: handler.UpdateAdminStoreStatus},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/stores/:id", Module: "listing-kit-admin", Handler: handler.DeleteAdminStore},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/stores/:id/restore", Module: "listing-kit-admin", Handler: handler.RestoreAdminStore},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/stores/:id/permanent", Module: "listing-kit-admin", Handler: handler.PermanentlyDeleteAdminStore},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/stores/:id/extend-validity", Module: "listing-kit-admin", Handler: handler.ExtendAdminStoreValidity},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/store-statistics", Module: "listing-kit-admin", Handler: handler.ListAdminStoreStatistics},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/import-tasks", Module: "listing-kit-admin", Handler: handler.ListAdminImportTasks},
		httproute.Descriptor{Method: http.MethodPost, Path: "/api/v1/listing-kits/admin/import-tasks/batch", Module: "listing-kit-admin", Handler: handler.BatchCreateAdminImportTasks},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/import-tasks/:id", Module: "listing-kit-admin", Handler: handler.DeleteAdminImportTask},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/filter-rules", Module: "listing-kit-admin", Handler: handler.ListAdminFilterRules},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/filter-rules/:id", Module: "listing-kit-admin", Handler: handler.GetAdminFilterRule},
		httproute.Descriptor{Method: http.MethodPost, Path: "/api/v1/listing-kits/admin/filter-rules", Module: "listing-kit-admin", Handler: handler.CreateAdminFilterRule},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/filter-rules/:id", Module: "listing-kit-admin", Handler: handler.UpdateAdminFilterRule},
		httproute.Descriptor{Method: http.MethodPatch, Path: "/api/v1/listing-kits/admin/filter-rules/:id/status", Module: "listing-kit-admin", Handler: handler.UpdateAdminFilterRuleStatus},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/filter-rules/:id", Module: "listing-kit-admin", Handler: handler.DeleteAdminFilterRule},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/profit-rules", Module: "listing-kit-admin", Handler: handler.ListAdminProfitRules},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/profit-rules/:id", Module: "listing-kit-admin", Handler: handler.GetAdminProfitRule},
		httproute.Descriptor{Method: http.MethodPost, Path: "/api/v1/listing-kits/admin/profit-rules", Module: "listing-kit-admin", Handler: handler.CreateAdminProfitRule},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/profit-rules/:id", Module: "listing-kit-admin", Handler: handler.UpdateAdminProfitRule},
		httproute.Descriptor{Method: http.MethodPatch, Path: "/api/v1/listing-kits/admin/profit-rules/:id/status", Module: "listing-kit-admin", Handler: handler.UpdateAdminProfitRuleStatus},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/profit-rules/:id", Module: "listing-kit-admin", Handler: handler.DeleteAdminProfitRule},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/pricing-rules", Module: "listing-kit-admin", Handler: handler.ListAdminPricingRules},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/pricing-rules/:id", Module: "listing-kit-admin", Handler: handler.GetAdminPricingRule},
		httproute.Descriptor{Method: http.MethodPost, Path: "/api/v1/listing-kits/admin/pricing-rules", Module: "listing-kit-admin", Handler: handler.CreateAdminPricingRule},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/pricing-rules/:id", Module: "listing-kit-admin", Handler: handler.UpdateAdminPricingRule},
		httproute.Descriptor{Method: http.MethodPatch, Path: "/api/v1/listing-kits/admin/pricing-rules/:id/status", Module: "listing-kit-admin", Handler: handler.UpdateAdminPricingRuleStatus},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/pricing-rules/:id", Module: "listing-kit-admin", Handler: handler.DeleteAdminPricingRule},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/operation-strategies", Module: "listing-kit-admin", Handler: handler.ListAdminOperationStrategies},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/operation-strategies/:id", Module: "listing-kit-admin", Handler: handler.GetAdminOperationStrategy},
		httproute.Descriptor{Method: http.MethodPost, Path: "/api/v1/listing-kits/admin/operation-strategies", Module: "listing-kit-admin", Handler: handler.CreateAdminOperationStrategy},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/operation-strategies/:id", Module: "listing-kit-admin", Handler: handler.UpdateAdminOperationStrategy},
		httproute.Descriptor{Method: http.MethodPatch, Path: "/api/v1/listing-kits/admin/operation-strategies/:id/status", Module: "listing-kit-admin", Handler: handler.UpdateAdminOperationStrategyStatus},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/operation-strategies/:id", Module: "listing-kit-admin", Handler: handler.DeleteAdminOperationStrategy},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/sensitive-words", Module: "listing-kit-admin", Handler: handler.ListAdminSensitiveWords},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/sensitive-words/:id", Module: "listing-kit-admin", Handler: handler.GetAdminSensitiveWord},
		httproute.Descriptor{Method: http.MethodPost, Path: "/api/v1/listing-kits/admin/sensitive-words", Module: "listing-kit-admin", Handler: handler.CreateAdminSensitiveWord},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/sensitive-words/:id", Module: "listing-kit-admin", Handler: handler.UpdateAdminSensitiveWord},
		httproute.Descriptor{Method: http.MethodPatch, Path: "/api/v1/listing-kits/admin/sensitive-words/:id/status", Module: "listing-kit-admin", Handler: handler.UpdateAdminSensitiveWordStatus},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/sensitive-words/:id", Module: "listing-kit-admin", Handler: handler.DeleteAdminSensitiveWord},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/generation-topic-catalog", Module: "listing-kit-admin", Handler: handler.ListAdminGenerationTopicCatalog},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/generation-topic-overrides", Module: "listing-kit-admin", Handler: handler.ListAdminGenerationTopicOverrides},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/generation-topic-overrides/:id", Module: "listing-kit-admin", Handler: handler.GetAdminGenerationTopicOverride},
		httproute.Descriptor{Method: http.MethodPost, Path: "/api/v1/listing-kits/admin/generation-topic-overrides", Module: "listing-kit-admin", Handler: handler.CreateAdminGenerationTopicOverride},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/generation-topic-overrides/:id", Module: "listing-kit-admin", Handler: handler.UpdateAdminGenerationTopicOverride},
		httproute.Descriptor{Method: http.MethodPatch, Path: "/api/v1/listing-kits/admin/generation-topic-overrides/:id/status", Module: "listing-kit-admin", Handler: handler.UpdateAdminGenerationTopicOverrideStatus},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/generation-topic-overrides/:id", Module: "listing-kit-admin", Handler: handler.DeleteAdminGenerationTopicOverride},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/generation-topic-policies", Module: "listing-kit-admin", Handler: handler.ListAdminGenerationTopicPolicies},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/generation-topic-policies/:id", Module: "listing-kit-admin", Handler: handler.GetAdminGenerationTopicPolicy},
		httproute.Descriptor{Method: http.MethodPost, Path: "/api/v1/listing-kits/admin/generation-topic-policies", Module: "listing-kit-admin", Handler: handler.CreateAdminGenerationTopicPolicy},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/generation-topic-policies/:id", Module: "listing-kit-admin", Handler: handler.UpdateAdminGenerationTopicPolicy},
		httproute.Descriptor{Method: http.MethodPatch, Path: "/api/v1/listing-kits/admin/generation-topic-policies/:id/status", Module: "listing-kit-admin", Handler: handler.UpdateAdminGenerationTopicPolicyStatus},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/generation-topic-policies/:id", Module: "listing-kit-admin", Handler: handler.DeleteAdminGenerationTopicPolicy},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/product-import-mappings", Module: "listing-kit-admin", Handler: handler.ListAdminProductImportMappings},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/product-import-mappings/:id", Module: "listing-kit-admin", Handler: handler.GetAdminProductImportMapping},
		httproute.Descriptor{Method: http.MethodPost, Path: "/api/v1/listing-kits/admin/product-import-mappings", Module: "listing-kit-admin", Handler: handler.CreateAdminProductImportMapping},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/product-import-mappings/:id", Module: "listing-kit-admin", Handler: handler.UpdateAdminProductImportMapping},
		httproute.Descriptor{Method: http.MethodPatch, Path: "/api/v1/listing-kits/admin/product-import-mappings/:id/status", Module: "listing-kit-admin", Handler: handler.UpdateAdminProductImportMappingStatus},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/product-import-mappings/:id", Module: "listing-kit-admin", Handler: handler.DeleteAdminProductImportMapping},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/categories", Module: "listing-kit-admin", Handler: handler.ListAdminCategories},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/categories/:id", Module: "listing-kit-admin", Handler: handler.GetAdminCategory},
		httproute.Descriptor{Method: http.MethodPost, Path: "/api/v1/listing-kits/admin/categories", Module: "listing-kit-admin", Handler: handler.CreateAdminCategory},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/categories/:id", Module: "listing-kit-admin", Handler: handler.UpdateAdminCategory},
		httproute.Descriptor{Method: http.MethodPatch, Path: "/api/v1/listing-kits/admin/categories/:id/status", Module: "listing-kit-admin", Handler: handler.UpdateAdminCategoryStatus},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/categories/:id", Module: "listing-kit-admin", Handler: handler.DeleteAdminCategory},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/product-data", Module: "listing-kit-admin", Handler: handler.ListAdminProductData},
		httproute.Descriptor{Method: http.MethodGet, Path: "/api/v1/listing-kits/admin/product-data/:id", Module: "listing-kit-admin", Handler: handler.GetAdminProductData},
		httproute.Descriptor{Method: http.MethodPost, Path: "/api/v1/listing-kits/admin/product-data", Module: "listing-kit-admin", Handler: handler.CreateAdminProductData},
		httproute.Descriptor{Method: http.MethodPut, Path: "/api/v1/listing-kits/admin/product-data/:id", Module: "listing-kit-admin", Handler: handler.UpdateAdminProductData},
		httproute.Descriptor{Method: http.MethodPatch, Path: "/api/v1/listing-kits/admin/product-data/:id/status", Module: "listing-kit-admin", Handler: handler.UpdateAdminProductDataStatus},
		httproute.Descriptor{Method: http.MethodDelete, Path: "/api/v1/listing-kits/admin/product-data/:id", Module: "listing-kit-admin", Handler: handler.DeleteAdminProductData},
	)
}
