package imageagentworker

import (
	"bytes"
	"context"
	"image"
	"image/color"
	"image/png"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	awss3 "github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/google/uuid"
	"github.com/stretchr/testify/require"

	"task-processor/internal/core/config"
	"task-processor/internal/imageagent"
	"task-processor/internal/imageagent/objectstore"
	s3integration "task-processor/internal/integration/s3"
)

func TestIsolatedTrialMinIOPreservesRecoversAndPublishesImmutableAsset(t *testing.T) {
	endpoint := os.Getenv("ISSUE487_MINIO_ENDPOINT")
	if endpoint == "" || os.Getenv("ISSUE487_MINIO_EXCLUSIVE") != "ISOLATED_TRIAL_ONLY" {
		t.Skip("requires the dedicated disposable issue 487 MinIO container")
	}
	if !strings.HasPrefix(endpoint, "http://127.0.0.1:") {
		t.Fatal("MinIO compatibility test refuses non-loopback endpoint")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	client, err := s3integration.NewClient(s3integration.ClientConfig{Region: "us-east-1", Endpoint: endpoint, AccessKeyID: "issue487_local", SecretAccessKey: "issue487_local_secret", UsePathStyle: true})
	require.NoError(t, err)
	bucket := "issue487-" + strings.ReplaceAll(uuid.NewString(), "-", "")[:20]
	_, err = client.CreateBucket(ctx, &awss3.CreateBucketInput{Bucket: aws.String(bucket)})
	require.NoError(t, err)
	storeConfig := config.ImageAgentArtifactStoreConfig{Enabled: true, Provider: "s3", PublicBase: "https://localhost:19444/image-agent-assets/" + bucket, IsolatedTrialGeneratedURLs: true, S3: config.ImageAgentArtifactStoreS3Config{Bucket: bucket, Region: "us-east-1", Endpoint: endpoint, AccessKeyID: "issue487_local", SecretAccessKey: "issue487_local_secret", UsePathStyle: true, ArtifactMode: "aws"}}
	store, err := buildImageAgentDurableArtifactStore(&config.Config{ImageAgent: config.ImageAgentConfig{ArtifactStore: storeConfig}}, defaultImageAgentArtifactTiming, nil)
	require.NoError(t, err)
	imageBytes := new(bytes.Buffer)
	pixels := image.NewRGBA(image.Rect(0, 0, 2, 2))
	for y := 0; y < 2; y++ {
		for x := 0; x < 2; x++ {
			pixels.Set(x, y, color.White)
		}
	}
	require.NoError(t, png.Encode(imageBytes, pixels))
	identity := imageagent.SlotExternalEffectIdentity{RunScope: imageagent.RunScope{TenantID: "org-a", OwnerUserID: "actor-a", RunID: "run-a"}, PlanRevision: 1, SlotID: "main", Attempt: 1}
	prepared, err := store.PrepareSlotArtifacts(objectstore.PrepareSlotArtifactsInput{Identity: identity, Assets: []objectstore.ArtifactInput{{Bytes: imageBytes.Bytes(), ContentType: "image/png", Width: 2, Height: 2, SourceAssetID: "catalog-image-1", Operations: []string{"render_white_background"}}}})
	require.NoError(t, err)
	require.NoError(t, store.PreserveSlotArtifacts(ctx, identity, prepared))
	recovered, err := store.RecoverSlotArtifacts(ctx, identity, prepared.Manifest)
	require.NoError(t, err)
	require.Equal(t, prepared.Manifest, recovered.Manifest)
	require.NoError(t, store.EnsureStaged(ctx, recovered))
	final, err := store.Finalize(ctx, recovered.Manifest)
	require.NoError(t, err)
	require.Len(t, final.Assets, 1)
	require.Equal(t, "image-agent/public", strings.Join(strings.Split(final.Assets[0].ObjectKey, "/")[:2], "/"))
	require.Equal(t, storeConfig.PublicBase+"/"+final.Assets[0].ObjectKey, store.PublicURL(final.Assets[0].ObjectKey))
	require.NoError(t, store.EnsureStaged(ctx, recovered))
	second, err := store.Finalize(ctx, recovered.Manifest)
	require.NoError(t, err)
	require.Equal(t, final, second, "recovery replay must not overwrite generated bytes")
}
