apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: casdoor-phone-idp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: task-processor-secrets
    kind: ClusterSecretStore
  target:
    name: casdoor-phone-idp-secret
    creationPolicy: Owner
  data:
    - secretKey: CASDOOR_POSTGRES_PASSWORD
      remoteRef:
        key: task-processor/prod/casdoor-phone-idp
        property: CASDOOR_POSTGRES_PASSWORD
    - secretKey: CASDOOR_TENCENT_SECRET_ID
      remoteRef:
        key: task-processor/prod/casdoor-phone-idp
        property: CASDOOR_TENCENT_SECRET_ID
    - secretKey: CASDOOR_TENCENT_SECRET_KEY
      remoteRef:
        key: task-processor/prod/casdoor-phone-idp
        property: CASDOOR_TENCENT_SECRET_KEY
    - secretKey: CASDOOR_TENCENT_SMS_APP_ID
      remoteRef:
        key: task-processor/prod/casdoor-phone-idp
        property: CASDOOR_TENCENT_SMS_APP_ID
    - secretKey: CASDOOR_TENCENT_SMS_SIGN_NAME
      remoteRef:
        key: task-processor/prod/casdoor-phone-idp
        property: CASDOOR_TENCENT_SMS_SIGN_NAME
    - secretKey: CASDOOR_TENCENT_SMS_TEMPLATE_ID
      remoteRef:
        key: task-processor/prod/casdoor-phone-idp
        property: CASDOOR_TENCENT_SMS_TEMPLATE_ID
    - secretKey: CASDOOR_OIDC_CLIENT_SECRET
      remoteRef:
        key: task-processor/prod/casdoor-phone-idp
        property: CASDOOR_OIDC_CLIENT_SECRET
